### PR TITLE
Revert "Added direct collection access to future collection item feature test"

### PR DESCRIPTION
**Pull request by mattr-**
Reverts jekyll/jekyll#6151

Collection handling output doesn't take `future` into account for non output files.

### CODE REVIEW

**Comment by ashmaroli** [comment]
@mattr- before you <kbd>Merge</kbd> this, I'd like you to consider reviewing #6497 which *I feel* resolves the issue related to this PR ***and*** the associated original Issue report #5953

**Comment by mattr-** [comment]
Going to go ahead and merge this since the tests are passing agin.

**Comment by ashmaroli** [comment]
@mattr- if you have access to the repo's settings, I recommend disabling merge to `master` unless Travis is green..

/cc @parkr

**Comment by DirtyF** [comment]
@ashmaroli it is… except for administrators 😅

**Pull request merged**
