### PR TITLE
Ci/GitHub actions

### PR DESCRIPTION
**Pull request by ethomson**
This is a 🙋 feature or enhancement. Picking up  #7785 and seeing if I can sort out the failures.

### CODE REVIEW

**Comment by ethomson** [comment]
Alas, I'm going to have to 👀 more deeply at the line ending issues.

**Comment by ashmaroli** [comment]
@ethomson Thank you for working on this. A few suggestions in case you're planning to push more commits:
- The primary reason for failures at the moment is RuboCop offenses. Please run `script/fmt -a` (or `bundle exec rubocop -a` to correct them.)
- It'd be better if the `#temp_dir` was moved into the `test/helper.rb` file and refactored to automatically join given arguments (see `module DirectoryHelpers` in the test helper for clarification / reference).

That said, in case you're not able to make the above changes, let me know. I shall push them myself. :smiley: 

P.S. *Is there a way to configure GitHub Actions suite to re-run individual check runs?*

**Comment by ethomson** [comment]
Happy to make these changes - let me know if that's not what you have in mind - it looks like there's still a few test failures that I'm not sure I understand yet, could you help me understand them?

> P.S. Is there a way to configure GitHub Actions suite to re-run individual check runs?

Unfortunately, no, not yet.  You can re-run the entire build workflow at the moment, not individual check runs.

**Comment by ashmaroli** [comment]
> it looks like there's still a few test failures that I'm not sure I understand yet

Actually, those failures are false negatives. They usually disappear with reruns.
Overall, the diff looks good to me.

**Comment by ashmaroli** [comment]
@ethomson Looks like there is bug when a *rerun check-suite* event is triggered. The re-run event is not being intercepted properly. The Actions for the latest commit are still *in the yellow..*

**Comment by ethomson** [comment]
>  Looks like there is bug when a rerun check-suite event is triggered. The re-run event is not being intercepted properly. The Actions for the latest commit are still in the yellow..

Ouch, thanks for letting me know.  I think that this was part of the [availability issue](https://www.githubstatus.com/incidents/b54zv9nz8m01) we had earlier today.  Could you try re-running it again so that I can see what happens?

**Comment by ashmaroli** [comment]
> Could you try re-running it again so that I can see what happens?

Perhaps I don't have the required privileges, or perhaps it is just bugs. But once I click the rerun button. the only appreciable changes are:
- Flash message stating that rerun requested successfully
- Button text changes to `Cancel check suite`
- Check status indicator updates to *yellow*

However when I consequently click the `Cancel check suite`, only the flash message is updated and rendered. The button text remains unchanged.

In both situations, no change is discernible in the VM panels.

**Comment by ethomson** [comment]
Thanks for the information, we're investigating why that particular check run is misbehaving.  In the meantime, I pushed an update to make sure that checks run were working more generally.

**Comment by ashmaroli** [comment]
@ethomson Thanks for the trigger. All check runs in the Actions suite have passed successfully.

**Comment by mattr-** [comment]
@jekyllbot: merge +dev

**Pull request merged**
