### PR TITLE
Stash documents `write?` attribute in a variable

### PR DESCRIPTION
**Pull request by ashmaroli**
- This is an :zap: optimization change.

## Summary

Instead of checking `collection&.write? && site.publisher.publish?(self)` on every call to the `:write?` method, compute the result once per instance and reuse the result on subsequent calls.

## Context

`document.write?` is invoked via various core classes (e.g. `Site`, `Regenerator`) and in-house plugins (e.g. `jekyll-mentions`, `jemoji`)

### CODE REVIEW

**Review by DirtyF — APPROVED** [review]
Good catch 🥇

**Comment by ashmaroli** [comment]
Thanks :)
@jekyllbot: merge +fix

**Comment by DirtyF** [comment]
@ashmaroli I hadn't build Jekyll website locally for a few months, last time it was taking 6.2s on my machine, current `master` is now at 3.6s. 🚀 👏

**Comment by ashmaroli** [comment]
The recent optimizations aren't major ones. Just minor bottlenecks I discovered when profiling various sites in the wild.
Our docs site is too small to get a noticeable improvement from these changes..
Thanks for the encouragement anyways. :smiley: 
Cheers :clinking_glasses:

**Pull request merged**
