### PR TITLE
corrects lsi docs

### PR DESCRIPTION
**Pull request by davidsilvasmith**
This updates the Latent Semantic Indexing docs to state how `site.related_posts` are pulled when lsi is off. Also states that LSI isn't supported on github pages.

### CODE REVIEW

**Comment by davidsilvasmith** [comment]
Sorry I'm new to submitting pull requests. I think my repo was out of date. I'll try resolving and resubmitting.

**Comment by envygeeks** [comment]
Please pick your changes and scrap that merge because it's not necessary and then we can look at it.

**Comment by davidsilvasmith** [comment]
I think I fixed it. It says it can automatically be merged. no? The changed files tab is correct.

**Comment by parkr** [comment]
i think this is taken care of in your other pr

**Comment by envygeeks** [comment]
Awesome!

**Pull request closed without merging**
