### PR TITLE
docs: Jekyll 3 paginate instructions update

### PR DESCRIPTION
**Pull request by nikolas**
* Changed the unmaintained `jekyll-paginate` gem to `jekyll-paginate-v2` - https://github.com/sverrirs/jekyll-paginate-v2
* Added explicit example of how to add this to your Gemfile

### CODE REVIEW

**Comment by ashmaroli** [comment]
Do note that GitHub Pages do not support the `v2` gem.. only the older `jekyll-paginate`

/cc @jekyll/documentation

**Comment by nikolas** [comment]
Ah okay, then we should note that in the docs and have examples for both `jekyll-paginate` and `jekyll-paginate-v2`.

**Comment by pathawks** [comment]
@nikolas Thanks for the PR! :beers:

AFAIK We don't own or control **jekyll-paginate-v2**. I'm not sure that we are responsible for its documentation.

**Comment by DirtyF** [comment]
@nikolas What we could do is mention @sverrirs plugin and explain why one might want to use `jekyll-paginate-v2`, i.e. for handling categories and tags pagination. For now this is not an official plugin and it's not supported by GitHub Pages, so we can't just make it the defaults in our docs.

If you want to take a shot at it, we'll happily review your submission. Thanks for bringing this to our attention. 👈

**Comment by sverrirs** [comment]
Thanks for the mention. 

Just a FYI, I would be more than happy include more people on the jekyll-paginate-v2 plugin project if you think including it would make a positive contribution to the official distribution. 

I'm also willing to do the work necessary to bring it up to any standards you might require of official plugins.

**Comment by DirtyF** [comment]
https://jekyllrb.com/docs/pagination/#enable-pagination now mentions @sverris `jekyll-paginate-v2`.

**Pull request closed without merging**
