### PR TITLE
Sort static files just once.

### PR DESCRIPTION
**Pull request by parkr**
Ref: #2075.

### CODE REVIEW

**Comment by parkr** [comment]
> It looks like YAML keys with digits in them are no longer allowed.

This could have to do with the strict parser. If you search for `strict` in lib/jekyll.rb and remove that line, does it work?

> Liquid seems to be parsing vendor/JS files, too

If these files are `include_relative`'d anywhere, then this'll happen as a result of the rendering process. :/

**Comment by mattr-** [comment]
> > Liquid seems to be parsing vendor/JS files, too

> If these files are include_relative'd anywhere, then this'll happen as a result of the rendering process. :/

That would mean that we'd need to work around this change in behavior before releasing Liquid 3 in a Jekyll 2.x version, correct?

**Comment by parkr** [comment]
> That would mean that we'd need to work around this change in behavior before releasing Liquid 3 in a Jekyll 2.x version, correct?

We'd have to have like `{% include_relative blah.js norender %}` – I think we manually render in the `IncludeTag` but not sure off the top of my head. I don't know if it affects Jekyll 2 – this is a Jekyll 3 PR.

**Comment by gjtorikian** [comment]
> This could have to do with the strict parser. If you search for strict in lib/jekyll.rb and remove that line, does it work?

Yeeeeeep, that was it; turning `strict` off made it happy. Whatever, though, I'm fine with it not accepting numbers.

> We'd have to have like {% include_relative blah.js norender %}

*shrug* https://github.com/janl/mustache.js/pull/418 

In the meantime, it's just one character.

**Pull request merged**
