### PR TITLE
Update cucumber gem version to 5.1.2

### LINKED ISSUE #8370: Update dependency constraint to allow for cucumber v5.1.1
Hey there! :wave:

I noticed that the constraint you have for cucumber doesn't allow for the latest version to be used.

The constraint I found was `~> 4.1`, and the latest version available is `5.1.1`.

Can you look into updating that constraint so our users can use the latest and greatest version? Thanks! :revolving_hearts:

### LINKED ISSUE #8402: Update dependency constraint to allow for cucumber v5.1.2
Hey there! :wave:

I noticed that the constraint you have for cucumber doesn't allow for the latest version to be used.

The constraint I found was `~> 4.1`, and the latest version available is `5.1.2`.

Can you look into updating that constraint so our users can use the latest and greatest version? Thanks! :revolving_hearts:

### PR DESCRIPTION
**Pull request by jesuslerma**
This is a project maintenance.

## Summary
Update cucumber gem from version 4.1 to 5.1.2.

## Context
Closes #8402
Closes #8370

### CODE REVIEW

**Review by DirtyF — APPROVED** [review]
Thanks @jesuslerma 🙏

**Comment by DirtyF** [comment]
@jekyll: merge +dev

**Comment by DirtyF** [comment]
Cucumber 5.1 has now a `publish` option, here's a preview of the output ([reports](https://reports.cucumber.io/reports/4033c843-6ece-4255-b1c1-95d64bd58cdc) only last 24h for now), it might be a nice addition to document features.

cucumber-publish

**Comment by ashmaroli** [comment]
@jesuslerma Thank you for submitting this pull request. Glad to know that our legacy cucumber tests still work fine..


> Cucumber 5.1 has now a `publish` option

@DirtyF This is awesome! If you know the best way to integrate the report with `jekyllrb.com`, go for it!

**Comment by jesuslerma** [comment]
I will happy to help doing that - cuscumber publish :)

**Comment by DirtyF** [comment]
The publish option is alreaady on, a 24h link is added at the end of the cucumber test suite=

https://travis-ci.org/github/jekyll/jekyll/jobs/730550503#L803

**Pull request merged**
