### PR TITLE
Add Event Machine into Gemfile

### PR DESCRIPTION
**Pull request by rodrigoargumedo**
This is a 🙋 feature or enhancement.

- I've adjusted the documentation (if it's a feature or enhancement)

## Summary

Event Machine does not correctly load on Windows. To accomplish the jekyll serve --livereload behavior, the gem would be needed to explicitly bundle together that it can work with all platforms including Windows.

```ruby
gem 'eventmachine', '~> 1.2', platform: :ruby
```

## Context

I was receiving an traceback error from that Ruby Event Machine does not exist in the local machine. So, the fix was by bundling the ruby platform of Event Machine.  Here is the traceback of the problem:

```
Traceback (most recent call last):
        22: from C:/Ruby26-x64/bin/jekyll:23:in `<main>'
        21: from C:/Ruby26-x64/bin/jekyll:23:in `load'
        20: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/jekyll-3.8.5/exe/jekyll:15:in `<top (required)>'
        19: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
        18: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
        17: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
        16: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
        15: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
        14: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/jekyll-3.8.5/lib/jekyll/commands/serve.rb:75:in `block (2 levels) in init_with_program'
        13: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/jekyll-3.8.5/lib/jekyll/commands/serve.rb:93:in `start'
        12: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/jekyll-3.8.5/lib/jekyll/commands/serve.rb:93:in `each'
        11: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/jekyll-3.8.5/lib/jekyll/commands/serve.rb:93:in `block in start'
        10: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/jekyll-3.8.5/lib/jekyll/commands/serve.rb:101:in `process'
         9: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/jekyll-3.8.5/lib/jekyll/commands/serve.rb:147:in `register_reload_hooks'
         8: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/jekyll-3.8.5/lib/jekyll/commands/serve.rb:147:in `require_relative'
         7: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/jekyll-3.8.5/lib/jekyll/commands/serve/live_reload_reactor.rb:3:in `<top (required)>'
         6: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/jekyll-3.8.5/lib/jekyll/commands/serve/live_reload_reactor.rb:3:in `require'
         5: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/em-websocket-0.5.1/lib/em-websocket.rb:3:in `<top (required)>'
         4: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/em-websocket-0.5.1/lib/em-websocket.rb:3:in `require'
         3: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/eventmachine-1.2.7-x64-mingw32/lib/eventmachine.rb:8:in `<top (required)>'
         2: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/eventmachine-1.2.7-x64-mingw32/lib/eventmachine.rb:8:in `require'
         1: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/eventmachine-1.2.7-x64-mingw32/lib/rubyeventmachine.rb:2:in `<top (required)>'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/eventmachine-1.2.7-x64-mingw32/lib/rubyeventmachine.rb:2:in `require': cannot load such file -- 2.6/rubyeventmachine (LoadError)
```

### CODE REVIEW

**Comment by mattr-** [comment]
Based on my reading of your report, it seems like this is an event machine (EM) problem and not a jekyll problem. Are they recommending in their documentation to load EM this way?

**Comment by rodrigoargumedo** [comment]
According to the sources I've encountered, Ruby 2.4 and newer do not properly support mingw and mingw-x64 (Windows) platform for Event Machine and have recommended using this method until they come with a solution.

[Source 1](https://github.com/oneclick/rubyinstaller2/issues/96#issuecomment-361549776)
[Source 2](https://stackoverflow.com/a/58683890/4316935)

**Comment by rodrigoargumedo** [comment]
Travis CI and AppVeyor are failing and I also checked this on my local computer. How strange that it passed without errors on the local env and others did not.

**Comment by solarane** [comment]
@rodrigoargumedo Possibly related: https://github.com/eventmachine/eventmachine/issues/907

**Pull request closed without merging**
