### PR TITLE
Fix passing multiline params to include tag when using the variable syntax 

### LINKED ISSUE #6857: Passing parameters to include-by-variable across multiple lines
- [X] I believe this to be a bug, not a question about using Jekyll.
- [X] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
    - github-pages (179), jekyll (3.6.2)
- [X] I ran `jekyll doctor` to check my configuration
- [X] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [X] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [x] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [ ] I was trying to build.
- [ ] It was another bug.

## My Reproduction Steps

When including a file based on a variable name (`{% include {{file}} ... %}`), only variables from the first line are passed to the partial. Anything after the first newline is ignored. This is weird, because newlines are allowed if the filename is included explicitly.

### Minimal example

**test_lvl1.html:**
```
---
---
{% capture nextlevel %}test_lvl2.html{% endcapture %}
<style>div {border: solid 1px black; margin:1em;}</style>
<div id="lvl1">
    <h4>Level 1</h4>
    {% include {{nextlevel}} a="level 1"
       b="level 1" %}
</div>
```

**_includes/test_lvl2.html:**
```
<div id="lvl2">
    <h4>Level 2</h4>
    <blockquote>{{include|inspect}}</blockquote>
</div>
```

One would expect that both `include.a` and `include.b` would be available in the partial, but only the first one is.

**output**:
```
<style>div {border: solid 1px black; margin:1em;}</style>
<div id="lvl1">
    <h4>Level 1</h4>
    <div id="lvl3">
    <h4>Level 2</h4>
    <blockquote>{&quot;a&quot;=&gt;&quot;level 1&quot;}</blockquote>
</div>
</div>
```
screen shot 2018-03-17 at 15 55 35

## The Output I Wanted
The environment should have also included `b`.

```
<style>div {border: solid 1px black; margin:1em;}</style>
<div id="lvl1">
    <h4>Level 1</h4>
    <div id="lvl3">
    <h4>Level 2</h4>
    <blockquote>{&quot;a&quot;=&gt;&quot;level 1&quot;, &quot;b&quot;=&gt;&quot;level 1&quot;}</blockquote>
</div>
</div>
```

_Note: Issue first filed against liquid as https://github.com/Shopify/liquid/issues/994_

### PR DESCRIPTION
**Pull request by ashmaroli**
Fixes #6857

### CODE REVIEW

**Comment by parkr** [comment]
Needs a test! AFAIK, `.` should include `\s`?

**Comment by pathawks** [comment]
`.` does not match newlines unless used in multiline mode (`/m`)

**Comment by ashmaroli** [comment]
> unless used in multiline mode (`/m`)

:man_facepalming: of course..! `/m` is the better alternative..

**Comment by DirtyF** [comment]
@jekyllbot: merge +fix

**Pull request merged**
