### PR TITLE
Hosting with AWS Amplify

### PR DESCRIPTION
**Pull request by swaminator**
Added hosting with AWS Amplify to the docs.

### CODE REVIEW

**Comment by pathawks** [comment]
How is Amplify better/different than S3+CloudFront?

**Comment by chrisfinazzo** [comment]
That's @swaminator's call, but AWS (in a number of circumstances) is a common deployment target, so I'm 👍 on this just to give people another option.

**Comment by pathawks** [comment]
> but AWS (in a number of circumstances) is a common deployment target

S3 and CloudFront _is_ AWS; that's why I'm confused.

**Comment by chrisfinazzo** [comment]
@pathawks I haven't used it, but do they make any distinction re deployment between the different "classes" (Amazon's term) of storage? E.g, Standard, Glacier, and Amplify which is focused on mobile. Someone smarter than me probably knows the answer.

confused

**Comment by DirtyF** [comment]
@swaminator Just curious: compared to free solutions like Github Pages, GitLab Pages or the generous Netlify free tiers, how does AWS Amplify compares for static website hosting?

**Comment by swaminator** [comment]
Thanks @DirtyF! We have a free tier for the first 12 months: https://aws.amazon.com/amplify/console/pricing/ 
As for how we compare to other services, we focus on full-stack deployments with the Amplify CLI (though our customers have asked for frontend only for which Jekyll works like a charm). 

@pathawks we have built the Amplify Console for frontend developers so they can get up and running with their apps without too much manual configuration. Some of the features Amplify enables:
Continuous deployment with feature branch deploys
1-click custom domain setup with Route53
Easy configuration of redirects
Password protection with basic auth
Automatic trailing slash and Clean URLs
Serverless deployments with the Amplify CLI for dynamic content

**Comment by swaminator** [comment]
Thanks guys, what are next steps to merge this change?

**Comment by mattr-** [comment]
@jekyllbot: merge +docs

**Pull request merged**
