### PR TITLE
CI(Appveyor): shallow clone with 5 last commits

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by parkr** [comment]
@XhmikosR Can you explain what you're doing here? The only substantive change I see is `clone` moved from `10` to `5`.

**Comment by XhmikosR** [comment]
Yup, nothing else. The rest is a cosmetic change, since environments makes more sense to be first to me :)

**Comment by parkr** [comment]
Ok, works for me!

**Comment by DirtyF** [comment]
@jekyllbot: merge +dev

**Comment by tedmelvin25** [comment]
Hi

**Pull request merged**
