### PR TITLE
Add WOFF2 font format

### PR DESCRIPTION
**Pull request by nhoizey**

### CODE REVIEW

**Comment by parkr** [comment]
@azizshamim Is this in the GHP mime types file? We're trying to maintain parity.

**Comment by envygeeks** [comment]
I don't know how he would know that because he doesn't have access to their servers?

**Comment by alfredxing** [comment]
I created a test repo, and it seems that WOFF files are served as `application/x-font-woff` (as expected), but WOFF2 files are still being served as `application/octet-stream`, which probably means GitHub hasn't added this on their end yet.

**Comment by parkr** [comment]
> I don't know how he would know that because he doesn't have access to their servers?

@envygeeks Aziz works on GitHub's infrastructure. He knows. :)

@alfredxing Ok, then it's time for a support request! I'll send it now.

**Comment by parkr** [comment]
On hold at the moment. Got a response from GitHub, but the W3C spec doesn't specify this MIME Type (and is vague about which one to use).

**Comment by envygeeks** [comment]
The spec states `application/font-woff2` which will more than likely be what it will land as in the final spec.

**Comment by parkr** [comment]
@envygeeks Are you looking at http://dev.w3.org/webfonts/WOFF2/spec/#IMT ?

**Comment by envygeeks** [comment]
https://code.google.com/p/chromium/issues/detail?id=391289

**Comment by parkr** [comment]
I'm convinced! Thanks. :smile:

**Comment by nhoizey** [comment]
\o/

Thanks!

**Comment by envygeeks** [comment]
:heart:

**Comment by jdennes** [comment]
We've deployed the corresponding change on the GitHub side. GitHub Pages will now serve `.woff2` files with a `Content-Type` header value of `application/font-woff2`.

**Comment by parkr** [comment]
Thank you so much @jdennes!!!!!!!

**Pull request merged**
