### PR TITLE
Install Jekyll on Windows: Add Ruby to PATH 

### PR DESCRIPTION
**Pull request by anonymoustafa**
I experienced difficulties using fantastic jekyll cause, my windows os only could understand jekyll commands in bin folder of ruby installation folder. After searching internet I found that I have to add the executive files route on my hard drive to the system path.

### CODE REVIEW

**Comment by XhmikosR** [comment]
1. I don't use Ruby 2.5 but
2. If you have chosen to add Ruby to PATH it works just fine and this is not needed for sure.

**Comment by ashmaroli** [comment]
I agree with @XhmikosR here. Adding Ruby to the `PATH` is a part of installing Ruby, which is beyond the scope of Jekyll Documentation.

**Comment by kacperduras** [comment]
I'm with @XhmikosR and @ashmaroli.

**Comment by DirtyF** [comment]
@anonymoustafa Thanks for the note, even if it does not make it to our docs, this could be useful for people landing on this PR 👍

**Comment by oe** [comment]
@DirtyF I think we could at least add a small note? This is legitimately a thing that people stumble into while following the installation instructions from _our docs_.

**Pull request closed without merging**
