### PR TITLE
Proper markup for coffeescript requirements

### PR DESCRIPTION
**Pull request by txels**
Replaced `*` with `-`

### CODE REVIEW

**Comment by parkr** [comment]
Hey @txels, thanks for the contribution! We are using `*` to denote lists in Markdown in most of our other markdown files (if not all of them), so we're going to stick with that. Thanks, though!

**Comment by pathawks** [comment]
Using `*` is fine, but there is _something_ wrong with the way this list is rendered. Which is to say, it is **not** rendered as a list.

coffeescript

**Comment by pathawks** [comment]
The issue seems to be the space preceding the `*`

If that is removed, it will render as a list.

**Comment by parkr** [comment]
Excellent observation, @pathawks! Publishing now.

**Comment by pathawks** [comment]
Everything is looking good now :+1:

Your @vscobot intrigues me

coffeescript

**Comment by parkr** [comment]
> Your @vscobot intrigues me

Haha yeah, I ran something at [work](http://vsco.co) and it set my global git user!

**Pull request closed without merging**
