### PR TITLE
Fixing rubocop offenses in lib/jekyll/cleaner.rb

### PR DESCRIPTION
**Pull request by derekgottlieb**

### CODE REVIEW

**Comment by parkr** [comment]
Thank you so much! 😍 

@jekyllbot: merge +dev

**Comment by derekgottlieb** [comment]
If I cleaned up some more of these, would you prefer a PR per file or a PR for several of them?

**Comment by envygeeks** [comment]
A single PR with multiple and a commit for each file would be preferable for cleanliness.

**Comment by derekgottlieb** [comment]
Can do!

**Pull request merged**
