### PR TITLE
Dependencies: upgrade to toml 0.2.0

### LINKED ISSUE #6540: Update dependency constraint to allow for toml v0.2.0
Hey there! :wave:

I noticed that the constraint you have for toml doesn't allow for the latest version to be used.

The constraint I found was `~> 0.1.0`, and the latest version available is `0.2.0`.

Can you look into updating that constraint so our users can use the latest and greatest version? Thanks! :revolving_hearts:

### PR DESCRIPTION
**Pull request by jekyllbot**
Fix #6540

```text
Dependencies: upgrade to toml 0.2.0
```

### CODE REVIEW

**Comment by pup** [comment]
0.2.0 or 0.4.0? 😄

**Comment by DirtyF** [comment]
@pup Jekyllbot open an issue for 0.2.0 but I noticed afterwards that latest version was 0.4.0 😄

**Comment by DirtyF** [comment]
I should have trusted @jekyllbot: [latest gem is 0.2](https://rubygems.org/gems/toml)  but [latest release of TOML is 0.4](https://github.com/toml-lang/toml/releases)

**Comment by pup** [comment]
yeah, it seems to be a pre-release:

image

**Comment by DirtyF** [comment]
@jekyllbot : merge +dev

**Comment by robmuh** [comment]
Sorry if I missed it in the [docs](https://jekyllrb.com/docs/frontmatter/) but is this thread related to TOML support in Frontmatter? If so WAHOOO, uhuem, and I would love to update the docs. If I had my way I would make TOML supported in *everything* (after all it is a Tom invention, like Jekyll itself, and ironically is supported in Hugo and no Jekyll, right?)

**Comment by parkr** [comment]
> Sorry if I missed it in the docs but is this thread related to TOML support in Frontmatter? If so WAHOOO, uhuem, and I would love to update the docs. If I had my way I would make TOML supported in everything (after all it is a Tom invention, like Jekyll itself, and ironically is supported in Hugo and no Jekyll, right?)

Hey @robmuh! TOML is only supported for your configuration file, e.g. `_config.toml`. TOML has so-so support in Ruby (this gem, really, and I don't believe it's currently maintained), whereas it has excellent support in Go (the language Hugo is written in). That explains the difference in support. In an effort to not confuse folks, I'd be a proponent of just using 1 configuration spec here, and YAML is much better supported in Ruby.

**Comment by robmuh** [comment]
Have to say I completely agree with your conclusion. Just wanted to be sure I didn't miss something. I must confess after reading about [this Hugo embedded in AWS Lambda approach](http://bezdelev.com/post/hugo-aws-lambda-static-website/), which I am not sure is possible with Jekyll, that the scale tipped toward Hugo for me. Thanks for the info.

**Pull request merged**
