### PR TITLE
Add a cache for the includes.

### PR DESCRIPTION
**Pull request by parkr**
https://github.com/jekyll/jekyll/issues/3202

Doesn't seem to make anything faster.

### CODE REVIEW

**Comment by mattr-** [comment]
If it doesn't make anything faster, then we don't need it. :smiley:

**Comment by parkr** [comment]
It could just be that we are

**Comment by mattr-** [comment]
Our tests aren't good benchmarking tools and if you were only looking at those, then I wouldn't expect to see any difference. :smiley:

**Comment by gjtorikian** [comment]
I'm also not seeing a huge improvement from this branch over `master`. 

If it's not hurting anything, though, I'd still say merge it in. Maybe someone, somewhere needs it?

**Comment by parkr** [comment]
Not impressive, but there's an improvement:

```text
Calculating -------------------------------------
              cached       634 i/100ms
            uncached       543 i/100ms
-------------------------------------------------
              cached     6570.6 (±3.0%) i/s -      32968 in   5.022063s
            uncached     5613.0 (±2.1%) i/s -      28236 in   5.032667s
```

**Comment by parkr** [comment]
Just another thing we'd have to reset in a `--watch` cycle. For a marginal benefit, not much use. :/

**Pull request closed without merging**
