### PR TITLE
Allow colons in `uri_escape` filter

Fixes #5954

### LINKED ISSUE #5954: Jekyll breaks when using uri_escape on a string containing a colon after a space
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/

---

- [x] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [x] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [ ] I was trying to build.
- [ ] It was another bug.

## My Reproduction Steps

1. Insert this snippet anywhere in a Jekyll page (works in index.html)
  `{{ 'Foo : Bat' | uri_escape }}`
2. Receive error: *Liquid Exception: Invalid scheme format: Foo in index.html*

I've noticed that this is dependent on the colon following a space somewhere before it in the string. It doesn't have to be immediately before. For example:

`{{ 'Foo : Bat' | uri_escape }}` - Fail
`{{ 'Foo bar: Bat' | uri_escape }}` - Fail
`{{ 'Foo: Bat' | uri_escape }}` - Pass

## The Output I Wanted

The page should build successfully, and the string should be escaped.

### PR DESCRIPTION
**Pull request by jekyllbot**
PR automatically created for @pathawks.

```text
Allow colons in `uri_escape` filter

Fixes #5954
```

### CODE REVIEW

**Comment by pathawks** [comment]
Fixes #5954

**Comment by pathawks** [comment]
> LGTM. Let's backport this to 3.4 and cut a v3.4.3.

✅ #5968

Does anything special need to be done to merge these? How does `History.markdown` work with parallel branches?

**Comment by parkr** [comment]
@pathawks Thank you! In the future, you may use `script/backport-pr` to backport these changes. The steps I follow are:

1. Merge this PR with @jekyllbot like normal. All your work on `master` is now done.
2. Checkout the backport branch in #5968 and run all tests locally via `script/cibuild`. If tests pass, then merge the PR.
3. Checkout the `3.4-stable` branch. From here you will make the release. Do not commit any of the following manually, simply stage your changes.
4. Pull the changes to ensure you have the merged code, and run `script/cibuild` again, just to be absolutely sure.
5. Add an item to the `History.markdown` for this version & the backport PR (the syntax should be quite clear from previous releases), and bump the version in `lib/jekyll/version.rb`.
6. Run `bundle exec rake site:generate` to generate the necessary files in `docs/`.
7. Stage all changes to the History, the version file, and the docs folder but do not commit them.
8. Run `bundle exec rake release`.
9. Use `git log` to get the SHA-1 hash for the last commit with all your non-code changes. Checkout the `master` branch again, and cherry-pick that commit from the `3.4-stable` branch. Make sure to re-align the histories and resolve conflicts as needed. Push this change to master (it should just update the History.markdown, the version.rb file, and some files in docs/). Once this has been properly committed, you may need to run `bundle exec rake site:generate` in order to get the files right, but it should work without this (famous last words!).
10. Write a release post. If you run `bundle exec rake site:releases:new[3.4.3]` a properly-organized post will be created. I've had a bit of fun with the last 2 patch release posts, so feel free to write what you wish. It needn't be too long.
11. Propose the release post in another PR and ping me. & the documentation affinity team.

Then you're done. 🎉  If you don't mind, I would love for you to do this release. You have been granted permission to publish the jekyll gem on RubyGems.org. I'll be back online tomorrow, March 21, if you have any questions. Feel free to email me or ping me in the Jekyll Slack. Thank you! ✨

**Comment by ashmaroli** [comment]
> The steps I follow are:

:open_mouth: Whoa! looks like a lot of hassle to release a patch-update with backports. (More prone to human-errors). I was under the impression that this would've been automated with a shell script and JekyllBot.

**Comment by pathawks** [comment]
@parkr I'm on it. We should add these directions to https://jekyllrb.com/docs/maintaining/

**Comment by pathawks** [comment]
@jekyllbot: merge +bug

**Comment by pathawks** [comment]
@parkr I'm not authorized to push to `master` (protected branch), so you may have to be the one to `cherry-pick 610d46134688c33ebc73fdaa5bfbffe0a65d42ca` to `master`

**Comment by parkr** [comment]
Done! 🙌

> --
Parker

**Pull request merged**
