### PR TITLE
Add a workflow to build gems consistently

### PR DESCRIPTION
**Pull request by ashmaroli**
## Summary

Use GH Actions to **build** gem.
(Push to Rubygems.org manually)

With this Ruby version and platform remains consistent when triggered by different maintainers.

## Context

As part of responding to #8826 (which will be closed after `v4.2.2` is shipped and a release post is published).
This will be back ported to `4.2-stable` and `3.9-stable`.

### CODE REVIEW

**Comment by ashmaroli** [comment]
Since this workflow will not be triggered for the current context, you may view the run on my fork at https://github.com/ashmaroli/jekyll/actions/runs/1291299525 for analysis.

**Review by mattr- — COMMENTED** [review]
What do you think about evolving this action so that it can be used to release the gem? We could use the push of the tag to trigger this workflow instead of the commit message, and then set up the actions secrets to push the gem.

We might want to create a jekyllbot user on rubygems so that the authentication is not tied to our accounts as well.

I really like the idea of getting the process of making a release off our local machines. Thanks for getting this started.

**Comment by ashmaroli** [comment]
> What do you think about evolving this action so that it can be used to release the gem?

Our release process for backports is not straight-forward and involves switching branches multiple commits. Automating that is definitely beneficial but I didn't do that in the initial phase to have greater control n err on the safer side.


> We might want to create a jekyllbot user on rubygems so that the authentication is not tied to our accounts as well.

:+1:

**Comment by parkr** [comment]
I setup a jekyllbot RubyGems account. I'm all for automating this, especially if it were as simple as adding a Git tag. I have added a secret called `RUBYGEMS_GEM_PUSH_API_KEY` to the org for use in our gem repos. Right now jekyllbot doesn't have access to anything, but it'd be cool to validate with a gem that's less important (maybe like a Jekyll-import or something?). What do you think?

**Comment by ashmaroli** [comment]
> it'd be cool to validate with a gem that's less important (maybe like a Jekyll-import or something?)...

We could use https://github.com/jekyll/jekyll-test-gem-plugin for this purpose.
Since it is not consumer-oriented and is intuitively named, we could play around with it without being concerned of side-effects.

**Review by parkr — APPROVED** [review]
We can run this once we give jekyllbot the appropriate permissions for the gem.

**Comment by ashmaroli** [comment]
@jekyllbot: merge +dev

**Pull request merged**
