### PR TITLE
Release post for v3.8.0

### PR DESCRIPTION
**Pull request by ashmaroli**
- [x] Initial Draft

### CODE REVIEW

**Comment by ashmaroli** [comment]
> Please consider adding:

I agree @DirtyF but I deferred adding *all contributors of this release as usual,* and *a link to the full changelog* to the release post for `v3.8.0`

**Comment by oe** [comment]
@ashmaroli Would you want to modify this branch for the full 3.8.0 release, or do you want to make a new post on a new branch?

**Comment by ashmaroli** [comment]
I'll update this branch itself..

**Comment by ashmaroli** [comment]
@oe Renamed.. rewrote.. and rebased.. :smiley:

**Comment by oe** [comment]
@jekyllbot: merge +doc

**Pull request merged**
