### PR TITLE
return correct file in dir if dir has same name as file

### LINKED ISSUE #6475: If `bar.html` exists, then `jekyll s` will show `bar.html` for `bar/.*` unless something else explicitly (but not implicitly) overrides it
If a file and a folder have the same "permalink" name, `jekyll s` shows wrong content at files in the folder.

- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I ran `jekyll doctor` to check my configuration
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [x] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [x] I am on (or have tested on) ***Windows*** 10+

Windows Linux Subsystem, `bash` via Windows 10 Powershell

- [x] It was another bug.

## My Reproduction Steps

`jekyll s` does strange things when a file has the same name as a folder:

- Site is configured as `permalink: /:path`
- `bar.md`, should render at `/bar`
- `bar/baz.md`, should render at `/bar/baz`

Unfortunately:

On accessing `/bar/baz`:
- In 3.5.2 everything was okay.
- Since 3.6.0 it shows the content of `bar.md`

I think this is a serious bug. It probably is a regression of #6231, which tried to fix some related problems.

In `_site` everything is generated as it should:
- `/bar.html` with content from `bar.md`
- `/bar/baz.html` with content from `bar/baz.md`

So the problem is in the way `jekyll s` decides which file to serve.

### Example repo

Here is a repo that shows this exact scenario:
https://github.com/janpio/jekyll-path-test
Use the site navigation for the three example pages. 

If you use `jekyll s`, note how you see the wrong content for "Baz" (only 3.6.x).

(The project also includes 3 collections that test further iterations of this problem:, _test1 and _test2 with `.html` ending are fine, but _test3 has the exact same problem.)

## The Output I Wanted

You can see how everything should work at Github Pages:
https://janpio.github.io/jekyll-path-test/

### PR DESCRIPTION
**Pull request by Crunch09**
- bar.html
- bar
  |- baz.html

_GET /bar/_
_Before:_ Returns bar.html
_After:_  Returns bar.html

_GET /bar/baz_
_Before:_ Returns bar.html
_After:_  Returns bar/baz.html

_GET /bar/whatever_
_Before:_ Returns bar.html
_After:_  Returns 404

This fixes #6475. Thanks @janpio for the great reproduction script! 👍 

cc: @jekyll/build

### CODE REVIEW

**Comment by ashmaroli** [comment]
@Crunch09 Does this address #6222 as well (resolved via  #6231). I think you should test for that case as well, if this doesn't already..

**Comment by Crunch09** [comment]
@ashmaroli Yes, this is checked by [this](https://github.com/Crunch09/jekyll/blob/4a769ec5cb32db65aa90fb3c68c255fc6b23a50b/test/test_commands_serve_servlet.rb#L18-L23) test.

**Comment by parkr** [comment]
Have you verified this against GitHub Pages? Ideally we'd keep this server behaviour the same, especially around an edge case like this which is confusing to users.

**Comment by Crunch09** [comment]
@parkr Checked the current Github-Pages behavior with https://janpio.github.io/jekyll-path-test/ (provided by @janpio ). After this PR, webrick should have the same behavior.

**Comment by DirtyF** [comment]
@jekyllbot: merge +bug

**Pull request merged**
