### PR TITLE
Remove broken test

### PR DESCRIPTION
**Pull request by jekyllbot**
PR automatically created for @pathawks.

```text
Remove broken test
```

### CODE REVIEW

**Comment by pathawks** [comment]
For reasons I cannot diagnose, this test _sometimes_ fails. Whenever this happens on Travis, I just restart the build and everything is fine.

I am not sure what it was supposed to be testing, as it is _so_ similar to the very next test.

Test was added by @simensen _way_ back in #438, but has gone through a number of revisions in the interim.

You can see the test fail on `master` by running

```sh
ruby -S bundle exec rake TESTOPTS="--profile --seed=36323" test
```

Issue seems to be that _sometimes_ [`Jekyll::Configuration::DEFAULTS.source`](https://github.com/jekyll/jekyll/blob/master/lib/jekyll/configuration.rb#L9) is set to `test/source/` instead of `test/`. Nailing down why could be an interesting exercise but, like I say, this test seems to be redundant considering the very next test.

**Comment by quiltbag** [comment]
this test has been a pain in my back for a long time now, so i'm up for obliterating it

**Comment by simensen** [comment]
> I am not sure what it was supposed to be testing, as it is so similar to the very next test.
> – @pathawks 

The test was to ensure that plugins is *always an array*, even if no plugins were specified. In #438, I [attempted to ensure that the plugins attribute would always be an array](https://github.com/jekyll/jekyll/pull/438/files#diff-30570eaa19766a40dfa44810430d5e16R21). At the time, if one wanted to do something with the plugins attribute, it was hard to know what you were going to get back `nil`, an array, or a string. This was an attempt to normalize the plugin attribute to always be an array.

> ... this test seems to be redundant considering the very next test.

I don't know enough about current Jekyll development to know if this is true. It would seem to me that since this test fails *sometimes* that `site_configuration` is different than `default_configuration` and that in some cases the default configuration is not doing something sane. Neither appear to be defined in this file so yeah. *shrug*

> this test has been a pain in my back for a long time now, so i'm up for obliterating it
> – @quiltbag 

I'm sorry to hear that. :(

---

For my part, I'm not actively using Jekyll anymore and am only coming here now since I was looped in. :) If there are no people who rely on plugins being an array who also use the default configuration, then it probably makes sense to nuke this test since it appears to now be non-deterministic. As @pathawks said, "nailing down why could be an interesting exercise," but if nobody cares then it probably isn't worth the effort.

Happy new year. :)

**Comment by pathawks** [comment]
@simensen It appears that I have been careless with my words, and perhaps my meaning has been lost.

I did not at all mean to put you on blast. When the test fails, it is not because `plugins` is not an array, but because the path is slightly different from what is expected. This is the part that was causing me grief.

The test that follows did not exist when this test was added, and both have been through many revisions, so I was only trying to figure out if they were indeed redundant ot if I was missing something.

Again, @simensen, so sorry if it seemed I was calling you out.

**Comment by simensen** [comment]
@pathawks Never fear! I read none of this as a blast. :)

I was hoping to fill in some gaps for any additional reviewers in case it wasn't clear why I was testing the default case on its own and that I have no idea if the test matters anymore on account of the newly added `site_configuration` test. I also wanted to share that I'm not doing much with Jekyll these days so even though I was the person who added the test it won't bother me if it was removed. :)

I appreciate being looped in. I only wish I had more to offer. :)

**Comment by pathawks** [comment]
The mystery has been solved by @parkr in #5779 :tada:

**Pull request closed without merging**
