### PR TITLE
typofix - https://github.com/vlajos/misspell_fixer

### PR DESCRIPTION
**Pull request by vlajos**

### CODE REVIEW

**Comment by envygeeks** [comment]
Please remove the font-awesome and split out the two typo's into two different commits.  Thanks.

**Comment by envygeeks** [comment]
By remove font-awesome I mean remove your font-awesome, not remove font-awesome period.

**Comment by vlajos** [comment]
Done. Is it OK this way?

**Comment by envygeeks** [comment]
I'm fine with it as it stands but I'll digress my opinion on the commit msgs to @jekyll/core and @parkr

**Comment by vlajos** [comment]
I don't adhere to the URLs in the commit messages.
I can remove them if you think it is better that way.

**Comment by parkr** [comment]
@vlajos, yes, please remove the URLs in the commit messages and be a little more specific. Something like: `Fixed typo in regenerator test comment.` Then, :shipit:. Thanks!

**Comment by vlajos** [comment]
Done.

**Pull request merged**
