### PR TITLE
Use data file to render table at `/docs/configuration/options/#global-configuration`

### LINKED ISSUE #8373: Docs: Use data file(s) to render table(s) at https://jekyllrb.com/docs/configuration/options/
## Background

Currently there are three tables at https://jekyllrb.com/docs/configuration/options/ that are rendered by marking up in HTML directly. This hampers new additions to those tables.

Since the markup is consistent for a given table, we can improve the contributability / maintainability by using datafile(s) and iterating through them via Liquid.

For example:
```html
<tbody>
  {% for entry in site.data.config_options.global %}
    <tr class="setting">
      ...
    </tr>
  {% endfor %}
</tbody>
```

## Notes to contributors

Its best to submit a PR for the first table only. Once the data file structure and Liquid template gets approved, the remaining tables can be converted in separate pull request(s).

*For additional reference, there's a data file to render documentation on the Liquid filters provided by Jekyll.*

### PR DESCRIPTION
**Pull request by malathit**
This is a 🔦 documentation change.

## Summary

Currently there are three tables at https://jekyllrb.com/docs/configuration/options/ that are rendered by marking up in HTML directly. This hampers new additions to those tables.

Since the markup is consistent for a given table, we can improve the contributability / maintainability by using datafile(s) and iterating through them via Liquid.

For example:

```
<tbody>
  {% for entry in site.data.config_options.global %}
    <tr class="setting">
      ...
    </tr>
  {% endfor %}
</tbody>
```

## Context
`Partially resolves #8373`

### CODE REVIEW

**Review by DirtyF — APPROVED** [review]
Thank you, do you intend to do the same for the other tables?

**Review by ashmaroli — APPROVED** [review]
This looks good for the first pass..
On the next pass, you could keep the lines shorter (about 120 characters long) by using folded block scalars in YAML:
```yaml
description: >- 
  A very long line with many words
  that is folded onto the successive line.
```

**Comment by ashmaroli** [comment]
Thank you @malathit :smiley:
@jekyllbot: merge +doc

**Comment by malathit** [comment]
> Thank you, do you intend to do the same for the other tables?

Yes

**Pull request merged**
