### PR TITLE
Update windows.md

### PR DESCRIPTION
**Pull request by DavidBurela**
Added a very quick guide on getting Jekyll up and running on Windows in the fastest way possible with just a few command prompt commands.

### CODE REVIEW

**Comment by parkr** [comment]
Great!

**Comment by kaatt** [comment]
@DavidBurela Why is nodejs required?

**Comment by parkr** [comment]
> @DavidBurela I think nodejs isn't required anymore. I don't have it installed and jekyll works for me.

@kaatt That's correct, NodeJS is only required for Jekyll 2.x, which depends on the CoffeeScript gem, which requires NodeJS. :)

**Comment by DavidBurela** [comment]
That would make sense. I was following what documentation I could find for Windows which was for 2.x at the time and listed Node. Didn't realise it had been removed for 3.x. I'll update the instructions to bring it down to just 2 command prompt entries :grin:

**Pull request merged**
