### PR TITLE
Update Font Awesome to v4.4.0.

### PR DESCRIPTION
**Pull request by XhmikosR**
Mostly for .woff2 support.

### CODE REVIEW

**Comment by parkr** [comment]
:+1:

**Comment by envygeeks** [comment]
I'm hesitant on this one, double check the SHA's before merging the binary files.

**Comment by XhmikosR** [comment]
Come on, guys, I'm not new on this.

**Comment by parkr** [comment]
We could have a SHA check built-into the rake task if we wanted.

**Comment by envygeeks** [comment]
@XhmikosR it's not that we think you are new, it's that we have to provide our own integrity so we need to verify the validity of things like that before we update them (at least that's my 0.02c) I don't know if @jekyll/core agrees.

**Comment by XhmikosR** [comment]
You can verify it if you really want, but seriously, you are barking at the wrong tree here.

**Comment by XhmikosR** [comment]
Just check who updated it last time too.

**Comment by envygeeks** [comment]
I'm not asking you to verify, I will happily verify when I have time unless somebody else does it before me.  There is no need to be defensive, nobody is saying you are going to do anything but I am saying we need to verify that everything is in order because fonts are a vector too.

**Comment by alfredxing** [comment]
@envygeeks Just verified the SHA1 hashes, matches fonts downloaded from FontAwesome.

**Comment by envygeeks** [comment]
:shipit:

**Pull request merged**
