### PR TITLE
Rubocop cleanup for misc files

### PR DESCRIPTION
**Pull request by brint**
More cleanup for #4885 

lib/jekyll/hooks.rb
lib/jekyll/layout.rb
lib/jekyll/liquid_extensions.rb
lib/jekyll/liquid_renderer.rb
lib/jekyll/liquid_renderer/file.rb
lib/jekyll/log_adapter.rb
lib/jekyll/page.rb
lib/jekyll/plugin.rb
lib/jekyll/plugin_manager.rb
lib/jekyll/publisher.rb

### CODE REVIEW

**Comment by pathawks** [comment]
It would be helpful if you could group like files in a pull request, instead of just a misc PR.
I am seeing some duplicated effort here, but I don't want to discourage you from continuing this awesome work 🍻

**Comment by brint** [comment]
I had started to pull stuff out of my own branch since I saw your PR's coming in. I generally start at a random spot in `.rubocop.yml` and work up or down from there. I'll close this one out, normally there's not a lot of traffic on that issue, so I had taken that for granted 😄

**Comment by pathawks** [comment]
> I'll close this one out

I might cherry pick some of your commits 😛:+1:

**Comment by brint** [comment]
Go for it! I'll leave the branch up

**Comment by pathawks** [comment]
*Thank you* for doing each one in an individual, atomic commit. Made `cherry-pick`ing and resolving conflicts *so much* easier :+1:

#4946

**Pull request closed without merging**
