### PR TITLE
Organize Form Platforms-as-a-Service into unified list & add FormSpree.io

### PR DESCRIPTION
**Pull request by lexoyo**

### CODE REVIEW

**Comment by parkr** [comment]
@lexoyo Thanks for your contribution. I don't mind the consolidation of form backends as a service. I haven't heard of Formspree – are you affiliated with them?

**Comment by lexoyo** [comment]
> I haven't heard of Formspree – are you affiliated with them?

no but I use them since it is open source :)
plays nice with jekyll and [Silex](http://www.silex.me) (static website builder for designers) 
I'm from Silex though ;)

**Comment by lexoyo** [comment]
bump

**Comment by DirtyF** [comment]
@parkr FWIW I use Formspree for simple contact form on Jekyll sites and I'm satisfied with it.

**Comment by parkr** [comment]
Works for me.

@jekyllbot: merge +site

**Pull request merged**
