### PR TITLE
Add missing comma

### PR DESCRIPTION
**Pull request by stkent**

### CODE REVIEW

**Comment by ashmaroli** [comment]
Hello Stuart, I found another spot needing a comma:
- **installation.md** | _Line 18_ | ... above for Jekyll 2`,` and ...

**Comment by envygeeks** [comment]
This pull need be split into two pull requests please, you have to different changes going on.

**Comment by stkent** [comment]
@envygeeks reverted the second change in this PR; reopened that as https://github.com/jekyll/jekyll/pull/5232.

**Comment by envygeeks** [comment]
LGTM. @jekyllbot: merge +site

**Comment by envygeeks** [comment]
:heart:

**Pull request merged**
