### PR TITLE
test 'absolute_url' filter with 'xml_escape' filter

### PR DESCRIPTION
**Pull request by ashmaroli**
test  jekyll/jekyll-feed#158 upstream

### CODE REVIEW

**Comment by ashmaroli** [comment]
looks like the filter combo only fails within the context of `.xml` files
/cc @pathawks

**Comment by pathawks** [comment]
I too have been trying to create a failing test, and I too have been unsuccessful.

**Comment by ashmaroli** [comment]
its not *meant* to fail.. just checks if it'll fail with the filter-input combo

**Comment by pathawks** [comment]
We need to create a failing test so we can isolate the problem.

**Comment by pathawks** [comment]
There's a trailing slash _after_ the Liquid. I am banging my head against a wall right now.

https://github.com/jekyll/jekyll-feed/blob/v0.8.0/lib/feed.xml#L8

**Comment by ashmaroli** [comment]
The error is in this [line](https://github.com/jekyll/jekyll-feed/blob/master/lib/jekyll-feed/feed.xml#L10)
See the trailing `/` just before the closing tag?

**Pull request closed without merging**
