### PR TITLE
Proposed re-wording of Sass note. :)

### PR DESCRIPTION
**Pull request by jpasholk**
This is a 🔦 documentation change.

## Summary

If I am understanding this right, my re-wording helps me clearly visualize what's going on in plainer English.

### CODE REVIEW

**Comment by jpasholk** [comment]
@DirtyF Yeah man! 

I had to read that whole thing like 10 times to understand wtf was going on, lol. I hope my version is a bit clearer.

Also, dude that was fast!

Hope you have a wonderful Thanksgiving. :)

**Comment by DirtyF** [comment]
@jpasholk People have troubles understanding this the first time.

Any file in `_sass` directory is a normal `.scss` or `.sass` file and does not need empty front matter to be processed by Jekyll.

But any Sass file, for instance `/assets/css/styles.scss` directory, has to have the empty front matter to be processed by Jekyll. The corresponding CSS output will be then located in `_site/assets/css/style.css`. 

That is the file you want to point to in the head of your template:

`<link rel="stylesheet" href="{{ "/assets/css/styles.css" | relative_url }}">`

@jekyllbot: merge +docs

**Comment by jpasholk** [comment]
@DirtyF Yeah for sure. I think I'm understanding it enough to actually start using it now, rather than just vanilla CSS. This is such a nice feature of Jekyll, takes all of the work out of using Sass for the most part.

Anyway, thanks for the quick response on this man! 

Cheers!!

**Comment by DirtyF** [comment]
@jpasholk 🍻 for your first contribution, keep'em coming 🦃

**Pull request merged**
