### PR TITLE
Fix test script to be platform-independent

### PR DESCRIPTION
**Pull request by parkr**
Removes magic.

/cc @XhmikosR

### CODE REVIEW

**Comment by parkr** [comment]
Needed for #3115.

**Comment by XhmikosR** [comment]
Awesome! I'll cherry pick and try it now.

**Comment by XhmikosR** [comment]
https://ci.appveyor.com/project/jekyll/jekyll/build/40

**Comment by parkr** [comment]
I need this for local dev right now. Merging.

**Pull request merged**
