### PR TITLE
Include document path in kramdown warnings

### PR DESCRIPTION
**Pull request by ashmaroli**
Agreed its not the most elegant solution, but it gets the job done..
I'm staying away from `SmartyPants` in the first-pass.

### CODE REVIEW

**Comment by pathawks** [comment]
Regarding `smartify`: https://github.com/gettalong/kramdown/issues/473

**Comment by ashmaroli** [comment]
any word on the patch here? :smiley:

**Comment by pathawks** [comment]
I'm not a fan of the way this is done, but I'm not sure what the better way is.

I don't think the converter needs to know the document path. This feels like a leaky abstraction.

I wonder if Jekyll::Converter could have an array where warnings could be added, and then printed via renderer?

**Comment by ashmaroli** [comment]
> I wonder if Jekyll::Converter could have an array where warnings could be added, and then printed via renderer?

Ah! I like that idea..

**Comment by pathawks** [comment]
Maybe each `warning` could include a `message` and a `lineno`. This way, if we got ambitious, we could adjust the line number before it is printed to account for things like front-matter. That way, the line number that we print is the *actual* line number in the file, rather than the line number in the MarkDown block.

renderer could print each warning in a standard format, and do things like use a different color for the filename or whatnot, and each converter will never need to know or worry about those implementation details.

**Comment by ashmaroli** [comment]
That's a compound list of enhancements.. I like it but prefer to have the enhancement added bit-by-bit over time..

**Comment by pathawks** [comment]
What I am suggesting is that we build this with flexibility in mind, so we don’t trap ourselves in a corner.

**Comment by ashmaroli** [comment]
> What I am suggesting is that we build this with flexibility in mind

I got that.. I'm on board.. thinking of a way to implement this with minimal collaterals.. :thinking:

**Comment by pathawks** [comment]
We should keep thinking about this, but this PR in its current state is not the direction we want to go.

Closing for now.

**Comment by pathawks** [comment]
> Any news on this problem?

I don't believe so. Care to open a PR?

**Comment by Xeverous** [comment]
#7149

**Pull request closed without merging**
