### PR TITLE
Add post about Jekyll Admin initial release

### PR DESCRIPTION
**Pull request by mertkahyaoglu**
@jekyll/gsoc, anything you'd like to add ? 😄

### CODE REVIEW

**Comment by parkr** [comment]
This is AMAZING! LGTM! !!!

**Comment by parkr** [comment]
LGTM.

**Comment by envygeeks** [comment]
Is it ready yet? We've been unable to get it to boot on our Windows machines where it's more useful.

**Comment by benbalter** [comment]
> Is it ready yet? We've been unable to get it to boot on our Windows machines where it's more useful.

It should be. Have you tried `v0.1.0`? See https://github.com/jekyll/jekyll-admin/issues/175 and https://github.com/jekyll/jekyll-admin/pull/181 (regarding development on Windows, installation should be fine).

We've been testing on Windows and @codegaze (a Window user) has been helping us and submitting a handful of PRs (both Windows and not Windows related to improve and document the experience).

**Comment by benbalter** [comment]
LGTM (pending @envygeeks's question above). 

We may want to bump the date until tomorrow? (it's already the 25th in Turkey).

**Comment by envygeeks** [comment]
LGTM.

**Comment by envygeeks** [comment]
Thanks for answering @benbalter if you've got windows testers who can get it working then we do need to update and tell our Windows users to try again. It was about a month ago we first tried it.

**Comment by benbalter** [comment]
Lol @jekyllbot. 

LGTM.

**Comment by mertkahyaoglu** [comment]
@benbalter Not sure what timezone I should use.

**Comment by jaybe-jekyll** [comment]
Awesomeness. So excited about this! Nice!

**Comment by envygeeks** [comment]
LGTM.

**Comment by mertkahyaoglu** [comment]
I have no idea why those checks are failing.

**Comment by envygeeks** [comment]
We ignore Appveyor for now, and Travis sometimes have random failures I am personally (I don't know if anybody else has tried) to pin down and replicate locally on my own Linux machine.

**Comment by parkr** [comment]
> @benbalter Not sure what timezone I should use.

Up to you! Probably best to use your own timezone. 😄

**Comment by parkr** [comment]
@benbalter Those LGTM's are commit-focused so if you update the PR it is re-reviewed. The intention anyway. 😄

**Comment by envygeeks** [comment]
@parkr that is a pretty nice feature.

**Comment by ashmaroli** [comment]
> @benbalter if you've got windows testers who can get it working then we do need to update and tell our Windows users to try again.

@envygeeks, I have tried jekyll-admin locally (on Windows). It works as documented, if that was what you were enquiring..
@mertkahyaoglu and his mentors, Thank you so much for adding the UI interface. I :heart: it 

P.S. I'd be great if the Gemfile generated by `jekyll new` had this plugin on by default.

**Comment by codegaze** [comment]
@benbalter @envygeeks Yeap, gem installation and basic use are fine on Windows.
I also changed the  title to jekyll/jekyll-admin#175 "Windows local development installation bugs" to avoid any confusion with the gem installation.

**Comment by mertkahyaoglu** [comment]
Hopefully this will be the last commit and then we can finally publish it 😬  Sorry for requesting too many LGTMs.

**Comment by benbalter** [comment]
LGTM x3

**Comment by benbalter** [comment]
LGTM.

**Comment by parkr** [comment]
LGTM.

**Comment by benbalter** [comment]
@jekyllbot: merge +site

**Comment by parkr** [comment]
🎉 https://jekyllrb.com/news/2016/08/24/jekyll-admin-initial-release/

**Pull request merged**
