### PR TITLE
optional bundle command

### PR DESCRIPTION
**Pull request by annaprotasio**
`bundle` didn't work in my mac, the suggested alternative did.

### CODE REVIEW

**Comment by ashmaroli** [comment]
@annaprotasio Sorry, but looks like you've misunderstood the documentation.
`bundle` is a shorthand for **`bundle install`**. `bundle exec jekyll build` will only work after `bundle` or `bundle install` finishes running successfully.

If you wish to edit the doc, you may rephrase the paragraph to replace `bundle` with `bundle install`. Else I shall close this Pull Request.

**Comment by annaprotasio** [comment]
please close it - I couldn't make it work for me, even running bubble install.

**Comment by ashmaroli** [comment]
> even running bubble install

It is **`bundle install`**..
However, the question now is, what exactly was the error that led you to believe **`bundle`** or **`bundle install`** did not work..?

**Comment by annaprotasio** [comment]
Hi Ashwin,

After running all the commands, including `bundle install` which seems to have run ok at the end since it did not produced any error, when I ran `bundle exec jekyll serve` it just hangs, without any warning message to error message. 

***
$ bundle exec jekyll serve
Configuration file: none
            Source: /Users/ap6/Documents/GitHub/annaprotasio.github.io
       Destination: /Users/ap6/Documents/GitHub/annaprotasio.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
                    done in 0.022 seconds.
 Auto-regeneration: enabled for '/Users/ap6/Documents/GitHub/annaprotasio.github.io'
    Server address: http://127.0.0.1:4000
  Server running... press ctrl-c to stop.
***

if I go to the local http "http://127.0.0.1:4000", it doesn't find it and then the command line throws :

***
[2019-11-30 22:43:09] ERROR `/favicon.ico' not found.
***

the index.html was copied from the Jekill tutorial.

I installed Jekill using condo, as I don't have admin rights on my machine. Could this be the problem? 

Thank you for your help.

Anna

**Comment by ashmaroli** [comment]
@annaprotasio Your Jekyll installation is working fine.
Instead of trying to access `http://127.0.0.1:4000`, try accessing `http://localhost:4000`.

Since I can't see your `index.html` contents, I can't tell you if it is enough to render correctly. But since I know that your Jekyll installation is fine, here's what you can do to test it:
- Create a *new test site* at path `/Users/ap6/Documents/GitHub/test-site`. To do so, simply run the following commands:
  ```sh
  cd /Users/ap6/Documents/GitHub       # move into your GitHub directory from which ever
                                       # directory you currently are inside.

  jekyll new test-site                 # create Jekyll boilerplate.

  cd test-site                         # once the above step finishes, move into
                                       # the *test-site* directory 

  bundle exec jekyll serve --verbose   # Build and serve the test site.
  ```
- Once you see the `Server running... press ctrl-c to stop.`, **point your browser to `http://localhost:4000/`**

**Comment by annaprotasio** [comment]
Hello, 

`jekyll new test-site` failed to run properly. This is the output from the command:

`$ jekyll new test-site`

> Running bundle install in /Users/ap6/Documents/GitHub/test-site... 
>   Bundler: Fetching gem metadata from https://rubygems.org/...........
>   Bundler: Fetching gem metadata from https://rubygems.org/.
>   Bundler: Resolving dependencies...
>   Bundler: Using public_suffix 4.0.1
>   Bundler: Using addressable 2.7.0
>   Bundler: Using bundler 1.17.2
>   Bundler: Using colorator 1.1.0
>   Bundler: Using concurrent-ruby 1.1.5
>   Bundler: Using eventmachine 1.2.7
>   Bundler: Using http_parser.rb 0.6.0
>   Bundler: Using em-websocket 0.5.1
>   Bundler: Fetching ffi 1.11.3
>   Bundler: Installing ffi 1.11.3 with native extensions
>   Bundler: Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
>   Bundler: 
>   Bundler: current directory: /Users/ap6/Documents/bin/miniconda3/lib/ruby/gems/2.6.0/gems/ffi-1.11.3/ext/ffi_c
>   Bundler: /Users/ap6/Documents/bin/miniconda3/bin/ruby -I /Users/ap6/Documents/bin/miniconda3/lib/ruby/2.6.0 -r ./siteconf20191203-8308-1e8ji0u.rb extconf.rb
>   Bundler: checking for ffi.h... *** extconf.rb failed ***
>   Bundler: Could not create Makefile due to some reason, probably lack of necessary
>   Bundler: libraries and/or headers. Check the mkmf.log file for more details. You may
>   Bundler: need configuration options.
>   Bundler: 
>   Bundler: Provided configuration options:
>   Bundler: --with-opt-dir
>   Bundler: --without-opt-dir
>   Bundler: --with-opt-include
>   Bundler: --without-opt-include=${opt-dir}/include
>   Bundler: --with-opt-lib
>   Bundler: --without-opt-lib=${opt-dir}/lib
>   Bundler: --with-make-prog
>   Bundler: --without-make-prog
>   Bundler: --srcdir=.
>   Bundler: --curdir
>   Bundler: --ruby=/Users/ap6/Documents/bin/miniconda3/bin/$(RUBY_BASE_NAME)
>   Bundler: --with-ffi_c-dir
>   Bundler: --without-ffi_c-dir
>   Bundler: --with-ffi_c-include
>   Bundler: --without-ffi_c-include=${ffi_c-dir}/include
>   Bundler: --with-ffi_c-lib
>   Bundler: --without-ffi_c-lib=${ffi_c-dir}/lib
>   Bundler: --enable-system-libffi
>   Bundler: --disable-system-libffi
>   Bundler: --with-libffi-config
>   Bundler: --without-libffi-config
>   Bundler: --with-pkg-config
>   Bundler: --without-pkg-config
>   Bundler: /Users/ap6/Documents/bin/miniconda3/lib/ruby/2.6.0/mkmf.rb:467:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
>   Bundler: You have to install development tools first.
>   Bundler: from /Users/ap6/Documents/bin/miniconda3/lib/ruby/2.6.0/mkmf.rb:601:in `try_cpp'
>   Bundler: from /Users/ap6/Documents/bin/miniconda3/lib/ruby/2.6.0/mkmf.rb:1109:in `block in have_header'
>   Bundler: from /Users/ap6/Documents/bin/miniconda3/lib/ruby/2.6.0/mkmf.rb:959:in `block in checking_for'
>   Bundler: from /Users/ap6/Documents/bin/miniconda3/lib/ruby/2.6.0/mkmf.rb:361:in `block (2 levels) in postpone'
>   Bundler: from /Users/ap6/Documents/bin/miniconda3/lib/ruby/2.6.0/mkmf.rb:331:in `open'
>   Bundler: from /Users/ap6/Documents/bin/miniconda3/lib/ruby/2.6.0/mkmf.rb:361:in `block in postpone'
>   Bundler: from /Users/ap6/Documents/bin/miniconda3/lib/ruby/2.6.0/mkmf.rb:331:in `open'
>   Bundler: from /Users/ap6/Documents/bin/miniconda3/lib/ruby/2.6.0/mkmf.rb:357:in `postpone'
>   Bundler: from /Users/ap6/Documents/bin/miniconda3/lib/ruby/2.6.0/mkmf.rb:958:in `checking_for'
>   Bundler: from /Users/ap6/Documents/bin/miniconda3/lib/ruby/2.6.0/mkmf.rb:1108:in `have_header'
>   Bundler: from extconf.rb:10:in `system_libffi_usable?'
>   Bundler: from extconf.rb:34:in `<main>'
>   Bundler: 
>   Bundler: To see why this extension failed to compile, please check the mkmf.log which can be found here:
>   Bundler: 
>   Bundler: /Users/ap6/Documents/bin/miniconda3/lib/ruby/gems/2.6.0/extensions/x86_64-darwin-17/2.6.0/ffi-1.11.3/mkmf.log
>   Bundler: 
>   Bundler: extconf failed, exit code 1
>   Bundler: 
>   Bundler: Gem files will remain installed in /Users/ap6/Documents/bin/miniconda3/lib/ruby/gems/2.6.0/gems/ffi-1.11.3 for inspection.
>   Bundler: Results logged to /Users/ap6/Documents/bin/miniconda3/lib/ruby/gems/2.6.0/extensions/x86_64-darwin-17/2.6.0/ffi-1.11.3/gem_make.out
>   Bundler: 
>   Bundler: An error occurred while installing ffi (1.11.3), and Bundler cannot continue.
>   Bundler: Make sure that `gem install ffi -v '1.11.3' --source 'https://rubygems.org/'` succeeds before bundling.
>   Bundler: 
>   Bundler: In Gemfile:
>   Bundler: minima was resolved to 2.5.1, which depends on
>   Bundler: jekyll-feed was resolved to 0.13.0, which depends on
>   Bundler: jekyll was resolved to 4.0.0, which depends on
>   Bundler: jekyll-sass-converter was resolved to 2.0.1, which depends on
>   Bundler: sassc was resolved to 2.2.1, which depends on
>   Bundler: ffi

I also tried to run `gem install ffi -v '1.11.3' --source 'https://rubygems.org/'`, but got:

> ERROR:  Error installing ffi:
> 	ERROR: Failed to build gem native extension.
> 
>     current directory: /Users/ap6/Documents/bin/miniconda3/lib/ruby/gems/2.6.0/gems/ffi-1.11.3/ext/ffi_c
> /Users/ap6/Documents/bin/miniconda3/bin/ruby -I /Users/ap6/Documents/bin/miniconda3/lib/ruby/2.6.0 -r ./siteconf20191203-12088-74s9q2.rb extconf.rb
> checking for ffi.h... *** extconf.rb failed ***
> Could not create Makefile due to some reason, probably lack of necessary
> libraries and/or headers.  Check the mkmf.log file for more details.  You may
> need configuration options.
> 
> Provided configuration options:
> 	--with-opt-dir
> 	--without-opt-dir
> 	--with-opt-include
> 	--without-opt-include=${opt-dir}/include
> 	--with-opt-lib
> 	--without-opt-lib=${opt-dir}/lib
> 	--with-make-prog
> 	--without-make-prog
> 	--srcdir=.
> 	--curdir
> 	--ruby=/Users/ap6/Documents/bin/miniconda3/bin/$(RUBY_BASE_NAME)
> 	--with-ffi_c-dir
> 	--without-ffi_c-dir
> 	--with-ffi_c-include
> 	--without-ffi_c-include=${ffi_c-dir}/include
> 	--with-ffi_c-lib
> 	--without-ffi_c-lib=${ffi_c-dir}/lib
> 	--enable-system-libffi
> 	--disable-system-libffi
> 	--with-libffi-config
> 	--without-libffi-config
> 	--with-pkg-config
> 	--without-pkg-config
> /Users/ap6/Documents/bin/miniconda3/lib/ruby/2.6.0/mkmf.rb:467:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
> You have to install development tools first.
> 	from /Users/ap6/Documents/bin/miniconda3/lib/ruby/2.6.0/mkmf.rb:601:in `try_cpp'
> 	from /Users/ap6/Documents/bin/miniconda3/lib/ruby/2.6.0/mkmf.rb:1109:in `block in have_header'
> 	from /Users/ap6/Documents/bin/miniconda3/lib/ruby/2.6.0/mkmf.rb:959:in `block in checking_for'
> 	from /Users/ap6/Documents/bin/miniconda3/lib/ruby/2.6.0/mkmf.rb:361:in `block (2 levels) in postpone'
> 	from /Users/ap6/Documents/bin/miniconda3/lib/ruby/2.6.0/mkmf.rb:331:in `open'
> 	from /Users/ap6/Documents/bin/miniconda3/lib/ruby/2.6.0/mkmf.rb:361:in `block in postpone'
> 	from /Users/ap6/Documents/bin/miniconda3/lib/ruby/2.6.0/mkmf.rb:331:in `open'
> 	from /Users/ap6/Documents/bin/miniconda3/lib/ruby/2.6.0/mkmf.rb:357:in `postpone'
> 	from /Users/ap6/Documents/bin/miniconda3/lib/ruby/2.6.0/mkmf.rb:958:in `checking_for'
> 	from /Users/ap6/Documents/bin/miniconda3/lib/ruby/2.6.0/mkmf.rb:1108:in `have_header'
> 	from extconf.rb:10:in `system_libffi_usable?'
> 	from extconf.rb:34:in `<main>'
> 
> To see why this extension failed to compile, please check the mkmf.log which can be found here:
> 
>   /Users/ap6/Documents/bin/miniconda3/lib/ruby/gems/2.6.0/extensions/x86_64-darwin-17/2.6.0/ffi-1.11.3/mkmf.log
> 
> extconf failed, exit code 1
> 
> Gem files will remain installed in /Users/ap6/Documents/bin/miniconda3/lib/ruby/gems/2.6.0/gems/ffi-1.11.3 for inspection.
> Results logged to /Users/ap6/Documents/bin/miniconda3/lib/ruby/gems/2.6.0/extensions/x86_64-darwin-17/2.6.0/ffi-1.11.3/gem_make.out
> -bash: Building: command not found

And:

`$ cat /Users/ap6/Documents/bin/miniconda3/lib/ruby/gems/2.6.0/extensions/x86_64-darwin-17/2.6.0/ffi-1.11.3/mkmf.log`
> "pkg-config --exists libffi"
> package configuration for libffi is not found
> "x86_64-apple-darwin13.4.0-clang -o conftest -I/Users/ap6/Documents/bin/miniconda3/include/ruby-2.6.0/x86_64-darwin17 -I/Users/ap6/Documents/bin/miniconda3/include/ruby-2.6.0/ruby/backward -I/Users/ap6/Documents/bin/miniconda3/include/ruby-2.6.0 -I. -D_FORTIFY_SOURCE=2 -mmacosx-version-min=10.9 -I/Users/ap6/Documents/bin/miniconda3 -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -I/Users/ap6/Documents/bin/miniconda3/include -fdebug-prefix-map=/usr/local/miniconda/conda-bld/ruby_1570379348315/work=/usr/local/src/conda/ruby-2.6.5 -fdebug-prefix-map=/Users/ap6/Documents/bin/miniconda3=/usr/local/src/conda-prefix -fno-common conftest.c  -L. -L/Users/ap6/Documents/bin/miniconda3/lib -L. -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,/Users/ap6/Documents/bin/miniconda3/lib -L/Users/ap6/Documents/bin/miniconda3/lib -fstack-protector-strong -L/usr/local/miniconda/conda-bld/ruby_1570379348315/_build_env/lib/clang/4.0.1/lib     -lruby.2.6   "
> checked program was:
> /* begin */
> 1: #include "ruby.h"
> 2: 
> 3: int main(int argc, char **argv)
> 4: {
> 5:   return 0;
> 6: }
> /* end */
> 
>

**Comment by ashmaroli** [comment]
You need to have command-line tools installed to compile native extensions.
I had hoped that you had previously followed the documentation at:
https://jekyllrb.com/docs/installation/macos/

**Comment by annaprotasio** [comment]
I think I have everything in place:

`$ ruby -v`

> ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin17]
> (my-jekyll) mib107371i:GitHub ap6$ gem -v
> 3.0.3
> 

`$ gcc -v`

> Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
> Apple LLVM version 10.0.0 (clang-1000.10.44.4)
> Target: x86_64-apple-darwin17.7.0
> Thread model: posix
> InstalledDir: /Library/Developer/CommandLineTools/usr/bin

`$ g++ -v`

> Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
> Apple LLVM version 10.0.0 (clang-1000.10.44.4)
> Target: x86_64-apple-darwin17.7.0
> Thread model: posix
> InstalledDir: /Library/Developer/CommandLineTools/usr/bin

`$ make -v`

> GNU Make 3.81
> Copyright (C) 2006  Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.
> There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
> PARTICULAR PURPOSE.
> 
> This program built for i386-apple-darwin11.3.0

One problem could be that I couldn't install Jekyll using gem:

> $ gem install jekyll bundler
> ERROR:  While executing gem ... (Gem::FilePermissionError)
>     You don't have write permissions for the /Library/Ruby/Gems/2.3.0 directory.

So I installed it using conda:

`conda create -n my-jekyll -c conda-forge rb-jekyll `

Could this be the problem?

**Pull request closed without merging**
