### PR TITLE
Handle liquid tags in excerpts robustly

### PR DESCRIPTION
**Pull request by ashmaroli**
Resolves: https://github.com/jekyll/jekyll/pull/6724#issuecomment-377794855

/cc @DirtyF

### CODE REVIEW

**Comment by pathawks** [comment]
@jekyllbot: :shipit: +minor

**Comment by ashmaroli** [comment]
um.. this was a `fix` though..

**Comment by pathawks** [comment]
Sure was. My mistake.

**Comment by nebulousdog** [comment]
I can confirm this issue with octopress img tags (`{% img ...}`).

**Pull request merged**
