### PR TITLE
Subdirectories of _posts are no longer categories

### PR DESCRIPTION
**Pull request by anthonyjsmith**
See  #4084

### CODE REVIEW

**Comment by anthonyjsmith** [comment]
Here's [the thread on Jekyll Talk which led to this](https://talk.jekyllrb.com/t/upgraded-to-3-0-3-and-all-my-posts-disappeared/2061/8).

**Comment by mattr-** [comment]
Thanks for this update to the documentation!

@jekyllbot merge +site

**Comment by mattr-** [comment]
@jekyllbot merge +site

**Comment by anthonyjsmith** [comment]
That was easy! :+1:

**Comment by parkr** [comment]
:heart:

**Pull request merged**
