### PR TITLE
Factor out a `read_data_file` call to keep things clean

### PR DESCRIPTION
**Pull request by gjtorikian**
I actually need this for a monkey-patch I am planning. :wink: But it does look cleaner, no?

/cc @parkr

### CODE REVIEW

**Comment by parkr** [comment]
Looks good to me, but it needs a test. :smile:

**Comment by gjtorikian** [comment]
Hrm, I would think the fact that nothing broke would be a succeeding test? :wink: Ok, ok...

**Comment by alfredxing** [comment]
:+1: Would also be great if we could allow custom data formats in the future in the form of plugins.

**Comment by parkr** [comment]
> Would also be great if we could allow custom data formats in the future in the form of plugins.

We could also start using converters...

**Pull request merged**
