### PR TITLE
Reorganize and cleanup the Gemfile, shorten required depends.

### PR DESCRIPTION
**Pull request by jekyllbot**
PR automatically created for @envygeeks.

```text
Reorganize and cleanup the Gemfile, shorten required depends.
```

### CODE REVIEW

**Comment by parkr** [comment]
@envygeeks :shipit: once minutest tests are fixed!

**Comment by envygeeks** [comment]
@parkr this didn't break those tests: dab53a697b8f58db9bef819dc9b6f5c3a592fe56 did.

**Comment by envygeeks** [comment]
I was actually in the middle of trying to figure out how dab53a697b8f58db9bef819dc9b6f5c3a592fe56 broke them when you posted that comment, because it intrigued me how that broke something so far from where the change was.

**Comment by parkr** [comment]
@jekyllbot: merge +development

**Pull request merged**
