### PR TITLE
Add includes link to doc nav

### PR DESCRIPTION
**Pull request by tomjohnson1492**
I created more advanced details about includes and created a new page for it instead of putting all the info on the templates page.

See https://github.com/jekyll/jekyll/pull/5630 for more details on the update. 

@jekyll/documentation

### CODE REVIEW

**Comment by DirtyF** [comment]
Includes were mentioned in templates, so this section should be right after the templates in the navigation if you ask me.

**Comment by tomjohnson1492** [comment]
I made the requested update here. Ready for re-review.

**Comment by parkr** [comment]
This depends on #5696. I'm confused as to why this is in its own pull request when it's no good on its own?

**Comment by tomjohnson1492** [comment]
My fault. I split this up into too many PRs. Next time I will combine the related ones like this.

**Comment by pathawks** [comment]
Looks like this has been merged into #5696 (Thanks @DirtyF :beers:)

**Pull request closed without merging**
