### PR TITLE
Allow plugins to modify the obsolete files.

### PR DESCRIPTION
**Pull request by envygeeks**

### CODE REVIEW

**Comment by DirtyF** [comment]
What is the use case here?

**Comment by envygeeks** [comment]
@DirtyF https://github.com/jekyll/jekyll-assets/blob/master/lib/jekyll/assets/patches/obsolete_files.rb should be unnecessary, people shouldn't have to hack Jekyll to prevent clobbering if their files at-large.

**Comment by DirtyF** [comment]
@envygeeks got you 👌

**Comment by DirtyF** [comment]
@jekyllbot: merge +minor

**Comment by DirtyF** [comment]
Thanks @envygeeks. 👍

**Comment by parkr** [comment]
This should be documented on the plugins page.

**Pull request merged**
