### PR TITLE
Fix diff syntax-highlighting

### PR DESCRIPTION
**Pull request by ashmaroli**
Since this is subjective, its going to take some inputs from multiple perspective..

Current:
image

### PR Initial Commit:
diff-syntax

### CODE REVIEW

**Comment by DirtyF** [comment]
@jekyllbot: merge +docs

**Comment by DirtyF** [comment]
We should have kept the bold here but it's already more readable, that's what matters the most. Thanks.

**Comment by ashmaroli** [comment]
Bold + text-shadow seemed a li'l too much to me..

**Comment by ashmaroli** [comment]
@DirtyF see the extra borders around the `code` blocks in the pics above..? I'm guessing it has something to do with the change in Rouge versions.. (GitHub Pages is still on the older version..)
Is that worth addressing..?

**Comment by DirtyF** [comment]
Yeah it's clearly a visual regression there's an extra `div` with `highlight` class that wasn't here before. We should remove it.

**Comment by ashmaroli** [comment]
handled in #6389 ...

**Pull request merged**
