### PR TITLE
Add a template for pull requests

### PR DESCRIPTION
**Pull request by chrisfinazzo**
Complement to #4535.

/cc @jekyll/core

### CODE REVIEW

**Comment by chrisfinazzo** [comment]
Hello? @travis-ci is anyone home?

**Comment by parkr** [comment]
The issue one I did that way because the answers were usually a bit longer. I think if we add a PR one, it could be a bit simpler: headers for block answers, simple `**Bold statement:** answer` fill-in-the-blanks for simple answers.

**Comment by parkr** [comment]
Thanks for the PR, @chrisfinazzo. I don't think I'm going to take it quite yet as I'm not sure how I'd like to organize pull requests. The issue template was an easy one to make sure users were submitting all the right information so we could figure out the issue, but pull requests vary greatly between documentation updates, bug fixes, and feature submissions. We'll let it be for now and revisiti it at some later date.

Thanks!

**Comment by chrisfinazzo** [comment]
No worries. Been busy with some other things lately so I hadn't really given it a great deal of thought either. I'll keep this locally so it's easy to start up again.

**Pull request closed without merging**
