### PR TITLE
Warn on command-line with permalink conflict

### LINKED ISSUE #6207: Warn/error on command-line with permalink conflict
- [X] I believe this to be a bug, not a question about using Jekyll.
- [X] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [X] I ran `jekyll doctor` to check my configuration
- [X] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [X] This is a feature request.

---

- [X] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [ ] I was trying to build.
- [X] It was another bug.

## My Reproduction Steps

1. Create a site with two pages, call them `a.html` and `b.html` (or `.md`, doesn't matter), but with different content.
2. Give both of the pages the same `permalink:` attribute in the front matter
3. build
4. See that sometimes one wins, sometimes the other

In a large site (or even a small one), this can easily lead to lots of debugging work with no understanding why.

## The Output I Wanted

Have Jekyll report on the build command-line if there are conflicts between permalinks. At minimum it should be a warning, although my personal view is that it is an error.

/cc @jekyll/build

### PR DESCRIPTION
**Pull request by SeekingMeaning**
This is a 🙋 feature or enhancement.

## Summary

This prints a warning for permalink conflict when running `jekyll serve`

Example output:

```
Configuration file: ~/permalink-conflict-test/_config.yml
            Source: ~/permalink-conflict-test
       Destination: ~/permalink-conflict-test/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
       Jekyll Feed: Generating feed for posts
          Conflict: The URL '~/permalink-conflict-test/_site/z.html' is the destination for the following pages: b.markdown, c.markdown
                    done in 0.324 seconds.
 Auto-regeneration: enabled for '~/permalink-conflict-test'
    Server address: http://127.0.0.1:4000/
  Server running... press ctrl-c to stop.
```

## Context

Closes #6207

### CODE REVIEW

**Comment by ashmaroli** [comment]
@SeekingMeaning Thank you for submitting this pull request.
I'd like some changes to be made, however:
- The `Jekyll::Commands::Doctor.conflicting_urls` is already a public class method. Why not call it directly from within the class `Site` instead of moving it into a new utility module?
  ```ruby
  # lib/jekyll/site.rb

  def process
    ...
    Jekyll::Commands::Doctor.conflicting_urls(self)
  end
  ```
  The benefits being:
  - use of existing implementation &mdash; no need for additional tests.
  - doesn't break semver principle by the `Doctor` command class not being able to call the method directly from outside the class.
- Secondly, how about issuing the warning as part of the `Jekyll::Site#write` method call instead of after writing all files?

**Comment by ashmaroli** [comment]
Thanks for the changes.

> ..as part of the `Jekyll::Site#write` method call instead of after writing all files?

This has still not been resolved, though. The focus being *instead of after writing all files*.
I recommend that the warning be issued before the call to block attached to `each_site_file`.

**Comment by ashmaroli** [comment]
@SeekingMeaning If you're interested, you can try and add a Cucumber based test to take this up to :100: 
However, its totally your call and as far as I'm concerned, the current diff is sufficient for a merge.
Thank you for your contribution.

**Comment by SeekingMeaning** [comment]
Hmm where would be a good place to add the test?

**Comment by ashmaroli** [comment]
> where would be a good place to add the test?

[`features/permalinks.feature`](https://github.com/jekyll/jekyll/blob/9a7955d9b3e85a78fa4876ccd98708fb2f762472/features/permalinks.feature#L1)

**Comment by DirtyF** [comment]
@jekyll:  merge +minor

**Comment by DirtyF** [comment]
@jekyllbot:  merge +minor

**Comment by ashmaroli** [comment]
@jekyllbot: merge +minor

**Comment by SeekingMeaning** [comment]
Could I submit a claim for the $5 on IssueHunt? (if it's not too much ask)

**Comment by ashmaroli** [comment]
> Could I submit a claim for the $5 on IssueHunt?

/cc @DirtyF

**Pull request merged**
