### PR TITLE
Update list of files excluded from Docs site

### PR DESCRIPTION
**Pull request by sebam2k4**
added exclusions

### CODE REVIEW

**Comment by sebam2k4** [comment]
Can you please review my pull request :)

**Comment by ashmaroli** [comment]
Welcome to the organisation @sebam2k4 :smiley: 
@DirtyF  or any other maintainer will shortly merge this PR.

Resolves #6438

**Comment by pathawks** [comment]
This is `+site` rather than `+docs` right @jekyll/documentation?

**Comment by parkr** [comment]
@pathawks +site originally meant jekyllrb.com changes. Recently folks have started using +docs instead. I’d use +site for this, yeah.

**Comment by pathawks** [comment]
@jekyllbot: merge +site

**Comment by pathawks** [comment]
Thanks so much @sebam2k4! :beers::tada:

**Comment by sebam2k4** [comment]
Thank you!

**Pull request merged**
