### PR TITLE
Site template: Move contents of the index.html page to the 'home' layout

### PR DESCRIPTION
**Pull request by DirtyF**
Reflects changes in https://github.com/jekyll/minima/pull/48

/cc @jekyll/core

### CODE REVIEW

**Comment by ashmaroli** [comment]
@DirtyF, few questions:
- what do you say to adding a comment  telling users they *need not* edit the empty `index.html` they now see..?
- is using index.md instead of `index.html` a bad-idea? 
If done so, we could add a `title: Home; permalink: /` and minima will automatically add this page to the top-nav

**Comment by DirtyF** [comment]
@ashmaroli good catch, applied your recommendations, except for title and permalink as It seems perfectly fine to me as it is.

**Comment by ashmaroli** [comment]
> except for title and permalink as it seems perfectly fine to me as it is.

Thanks Frank, but according to [this](https://github.com/jekyll/minima/blob/master/_includes/header.html#L20-L22), unless those parameters are set, the top-nav wont have the link defined. 
I wont press on including them though, as this [line](https://github.com/jekyll/minima/blob/master/_includes/header.html#L7) already links to the blog's root.

**Comment by parkr** [comment]
@jekyllbot: merge +minor

**Pull request merged**
