### PR TITLE
Date filters should never raise an exception

### PR DESCRIPTION
**Pull request by jekyllbot**
PR automatically created for @pathawks.

```text
Failing test: date filter should allow empty input to pass through
```

### CODE REVIEW

**Comment by pathawks** [comment]
Fixes #5680

**Comment by parkr** [comment]
:+1: for being consistent with Liquid.

**Comment by pathawks** [comment]
This looks ready to merge...?

**Comment by DirtyF** [comment]
At your service @pathawks 

@jekyllbot: merge +minor

📅

**Pull request merged**
