### PR TITLE
Allow excerpts to be generated for Page objects

### LINKED ISSUE #6778: Allow Jekyll::Page objects to render {{ page.excerpt }} with relevant content
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [x] This is a feature request.

---

- [x] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux

---

## My Reproduction Steps

I'm trying to get  `{{ page.excerpt }}` from my layout file. This seem to only work for documents (including posts), but not for pages.

I created a repository that reproduce the issue: https://github.com/pixelastic/jekyll-excerpt

I basically created a new site using `jekyll new my_site`. 

Then I created a new layout, `_layouts/test_layout.html` with the following content:
```
---
layout: default
---

<dl>
  <dt>Excerpt:</dt>
  <dd>{{ page.excerpt }}</dd>
</dl>
```

I updated both `about.md` and the post example to use this layout. Only the post actually display the excerpt.

## The Output I Wanted

I expected to be able to get access to an excerpt for pages, as I can do for posts.

## Miscellaneous

_Note that this is a simplified test case. My actual use-case is from inside a plugin, where I'd like to get access to the excerpt of a `Jekyll::Page` instance. When I have a `Jekyll::Document` instance, I can call `.data['excerpt]` on it, but there is no such key for a page._

### PR DESCRIPTION
**Pull request by ashmaroli**
- This is a 🙋 feature or enhancement. 

## Summary

Allow excerpts to be generated for `Jekyll::Page` objects.

*Currently just a bare-bones feature, `{{ page.excerpt }}` for a `Jekyll::Page` will yield just the rendered output string of the Page's excerpt-source.*

## Context

Resolves #6778

### CODE REVIEW

**Comment by ashmaroli** [comment]
Unfortunately since this breaks existing builds, it is not ready to move out of the *draft* status.

**Comment by ashmaroli** [comment]
@jekyllbot: merge +minor

**Comment by seth-reeser** [comment]
Hello, this had an unintended consequence, I would recommend stripping html, stripping newlines, and even maybe truncating. I was using page.excerpt as a meta description entry:

`<meta name="description" content="{% if page.excerpt %}{{ page.excerpt | strip_html | strip_newlines | truncate: 160 }}{% else %}{{ site.description }}{% endif %}">`

In an example of an `excerpt` not being defined for a page, this would have evaluated to the `site.description`, but now I'm getting markup generated for me that breaks because of HTML being included.

**Comment by ashmaroli** [comment]
@seth-reeser Please open a new issue ticket and include the expected and actual results in the ticket for a discussion.

**Pull request merged**
