### PR TITLE
Convertible#validate_permalink!: ensure the return value of data["permalink"] is a string before asking if it is empty

### LINKED ISSUE #5804: Jekyll fails to build sites with `permalink`s that contain only digits
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [ ] This is a feature request.

---

- [ ] I am on (or have tested on) ***macOS*** 10+
- [x] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [x] I had an error on GitHub Pages and I did not test it locally.
- [ ] I was trying to build.
- [ ] It was another bug.

## My Reproduction Steps

Created this repository and made this commit: https://github.com/AJMansfield/jekyll-test/commit/7cbbc83a73ff5d0e424123548a0eea4b9b8370e2

The site builds fine before the commit, and fails to build afterwards.

This may be related to #5603.

## The Output I Wanted

The actual repository I discovered this issue in is https://github.com/AJMansfield/scp-rec.

I want to be able to navigate to `ajmansfield.github.io/scp-rec/728` and be able to view the content described by `728.md`. It is unfortunately not possible for me to just put that content at some other URL because of how this site has to inter-operate with another site.

/cc include any Jekyll affinity teams here (see https://teams.jekyllrb.com/ for more info)

### PR DESCRIPTION
**Pull request by parkr**
Fixes #5804.

### CODE REVIEW

**Comment by pathawks** [comment]
What happens if it is not a string?

**Comment by parkr** [comment]
> What happens if it is not a string?
>

If it's not string, we get a NoMethodError. The issue I linked to above
shows the stacktrace.

> --
Parker

**Comment by pnn** [comment]
@jekyllbot: merge +bug

**Pull request merged**
