### PR TITLE
Be more specific on what to upload

### LINKED ISSUE #6118: Mistake in the Jekyll documentation
I think there is a mistake in the document of Jekyll in the [Deployment method](http://jekyllrb.com/docs/deployment-methods/).

In the documentation, it was showing that you need to upload the _site name folder to the FTP server. But when I tried this. It didn't work. To open the website I type the name of the folder to open the website.

For example: 
`localhost:4000/_site`

When I uploaded the files inside the folder, then it work.
(Sorry, if I am wrong).

### PR DESCRIPTION
**Pull request by DirtyF**
fix #6118

### CODE REVIEW

**Comment by DirtyF** [comment]
@jekyllbot: merge +docs

**Comment by pathawks** [comment]
Thank you @mittalyashu for bringing this up, and @DirtyF for getting it fixed :beers::+1:

**Comment by mittalyashu** [comment]
Big FAN of Jekyll. Love to contribute more.

**Comment by huangxianfeng** [comment]
good

**Pull request merged**
