### PR TITLE
Exclude vendor by default

### LINKED ISSUE #5359: Invalid date error resolution
- [x] I believe this to be a bug, not a question about using Jekyll.
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [x] This is a feature request.

---

- [x] I am on (or have tested on) ***macOS*** 10+
- [ ] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [ ] I am on (or have tested on) ***Fedora*** GNU/Linux
- [ ] I am on (or have tested on) ***Arch*** GNU/Linux
- [ ] I am on (or have tested on) ***Other*** GNU/Linux
- [ ] I am on (or have tested on) ***Windows*** 10+

---

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have reproduced it locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [x] I was trying to build.
- [ ] It was another bug.

## My Reproduction Steps

```
gem update jekyll
jekyll new foo
cd foo
bundle install
bundle exec jekyll serve
```

## The Output I Wanted

```
     Generating... 
                    done in 0.332 seconds.
 Auto-regeneration: enabled for '/Users/micahtaylor/Sites/foo'
Configuration file: /Users/micahtaylor/Sites/foo/_config.yml
    Server address: http://127.0.0.1:4000/
  Server running... press ctrl-c to stop.
```
## The Output I Received
```
Generating... 
             ERROR: YOUR SITE COULD NOT BE BUILT:
                    ------------------------------------
                    Invalid date '<%= Time.now.strftime('%Y-%m-%d %H:%M:%S %z') %>': Document 'vendor/bundle/gems/jekyll-3.2.1/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb' does not have a valid date in the YAML front matter.
```

## The resolution
I am able to resolve this by excluding vendor dir to the `_config.yml`
```exclude:
- vendor
```

### PR DESCRIPTION
**Pull request by DirtyF**
Fix #5359 

- [x] Update documentation

cc/ @jekyll/core

### CODE REVIEW

**Comment by mattr-** [comment]
LGTM.

**Comment by Crunch09** [comment]
Do we need to document this somewhere?

Linking #5210 because excluding `vendor` was also mentioned in there.

**Comment by DirtyF** [comment]
@Crunch09 you're right, I'll update the PR to mention it in https://jekyllrb.com/docs/configuration/#default-configuration

**Comment by parkr** [comment]
@jekyllbot: merge +minor

**Comment by envygeeks** [comment]
:heart: so much for this.  It'll be such  relief not to build a new Jekyll site and have it fail the first build only for me to remember to add vendor/bundle to the list of excludes.

**Comment by just-boris** [comment]
This is breaking change!

I had a repo on Github with `gh-pages`, that contains some file and also a `vendor` dir with some third-party libraries. Today I tried to update that project and it had been broken.

Finally, I have figured out that `vendor` dir is ignored by default now, but that was very sudden, there was no announce, that here will be new default options, and users should check their pages.

**Comment by ashmaroli** [comment]
This has been [patched](https://github.com/jekyll/jekyll/pull/5564) with `v3.3.1` Now only a few specific sub-directories inside `vendor` are ignored. Github-Pages gem will be updated soon to fix this issue.

/cc @benbalter

**Pull request merged**
