### PR TITLE
add a script to test theme-gem building

### PR DESCRIPTION
**Pull request by ashmaroli**
Add a script to automatically test if the theme gem scaffolding builds a gem as intended.
(initial commit; open to feedback)

### CODE REVIEW

**Comment by parkr** [comment]
I think it would make more sense here to have this be a Cucumber feature. I believe we have `jekyll new` tests in there as well, and it doesn't look like your script does anything new.

**Comment by ashmaroli** [comment]
@parkr ,This script proves that currently, the theme-gem is empty.
Though, for some reason, travis doesn't recognize the script.

**Comment by ashmaroli** [comment]
I'm delegating this PR to concern only with `script/theme-gem`

**Comment by ashmaroli** [comment]
@envygeeks, any idea why travis doesn't recognize this script as part of the [TEST-SUITE] ?

**Comment by envygeeks** [comment]
@ashmaroli because your script isn't executable.  We explicitly check for the executable bit rather than existence as a safeguard.  If you've no access to Linux you can enable contributor contributions on your pull and I can pull it and set the bit for you, otherwise you should set the executable bit on on `script/theme-gem`

**Comment by ashmaroli** [comment]
I've now enabled
- [x] Allow edits from maintainers.

**Comment by envygeeks** [comment]
I've set the executable bit for you.

**Comment by ashmaroli** [comment]
Thanks Jordon :smiley:

**Comment by parkr** [comment]
Thanks, @ashmaroli! I appreciate you compiling this. I think this would be much better as a Cucumber feature still so I'm going to close this out in favor of a pull request using Cucumber. 😄

**Comment by ashmaroli** [comment]
:disappointed:

**Comment by ashmaroli** [comment]
Agreed, this script doesnt have a long-term use. 
But it could positively test the upcoming patch to gemspec template.

**Comment by parkr** [comment]
@ashmaroli Sorry! I remember seeing this as a cucumber feature in some PR... wasn't that you?

**Comment by ashmaroli** [comment]
Must've been me.. I did make a commit with a feature file I cooked up using cues from existing ones. Since I could not run it on my windows machine, I pushed it to see how travis ran it.. I quickly deleted that commit from this branch thereafter.

**Pull request closed without merging**
