### PR TITLE
Add missing GFM syntax highlighting background

### PR DESCRIPTION
**Pull request by sparanoid**

### CODE REVIEW

**Comment by parkr** [comment]
Can you show a before and after example, please? Curious how this changes things.

**Comment by sparanoid** [comment]
@parkr sorry for the lack of reproduction steps:

```sh
~ $ mkdir jekyll-rouge && cd jekyll-rouge
~/jekyll-rouge $ jekyll new
```

Add the following config in `_config.yml`:

```yaml
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
```

Add the following snippets in `_posts/2015-10-26-welcome-to-jekyll.markdown`

    ```ruby
    def print_hi(name)
      puts "Hi, #{name}"
    end
    print_hi('Tom')
    #=> prints 'Hi, Tom' to STDOUT.
    ```
    
    {% highlight ruby %}
    def print_hi(name)
      puts "Hi, #{name}"
    end
    print_hi('Tom')
    #=> prints 'Hi, Tom' to STDOUT.
    {% endhighlight %}

Then:

```sh
~/jekyll-rouge $ jekyll s
```

Result:

image

I've re-apply background color for `.highlight` in `.highlighter-rouge`, this should fix this issue.

**Comment by envygeeks** [comment]
I'm gonna be honest, there should be no disparity between Rogue and Pygments :-1:

**Comment by sparanoid** [comment]
@envygeeks just rechecked the config after I found [this issue](https://github.com/jekyll/jekyll/pull/3323), you don't need to change the config since rouge is the default highlighter, so this PR should be “Add missing GFM syntax highlighting background”

**Comment by envygeeks** [comment]
That's not relevant, it wasn't there for Pygments (apparently -- according to the CSS -- and btw, Pygments is still available, the default is in no way the defacto -- at least in this case.) That means there will be a disparity.

**Comment by AndorChen** [comment]
@envygeeks As far as I know, there are no much differences between Pygments and Rouge, the problem issued here is caused by kramdown, as you can see in [the source code where the `.highlighter-rouge` class added](https://github.com/gettalong/kramdown/blob/master/lib/kramdown/converter/html.rb#L98).

**Comment by parkr** [comment]
Yeah, it looks like Kramdown does this. https://github.com/gettalong/kramdown/blob/7a7bd675b9d2593ad40c26fc4c77bf8407b70b42/lib/kramdown/converter/html.rb#L365-L368

I don't see a huge issue with doing this in the CSS. I wouldn't want to change our Ruby for it, but adding this class seems pretty harmless to me.

**Comment by envygeeks** [comment]
@parkr, it's not about adding the class, it's that the class is only added to Rogue, unless this affects pygments too, it's a disparity and an oddity to say the least.  We should keep it uniform across both... but I didn't look at the CSS fully to even see if Pygments is supported by default in that CSS anyways.

**Comment by parkr** [comment]
> but I didn't look at the CSS fully to even see if Pygments is supported by default in that CSS anyways.

Yeah, the highlighting CSS was written to the output of Pygments some time ago.

**Pull request merged**
