### PR TITLE
WIP: Experiment with replacing Addressable for URL filters

### PR DESCRIPTION
**Pull request by jekyllbot**
PR automatically created for @pathawks.

```text
Experiment with replacing Addressable for URL filters
```

### CODE REVIEW

**Comment by pathawks** [comment]
@ashmaroli See the failing tests. If we can make this work, _and_ it's significantly faster, let's do it.

If it cannot be made **significantly** faster, we should absolutely _not_ do it, because I don't want to be responsible for i18n edge cases.

**Comment by ashmaroli** [comment]
@pathawks if you're still working on this experiment, please stop. I don't think its worth it..
If we're going to use the regex, we'll have to expand it include all possible schemes valid in a url.. e.g. (`ftp://~`)

**Comment by pathawks** [comment]
Closing in favor of #6747

**Comment by pathawks** [comment]
> please stop

🤣🤣🤣

**Pull request closed without merging**
