### PR TITLE
Remove Glynn as deployment option

### PR DESCRIPTION
**Pull request by neudabei**
Remove Glynn as deployment option since that gem is no longer actively maintained. See notes in readme in repository: https://github.com/dmathieu/glynn and https://github.com/dmathieu/glynn/issues/67

### CODE REVIEW

**Comment by DirtyF** [comment]
@neudabei 👍 

/cc @jekyll/documentation

**Comment by neudabei** [comment]
😉 Maybe it can be re-considered once the glynn project is maintained again for those who still want to use FTP or rather SFTP with jekyll.

**Comment by DirtyF** [comment]
@jekyllbot: merge +site

**Comment by Phlow** [comment]
Damn, that's sad. I use *Glynn* for small websites on my own webspace. It was so easy to use…

**Comment by neudabei** [comment]
@Phlow +1, I used it too and was very glad when I found it.

**Pull request merged**
