### PR TITLE
Fix spelling of GitHub in docs and history

### PR DESCRIPTION
**Pull request by splattael**
* Github -> GitHub
* GitHub pages -> GitHub Pages

### CODE REVIEW

**Comment by parkr** [comment]
capital_H_dangit

**Comment by parkr** [comment]
Thanks a lot :smile:

**Comment by splattael** [comment]
I doubt that this PR caused the build failures on Travis :smiley_cat:

**Comment by parkr** [comment]
> I doubt that this PR caused the build failures on Travis 

You're correct!

**Comment by splattael** [comment]
Thanks for merging :green_heart:

**Comment by parkr** [comment]
Thanks for the pull request!!

**Pull request merged**
