### PR TITLE
Add link to Staticman

### PR DESCRIPTION
**Pull request by eduardoboucas**
This PR adds a link to [Staticman](https://staticman.net), a free and open source platform to insert user-generated into a Jekyll site by converting entries to data files and pushing them to the repository where the site lives.

### CODE REVIEW

**Comment by parkr** [comment]
LGTM. Did you test this locally? From the syntax highlighting weirdness, there may be an issue parsing this list with the quotation above it. Please give it a preview locally 👍

**Comment by eduardoboucas** [comment]
Sorry for the delay, finally got around to testing this locally. It looks good!

**Comment by DirtyF** [comment]
LGTM

**Comment by eduardoboucas** [comment]
Is there anything else that needs to be done on my end?

**Comment by DirtyF** [comment]
@eduardoboucas nope.

@parkr it's OK locally:

preview-resources

**Comment by envygeeks** [comment]
@jekyllbot: merge +site

**Pull request merged**
