### PR TITLE
Add DEV Community's Jekyll tag to community page

### PR DESCRIPTION
**Pull request by belhassen07**
[DEV Community](https://dev.to/) is a burgeoning source of guidance and discussion on software topics, especially web dev. This will be a useful link to point to the official place to discuss Jekyll matters on the platform.

A few additional links pertaining to dev.to

Traffic stats: https://www.similarweb.com/website/dev.to
Twitter: https://twitter.com/thepracticaldev
Jekyll tag (as included in PR): https://dev.to/t/jekyll

Some example Jekyll posts:
https://dev.to/evantypanski/the-art-of-a-personal-website-15h1
https://dev.to/adrienjoly/how-to-maintain-a-collection-of-music-albums-online-using-jekyll-and-github-pages-3hd6
https://dev.to/jaybeekeeper/getting-started-with-jekyll-3nf9

Happy coding :heart:

### CODE REVIEW

**Comment by pathawks** [comment]
I was going to ask if this might seem like an endorsement of a third-party site, but given that it is right above a link to a Google search for Jekyll, I think it is clear 👌

**Comment by belhassen07** [comment]
it has been added to the official react website as well : https://reactjs.org/community/support.html 
It's about adding a place where people can discuss or write about Jekyll mostly @pathawks.

**Comment by belhassen07** [comment]
can someone merge this?

**Comment by oe** [comment]
@jekyllbot: merge +doc

**Pull request merged**
