### PR TITLE
Create analytics.html

### PR DESCRIPTION
**Pull request by vrajchauhan**

### CODE REVIEW

**Comment by pathawks** [comment]
Was this opened by mistake?

Can you explain your motivation here?

**Comment by vrajchauhan** [comment]
Yes, actually i am trying to link google analytics.

**Comment by pathawks** [comment]
> Yes, actually i am trying to link google analytics.

Are you trying to add Google Analytics to your own site? You are adding this file to the root of the main Jekyll repo, where no Jekyll site exists.

**Comment by DirtyF** [comment]
@vrajchauhan Google Analytics is already active and running on Jekyll's website, so as @pathawks assumed, I guess you opened this by mistake :)

**Comment by vrajchauhan** [comment]
Yes, it was not intentional. I apologize if i messed up something.

**Pull request closed without merging**
