### PR TITLE
New website again woo

### PR DESCRIPTION
**Pull request by jordanthornquest**
I moved my blog with an article about Jekyll to a new location and updated the resources page to reflect the change. Shouldn't need to change that again. Thanks again, @parkr, you're the bestest :heart:

### CODE REVIEW

**Comment by pathawks** [comment]
Could you possibly leave a more descriptive commit message?

**Comment by jordanthornquest** [comment]
Sure! I've edited it.

**Comment by envygeeks** [comment]
It seems Github is not picking up your changes? Did you +branch it up to Github?

**Comment by parkr** [comment]
:+1: with @pathawks comment addressed.

**Comment by jordanthornquest** [comment]
Oh, I'm sorry! I misunderstood. I edited my comment here on GitHub, but not the actual Git commit! I'll get right on that.

**Comment by jordanthornquest** [comment]
Done. Sorry for the wait!

**Comment by envygeeks** [comment]
Now there is an issue with your dangling merge commit, can you please edit your history and remove it.

**Comment by jordanthornquest** [comment]
Yes I can! All done. Thanks for your help!

**Comment by envygeeks** [comment]
:heart: :shipit:

**Comment by parkr** [comment]
The irony of linking out to a Tumblr blog post about a Jekyll feature. lol

**Comment by jordanthornquest** [comment]
Haha! I still love Jekyll for static sites, for sure. GitHub Pages is rad :)

**Comment by jordanthornquest** [comment]
Hey, guys! I'd like to reopen this and, for the last time, make a change. There are far superior articles to mine on the same topic, now, and I feel mine isn't needed anymore. I'd like to delete the post, but I'd also like to ensure there isn't a dangling link on the Jekyll website. What needs to be done to make this happen?

**Comment by envygeeks** [comment]
You can submit a PR to remove it but IMO there is no need, a resource is a resource and all are good.

**Pull request merged**
