### PR TITLE
Enhance 'link' tag to include variables support

### PR DESCRIPTION
**Pull request by alexey-pelykh**
This would allow to use
```
{% assign path = 'some/variable/path.md' %}
{% link {{path}} %}
```
in addition to
```
{% link some/hardcoded/path.md %}
```
(similar to `include` tag)

### CODE REVIEW

**Comment by parkr** [comment]
What do you think about

```text
{% assign path = 'some/variable/path.md' %}
{% link path %}
```

?

**Comment by alexey-pelykh** [comment]
@parkr I think it's better to leave a marker of a variable to avoid misreading + is there a chance that I'll have an extensionless file `path`? Maybe it would be great to support something like
```
{% assign path = 'some/variable/path.md' %}
{% link '{{site.locale}}{{path}}' %}
```
?

And how to treat spaces between marker `{{` and first character of the variable?
Yesterday I got a bit confused about jekyll-assets plugin since `{% include {{ variable }} %}`(note the spaces) is ok, yet `{% image {{\ variable\ }} %}` (note the escaping). That inconsistency broke my mind for a couple of minutes :)

**Comment by parkr** [comment]
Ah, yes! Also, I realized that this functionality is basically the same as for the `include` tag (you can do `{% include {{path}} %}` so the syntax lines up OK. I really think we should just run the whole input string (e.g. `{{path}}`) through Liquid 😉  At any rate, I wonder if we can reuse some of that code here?

**Comment by alexey-pelykh** [comment]
Since I've used `include` tag as a reference :) You mean parse path like in #6269?

**Comment by alexey-pelykh** [comment]
@parkr what's next?

**Comment by alexey-pelykh** [comment]
@parkr rebased

**Comment by pathawks** [comment]
Closing in favor of #6269

**Pull request closed without merging**
