### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by ss18**
Fixed typos:
programatically -> programmatically
occured -> occurred
recieve -> receive
postive -> positive
severly -> severely
statment -> statement
unecessary -> unnecessary

### CODE REVIEW

**Comment by pathawks** [comment]
Generally we don’t modify `History.markdown`, but I think this is ok :+1:

**Comment by pathawks** [comment]
Think we should categorize this as `+docs`?

It touches code, but it’s not a bugfix or enhancement…

**Comment by ashmaroli** [comment]
I'd categorize it as `docs` as well.. The lone edit to ruby code is on a test file

**Comment by pathawks** [comment]
@jekyllbot: merge +docs

**Comment by pathawks** [comment]
Thanks @ss18 :beers::+1:

**Pull request merged**
