### PR TITLE
Prevent reset of page in Liquid payload right before rendering layouts

### LINKED ISSUE #4414: Jekyll 3.1 broke page payload in layout
I have a plugin running on every page and adding a property to the payload:

```ruby
Jekyll::Hooks.register :pages, :pre_render do |page, payload|
## do stuff
    payload['page']['breadcrumbs'] = breadcrumbs
    #binding.pry

  end
```

In my layout file I have an include:
`{% include breadcrumb.html %}`

My `breadcrumb.html` uses the variable `{{page.breadcrumbs}}`.

With 3.0 this worked fine and I had access to this variable. Since upgrading to 3.1 this variable is now empty.

If I try to print the same variable in the page itself then it works. It does not work in the layout files or includes within the layout.

### PR DESCRIPTION
**Pull request by nasht00**
Note that this prevents the workaround from working anymore.

### CODE REVIEW

**Comment by nasht00** [comment]
Checks are apparently failing...

**Comment by envygeeks** [comment]
Checks are fine, restarted the test for you.  I'm curious if this will have any problems down the line but it's LGTM.  :shipit:

**Comment by parkr** [comment]
Perfect! @nasht00, would you please add a test for this? Create a hook like you did in #4414 and place it in a `.feature` file. You may create a new scenario in `features/hooks.feature` if you like. 😄 I don't want to break this again!

**Comment by nasht00** [comment]
I'm not familiar with this .feature syntax, this reads like plain English. The test will execute this as-is??

**Comment by nasht00** [comment]
Added a scenario. I would love some code review as this is a first for me.

**Comment by parkr** [comment]
Looks good to me! Failing Travis check is a formatting error unrelated to your change. Thank you 😄 

@jekyllbot: merge +bug

**Comment by parkr** [comment]
> I'm not familiar with this .feature syntax, this reads like plain English. The test will execute this as-is??

Yes it does! 😄 https://travis-ci.org/jekyll/jekyll/jobs/137730352#L466

**Pull request merged**
