### PR TITLE
Disable incremental regeneration by default in Jekyll 3.0

### PR DESCRIPTION
**Pull request by alfredxing**
Disable the feature as it's still not 100% working 100% of the time. Incremental regeneration can be re-enabled by specifying `full_rebuild: false` in the configuration.

(As per discussion in #4057)

### CODE REVIEW

**Comment by parkr** [comment]
Need to update `--full-rebuild` tag to something like `--incremental` or `--incr`.

**Comment by parkr** [comment]
Is there _any_ documentation on this feature? Perhaps it can say it's off by default.

**Comment by alfredxing** [comment]
On it!

There's barely any documentation, though it prints out whether it's enabled when building:

```
Configuration file: /Users/alfred/git/jekyll/test/_config.yml
            Source: /Users/alfred/git/jekyll/test
       Destination: /Users/alfred/git/jekyll/test/_site
 Incremental build: disabled
      Generating...
```

**Comment by parkr** [comment]
> Incremental build: disabled

Maybe we should change this to say `disabled. Enable with --incremental.`?

**Comment by jaybe-jekyll** [comment]
I prefer a switch/command/trigger to enable regeneration in general regardless of current state.

Building, Serving, Regenerating... all specific and chosen capabilities.

I would expect `jekyll build` to build once and return successful.

I would expect to `jekyll build ---watch` or `jekyll build -w` to enable/turn on regeneration.

$.02 💸

**Comment by envygeeks** [comment]
@jaybe-jekyll that very well could be the case when it's enabled by default but with it being disabled by default as an experimental feature now, that won't work.

**Comment by parkr** [comment]
@jaybe-jekyll It's still very experimental, but that's a fantastic idea for the future! :)

**Comment by alfredxing** [comment]
Agreed! Commits coming as soon as the tests pass. It'll be `incremental` in configuration and `--incremental` or `-ir` as command-line flags.

**Comment by jaybe-jekyll** [comment]
I need to correct myself; apologies --

I prefer a switch/command/trigger required to enable regeneration,

Building, Serving, Regenerating... all specific and chosen capabilities.

I would expect `jekyll build` to build once and end, returning as successful.

I would expect to `jekyll build --regnerate`to enable/turn on regeneration, with or without --watch, as --regeneration would presume --watch.

Pfew.

$.02 💸

**Comment by parkr** [comment]
I think `-ir` might get confusing. Maybe `--ir` or use just one character for a single dash.

**Comment by alfredxing** [comment]
@parkr: Would you prefer `-i` or `-r` for the shorthand flag?

@jaybe-jekyll Not sure about the "flag presumes `--watch`" part, since incremental regen would offer a performance improvement even without watching (so users might want to enable it without enabling watch)

**Comment by jaybe-jekyll** [comment]
Another opinion; I think the term, "incremental", in "incremental regeneration" (i.e. --ir) applies more to a technical audience and isn't necessarily necessary or appropriate for general use(rs).

*Regenerate.*

Agreed; single character enablement; perhaps `-R` (for, **REGENERATION POWERS ACTIVATED**). And, for the verbose and visually-minded, `--regenerate` and or `--regeneration`.

**Comment by parkr** [comment]
> @parkr: Would you prefer -i or -r for the shorthand flag?

Historically, I have used `-i` for "case-insensitive", and `-r` for "recursive." I would go with the first character of the double-dashed one or an alternative if it isn't there.

**Comment by jaybe-jekyll** [comment]
@alfredxing I don't see how generation could occur within a system without --watch; does it not imply watching for changes (`--watch`) then acting on those changes (`--regenerate`)?

**Comment by envygeeks** [comment]
@parkr @alfredxing: @jaybe-jekyll brings up a fine point, why not call the flag `--cache`? That's literally what it's doing, but we call it incremental regeneration as a technical term, when Occam is standing over there pointing to the term: caching.

**Comment by parkr** [comment]
Does the `sass` compiler have a flag like this? Our Jekyllers tend to be front end devs so maybe Sass's CLI is known.

**Comment by parkr** [comment]
@jaybe-jekyll Yeah, it's more about caching. `--watch` says "hey, regenerate every time you detect a changed file!" and `--regenerate` or `--increment` or `--cache` is "hey, when you do regenerate, only regenerate the changed files!".

**Comment by envygeeks** [comment]
Sass by default caches so they have a `--force` flag which forces it to update the cache even if it's cached.

**Comment by parkr** [comment]
@alfredxing just waiting on this PR. once it's merged, i'll release an RC and then do any final bug fixes before I release around 8pm PST tonight.

**Comment by alfredxing** [comment]
Sure! Right now I have it as `-I` and `--incremental`. If we don't think `-I` is appropriate, I can remove it!

**Comment by envygeeks** [comment]
`-I` is what I instantly thought of when you said you wanted `--incremental` so I'm :+1:

**Comment by parkr** [comment]
Looks great! Thanks so much, @alfredxing. I'll merge once it's :green_heart: .

**Comment by alfredxing** [comment]
:+1:

Good luck (& congrats!) on the launch tonight!

**Comment by parkr** [comment]
> Good luck (& congrats!) on the launch tonight!

@alfredxing Congrats to you, too! It's been a huge team effort. Thanks for all your time and effort thus far – it's meant a lot!

**Pull request merged**
