### PR TITLE
Rename CONDUCT.md to CONDUCT.markdown

### PR DESCRIPTION
**Pull request by SuriyaaKudoIsc**
@mojombo @parkr @mattr- 

----

Hi guys, :smile: 

I renamed the **`CONDUCT.md`** file to **`CONDUCT.markdown`** because all other Markdown files like *README*, *CONTRIBUTING* and the *HISTORY* files got a *`.markdown`* file ending instead of *`.md`*!

*Yours,*
[**Suriyaa Kudo**](https://github.com/SuriyaaKudoIsc) :octocat:

### CODE REVIEW

**Comment by parkr** [comment]
Ok! I guess I can buy the conformity argument here. :wink: Thanks!

**Comment by SuriyaaKudoIsc** [comment]
@chris72205 done it already in #4434!

**Comment by chris72205** [comment]
I just updated the README.  The site links were fixed in #4436

**Comment by SuriyaaKudoIsc** [comment]
@chris72205 :+1:

**Pull request merged**
