### PR TITLE
Update rubocop to ~> 0.63.1

### LINKED ISSUE #7480: Update dependency constraint to allow for rubocop v0.63.0
Hey there! :wave:

I noticed that the constraint you have for rubocop doesn't allow for the latest version to be used.

The constraint I found was `~> 0.62.0`, and the latest version available is `0.63.0`.

Can you look into updating that constraint so our users can use the latest and greatest version? Thanks! :revolving_hearts:

### LINKED ISSUE #7490: Update dependency constraint to allow for rubocop v0.63.1
Hey there! :wave:

I noticed that the constraint you have for rubocop doesn't allow for the latest version to be used.

The constraint I found was `~> 0.62.0`, and the latest version available is `0.63.1`.

Can you look into updating that constraint so our users can use the latest and greatest version? Thanks! :revolving_hearts:

### PR DESCRIPTION
**Pull request by luisenrike**
## Summary

Update rubocop to ~> 0.63.0

## Context

Fixes #7480
Fixes #7490

### CODE REVIEW

**Comment by ashmaroli** [comment]
`rubocop-0.63.1` is already out though..

**Comment by ashmaroli** [comment]
Yes, that is correct. Since the bug in `0.63.0` has been resolved, we should not support it longer.
Say a user has only `rubocop-0.63.0` installed. If he were to clone the repo after this PR is merged, he would get an error when he runs our `script/fmt`.
But if we were to not support `v0.63.0`, he would be forced to update to the resolved version.

**Comment by luisenrike** [comment]
👍 that makes sense, so it should be `gem "rubocop", "~> 0.63.0", ">= 0.63.1"`, right?

**Comment by ashmaroli** [comment]
```
gem "rubocop", "~> 0.63.1"
```
should suffice IMO..

**Comment by ashmaroli** [comment]
Thank you very much @luisenrike 

@jekyllbot: merge +dev

**Pull request merged**
