### PR TITLE
add documentation about the "pinned" label

### PR DESCRIPTION
**Pull request by pup**
i noticed that documentation about this label was missing. are there any other undocumented special labels?

### CODE REVIEW

**Comment by pup** [comment]
cc @jekyll/documentation

**Comment by DirtyF** [comment]
@pup according to the source code `security`and `has-pull-request` also prevent an issue from being marked as `stale`

https://github.com/parkr/auto-reply/blob/f1933491fbda8e521572d7695dbe2bbc623e111c/cmd/mark-and-sweep-stale-issues/mark_and_sweep_stale_issues.go#L22-L25

**Comment by pup** [comment]
@DirtyF huh! the question is, do we want to list those as viable alternatives that could be used instead of `pinned`? i think it might cause some confusion, especially with `security`

**Comment by pup** [comment]
i'll add a note that `has-pull-request` has the same effect, but shouldn't be used singularly to achieve it

**Comment by DirtyF** [comment]
@pup `has-pull-request`is often set automatically when mentioning `fix`and isssue number in a PR comment, so it's not a label I use very much.

**Comment by DirtyF** [comment]
@jekyllbot: merge +docs

**Pull request merged**
