### PR TITLE
Reduce array traversal in Jekyll::Reader

### PR DESCRIPTION
**Pull request by ashmaroli**
This proposal is mainly to replace the following steps with optimized alternatives and see what Utterson feels about it.
```ruby
dot_dirs  = dot.select { |file| File.directory?(@site.in_source_dir(base, file)) }
dot_pages = dot_files.select { |file| Utils.has_yaml_header?(@site.in_source_dir(base, file)) }
```
Also `dot_files = (dot - dot_dirs)` simply exists to create another array `dot_static_files` ...

### CODE REVIEW

**Comment by pathawks** [comment]
Not a performance optimization, but maybe more readable :+1:

**Comment by ashmaroli** [comment]
> Not a performance optimization

Strange indeed. @pathawks Do you have any input on how / why my logic is flawed here..?

**Comment by pathawks** [comment]
@ashmaroli Unfortunately, no. Logic seems sound; I also would have guessed this would be faster. 🤷‍♂️

**Comment by ashmaroli** [comment]
> I can run one locally, if you like

No, that's not necessary. But, thanks anyways..

**Comment by pathawks** [comment]
| ref                                      | build time in seconds |
|:-----------------------------------------|----------------------:|
| #7157                                    |                287.63 |
| `master`                                 |                289.64 |

On my laptop, results show a couple seconds in the other direction. It seems like we're doing the same basic things either way, but I'd say this change is a bit more readable :+1:

**Comment by ashmaroli** [comment]
@jekyllbot: merge +dev

**Pull request merged**
