### PR TITLE
Use keyword arguments instead of a Hash argument

### PR DESCRIPTION
**Pull request by ashmaroli**
- This is an :zap: optimization change

## Summary

Testing to see if this has a visible gain in performance..
The included benchmark script shows that using keyword args are about ~2.5x faster than a Hash argument

### CODE REVIEW

**Comment by ashmaroli** [comment]
Utterson reports a ~3s gain:

ref | build time in seconds
-- | --
#7361 | **232.63**
master | 235.23

**Comment by mattr-** [comment]
Is it possible to estimate the impact this will have on plugins, sites, etc? Switching to keyword arguments is a breaking change. I don't have any problems with that, but it would be good to know and  document the cases where we expect breakage as part of an upgrade guide for 4.0

**Comment by ashmaroli** [comment]
@mattr- To me, this change does not classify as "breaking" since the constructor signature has not changed. It just took a more explicit form.
Moreover, our test-suite that mocks new instances (esp. of `Document` and `URL`) pass without any modification. So I'm pretty confident that this would have zero impact on plugins.

**Comment by mattr-** [comment]
@ashmaroli The constructor signature has changed though. Options that could be present in the hash, should this PR gets merged, are no longer permitted. In general, a move like this from less explicit to more explicit is a breaking change.

Consider the following method:
```ruby
def foo(test:, test2:)
  puts "#{test} #{test2}"
end
```

If you call it with an extra parameter, you'll get an argument error:
```ruby
irb(main):009:0> foo(test: "foo", test2: "bar", test3: "baz")
ArgumentError: unknown keyword: test3
        from (irb):5:in `foo'
        from (irb):9
        from /usr/bin/irb:11:in `<main>'
```

The hash variant does not raise an error, and if the method never uses the extra pairs in the hash, there's not a problem:
```ruby
def foo(hash)
  puts "#{hash}"
end
```
```ruby
irb(main):013:0> foo(test: "foo", test2: "bar", test3: "baz")
{:test=>"foo", :test2=>"bar", :test3=>"baz"}
```


We need to document that we've changed the signatures of `Jekyll::Document` and `Jekyll:Url` so that users can make adjustments since both of these classes are public API.

**Comment by ashmaroli** [comment]
@mattr- I proposed this change under the impression that it wouldn't be a breaking change.
But in the light of your explanation, I no longer wish to proceed with this and add complexity for minor perf gains.

Thank you very much for the detailed explanation.

**Pull request closed without merging**
