### PR TITLE
Adds ability to link to all files

### PR DESCRIPTION
**Pull request by jeffkole**
Fixes request made in #4624 and bug found in #5182

### CODE REVIEW

**Comment by envygeeks** [comment]
What bug? I see no bug in that documentation.

**Comment by DirtyF** [comment]
Thanks @jeffkole link to pages and files works fine now :)

I tested it a bit and noticed that you have to use add a `/` before the path to a file:

`{% link /assets/files/doc.pdf %} `

Also, just so you know I didn't manage to link to a data file with `{% link _data/file.yml %} ` but's it's out of the scope of this fix.

@envygeeks it wasn't a bug in the documentation but rather in the implementation of the brand new `link`tag.

**Comment by parkr** [comment]
@jeffkole Because you added a file to the test fixture site, you have to update another test: https://travis-ci.org/jekyll/jekyll/jobs/149605617

**Comment by jeffkole** [comment]
@DirtyF That is annoying, isn't it. Looks like static files get a leading slash added to their relative path property.  I'll check in a fix.

**Comment by parkr** [comment]
LGTM!

**Comment by DirtyF** [comment]
@jekyll/core LGTY?

**Comment by envygeeks** [comment]
I like that it has tests.  Thanks for adding tests.  LGTM.

**Comment by envygeeks** [comment]
Since I don't remember the tag for a feature +minor? I'll let @parkr or somebody else on @jekyll/core deal with the merge.

**Comment by mattr-** [comment]
@jekyllbot: merge +minor

**Comment by mattr-** [comment]
@envygeeks you were right. It's +minor. 😃

**Pull request merged**
