### PR TITLE
Rubocop: Require consistent comma in multiline literals

### PR DESCRIPTION
**Pull request by jekyllbot**
PR automatically created for @pathawks.

```text
Rubocop: Require consistent comma in multiline literals
```

### CODE REVIEW

**Comment by DirtyF** [comment]
Same change as @parkr did in https://github.com/github/pages-gem/pull/383/

**Comment by pathawks** [comment]
@DirtyF I wonder what got me thinking about it 🤔 🤣

**Comment by DirtyF** [comment]
@jekyllbot: merge +dev

**Comment by ashmaroli** [comment]
Rubocop `v0.47.1` now raises an offence against a [hash](https://github.com/jekyll/jekyll/blob/master/test/test_site_drop.rb#L7) previously ignored.. 
overzealous cop? or error on our side?

**Comment by parkr** [comment]
We used the auto-correct feature here so probably an edge case that was fixed in the latest version of Rubocop.

**Pull request closed without merging**
