### PR TITLE
Symlink local tmp

### LINKED ISSUE #2831: test/source/_includes/tmp is a symlink to /tmp
https://github.com/jekyll/jekyll/blob/c8b22a19adee0d2dfe3418349b314c35dd8c1212/test/source/_includes/tmp

There has to be some way around symlinking to /tmp. It causes all sorts of permissions errors in certain environments and does not work at all with dropbox (dropbox tries to sync the whole /tmp) folder. Is there a more elegant solution?

### PR DESCRIPTION
**Pull request by omegahm**
Fixes #2831 and possibly #2773

The two tests regarding symlinks will use `tmp` in the root-dir instead of `/tmp`.

### CODE REVIEW

**Comment by parkr** [comment]
Cool! We alread have a tmp directory so I'd rather use that. Kill the . and we're in business. Thanks!

**Comment by omegahm** [comment]
@parkr I think we might need to have the `tmp` folder in Git with a `.keep` file. What's your take on that?

**Comment by parkr** [comment]
> @parkr I think we might need to have the tmp folder in Git with a .keep file. What's your take on that?

I'd rather the `script/test` create the `tmp` directory than track it through Git.

**Comment by omegahm** [comment]
@parkr Yup, I can see that that is actually also what is failing on Travis. :dizzy_face:

I have added `mkdir tmp` to `script/cibuild`.

**Comment by XhmikosR** [comment]
This will fix 2 of the failing tests on Windows too hopefully.

**Comment by parkr** [comment]
Great work. :shipit:

**Pull request merged**
