### PR TITLE
Create CSV to table tutorial

### LINKED ISSUE #8086: How to access the header row in imported .csv data
## Motivation

For any arbitrary imported .csv data file, I'd like to learn how to read and display the column names in the header. I can't find an example in the Jekyll docs that describes how to access the header row.

### PR DESCRIPTION
**Pull request by MichaelCurrin**
This is a 🔦 documentation change.

## Summary

Added tutorial and updated tutorial navigation list.

## Context

Resolves #8086

### CODE REVIEW

**Comment by DirtyF** [comment]
FYI: Shopify has a [`tablerow`](https://shopify.github.io/liquid/tags/iteration/#tablerow) tag that accepts some [parameters](https://shopify.github.io/liquid/tags/iteration/#tablerow-parameters).

**Comment by ashmaroli** [comment]
@MichaelCurrin Thank you very much.
I would like to point some things out though:
- Like @DirtyF mentioned above, you can use Liquid's `tablerow` tag for more concise code. However, that tag only renders `<tr>` elements with `<td>` children, though.
- I'd like you to put your name or GitHub username as this tutorial's author. (We currently don't render that info on the website, but I plan on doing that soon..)
- Now for some nitpicking..
  - I'm not a fan of using `{% assign ... %}` for the sake of it. You can just as easily use
`<th>{{ pair[0] }}</th>` and `<td>{{ pair[1] }}</td>` directly.
  - It'd be better if the line-lengths were broken at 125 characters or less, instead of having one long line that gets folded over to multiple lines.

**Comment by MichaelCurrin** [comment]
Sure. Sensible suggestions.

For now I'll add author to the top (otherwise bottom?) directly.

I'd be happy to take on author as a next issue - is there one open? I can see that working with frontmatter and layout, even pulling in profile pic.

**Comment by ashmaroli** [comment]
We already use the `jekyll-avatar` plugin to pull in profile pics for the author. (Take a look at one of release posts on the website). For this PR though, just having the `author` metadata in the front matter should suffice.

**Comment by ashmaroli** [comment]
Oh yeah, I forgot. I think you should also add a paragraph about the use of `inspect` filter to understand the actual data. That'll make it clear as to why you use integer keys to access a row data.

**Comment by ashmaroli** [comment]
@MichaelCurrin We have updated the `master` branch to render author name and tutorial date when provided. You can run `git pull upstream master` locally to have this branch synced.
Thank you.

**Comment by MichaelCurrin** [comment]
Thanks for all the suggestions. I've made the changes. 

The author part displays well for me.

**Comment by ashmaroli** [comment]
Thank you for incorporating the changes, @MichaelCurrin 
The rendered tutorial can be previewed at the link:
https://deploy-preview-8090--jekyllrb.netlify.com/tutorials/csv-to-table/

I see some minor typo and the need for better syntax-highlighting.
I'll make the necessary changes and will publish this on Sunday.

**Comment by MichaelCurrin** [comment]
@ashmaroli Great, thank you. 

I didn't think `raw` and `highlight liquid` would work together but I had another go and got Liquid highlighting setup. If you want to switch to `highlight html` that can work too, but I can only get one _or_ the other two work at once.

I've pushed my changes and checked on the test URL. I am done making changes.

**Comment by MichaelCurrin** [comment]
Side note - I noticed that line height for the Liquid code blocks renders to short (vertically), when compared with other code blocks rendered using triple backticks, so maybe a CSS issue to bring up.

**Comment by DirtyF** [comment]
Thanks @MichaelCurrin 

@jekyll: merge +docs

**Pull request merged**
