### PR TITLE
Add configuration for DirectoryIndex setting

### PR DESCRIPTION
**Pull request by adborden**
Fixes https://github.com/jekyll/jekyll/issues/6348

### CODE REVIEW

**Comment by ashmaroli** [comment]
@adborden This is nice..!! But, I'd like to take this a bit further.
Currently, if you wanted to add `.json` to the list, you'd have to **list all the required extensions**, i.e. `"htm","html","rhtml","cgi","xml","json"` to restore original functionality.

So, I feel we can reduce the overhead by having the array in the config file **appended** to the default array already supported by Jekyll

**Comment by DirtyF** [comment]
Should `json` extension be also added to the default options?

**Comment by adborden** [comment]
Yes, you're right, but I think it's okay for users to enter the entire list, after all, they know what index files they're using in the project. Plus the default list is documented.

Consider the alternative though, what if you wanted to reduce the default list to only "html"? There wouldn't be a way to do it if the config only appended. What do you think?

**Comment by ashmaroli** [comment]
> what if you wanted to reduce the default list to only "html"?

I don't see the benefit of it..
Either ways, having such an option could be a double-edged sword.. (just my 2cents..)

Also, I understand that you used a comma-separated-string in sync with existing configuration for Markdown extensions, but wouldn't it be better to pass in an array of extensions directly, instead of having Jekyll *split* it out of a csv?

**Comment by pathawks** [comment]
> wouldn't it be better to pass in an array of extensions directly, instead of having Jekyll split it out of a csv?

👍

**Comment by parkr** [comment]
@adborden I'm thinking about the user experience here, and I think being exclusive is troublesome.

Imagine a user wants to do what you're doing: add "index.json" to the list. They go to set `directory_index_exts: "json"` and run `jekyll serve`. Dang! Their site's broken and they have no idea why. They do some research online, maybe find this PR, and discover only there that it overrides the defaults.

I think that's a bad user experience because it doesn't feel expected. A web server should always serve at _least_ `index.html`, right? Isn't it a 20-year-old convention? I can see not wanting `.htm` or some of the others here, but we should at least show `index.html`. That seems like a requirement for calling something a web server.

If we did that, we'd take `Set.new(["html"]) | Set.new(site.config["directory_index_exts"])` instead of just the latter. We'd always guarantee `html` is in there. `index.cgi`? `index.xml`? Yeah, I don't think those are nearly as important as `index.html` here.

What do you think of always guaranteeing `index.html`? 

Regarding the configuration setting, we actually do funky things where we allow both strings and arrays, so `directory_index_exts: json,xml,erb` and `directory_index_exts: [json, xml, erb]` are identical (YAML reads the first as a String, the second as an Array of Strings). We could standardize the reading of those options so they work both ways. 🤷‍♂️ I think Arrays of Strings makes more sense because that's what the program wants to use, but I'm open to arguments about consistency (e.g. `markdown_exts` as a comma-separated string) and ease-of-use (e.g. users don't understand YAML so we should handle anything that looks like an Array, such as a comma-separated string).

**Comment by mattr-** [comment]
If the goal is just to be able to serve `index.json` along with other the index pages we already serve, could we go with the simpler option of just adding `index.json` to Jekyll's WEBrick configuration and skip adding the option for configuring new ones? 

This would require work from the GitHub Pages crew to add the same support but from the strictly Jekyll point of view, this satisfies the request for the functionality and is much simpler to implement.

Just my two cents. :smile:

**Comment by adborden** [comment]
If Github would be open to adding index.json to their configuration, I'm totally down for the simpler solution of just adding it to the WEBrick config.

Otherwise, I'm happy to force `html` to be included as per @parkr 's recommendation. I can also try adding dual support for arrays/strings.

Let me know if there's consensus and I'll push an update :)

**Comment by parkr** [comment]
@adborden Let's add `index.json` to the list here and I'll work on getting it supported in Pages. If we come up with a really good reason it shouldn't be supported, then we can at least have it here in dev environments and for folks running custom server setups.

👍 on adding `index.json` to the default list in lieu of customization.

**Comment by adborden** [comment]
Closing in favor of https://github.com/jekyll/jekyll/pull/6550

Thanks for the input, all!

**Pull request closed without merging**
