### PR TITLE
Update 07-assets.md

### PR DESCRIPTION
**Pull request by henryhu712**
## Summary

Use absolute path to make it clearer.

### CODE REVIEW

**Comment by ashmaroli** [comment]
@henryhu712 There is no need for the leading slash in either of the places you've changed.
The `_sass` directory is at the root of a Jekyll source directory, not at the root of the system directory..

**Comment by henryhu712** [comment]
@ashmaroli I agree with you. I promote the pull request because there is an expression of /assets/css/style.sass just previous it. The absolute and relative paths confused me. It needs to change another.

**Comment by ashmaroli** [comment]
> there is an expression of /assets/css/style.sass just previous it. The absolute and relative paths confused me

Let me make it clearer for you.
The two expressions are of different types. `/assets/css/style.sass` is an **URL** relative to the webserver root. `_sass/main.scss` is a **file path** relative to the Jekyll source directory.

The URL is usually "generated" points to the "generated file". The file path points to the "source file".

**Comment by henryhu712** [comment]
Thank you. How can I know they are url path or file path without your explanation?

**Comment by DirtyF** [comment]
All folders beginning with an underscore will not be copied in the destination folder, and thus will not become an URL.

**Pull request closed without merging**
