### PR TITLE
Update License

### LINKED ISSUE #5710: Copyright date in LICENSE
Before somebody submits the annual PR to update the copyright date in `LICENSE`, I just wanted to ask how that all works, legally.

Why do we say that TPW owns the copyright to Jekyll code from 2016 when his last commit was 2013?
When I contribute to Jekyll, do I transfer the copyrights to my contributions to TPW? Neither the license nor CONTRIBUTING says anything to that effect.

Would it be better to say that Jekyll’s copyright is owned by its contributors, or maybe all future contributions will be owned by GitHub?

Obviously I am not a lawyer, I just wanted to see if somebody smarter than I knew the answer, before we just blindly `date++`

(I also apologize for posting this as an issue. This is almost certainly not the place for this discussion, but I’m unsure where it _would_ belong)

### PR DESCRIPTION
**Pull request by DirtyF**
fix #5710 

Add Jekyll contributors, following @benbalter advice.

/cc @pathawks

### CODE REVIEW

**Comment by pathawks** [comment]
Thanks @DirtyF!

**Comment by ashmaroli** [comment]
:+1:  
Just a passing thought: Is it practical to use a footnote to link to a page that lists an array of all the contributors till date?

**Comment by pathawks** [comment]
> Is it practical to use a footnote…

It's just a text file – not Markdown, footnotes don't really exist, and we don't want to mess with the format of the file and risk not being detected by [**licensee**](https://github.com/benbalter/licensee)

**Comment by quiltbag** [comment]
@jekyllbot: merge +minor

**Comment by benbalter** [comment]
> risk not being detected by licensee

Anything after the date in the copyright line is assumed to be attribution, so there's no reason we couldn't do, e.g., `Jekyll Contributors, see https://github.com/jekyll/jekyll/graphs/contributors`.

**Pull request merged**
