### PR TITLE
no more invalid US-ASCII on lines 30 and 97

### PR DESCRIPTION
**Pull request by clorichel**
Avoiding errors on `jekyll serve`

```
# jekyll serve -H 0.0.0.0
Configuration file: /jekyll-offline-docs/site/_config.yml
Configuration file: /jekyll-offline-docs/site/_config.yml
            Source: /jekyll-offline-docs/site
       Destination: /jekyll-offline-docs/site/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
  Conversion error: Jekyll::Converters::Scss encountered an error while converting 'css/screen.scss':
                    Invalid US-ASCII character "\xE2" on line 30
jekyll 3.3.0 | Error:  Invalid US-ASCII character "\xE2" on line 30
```

And line 97 when 30 is adjusted...

---

Will be super usefull to have the doc offline while travelling, thank you for that guys 👍

### CODE REVIEW

**Comment by DirtyF** [comment]
@clorichel I haven't been able to reproduce this behavior on my configuration. Could you provide some context?

**Comment by zdroid** [comment]
@DirtyF Maybe he set a different charset, yet the PR is legit. It's wrong to use <code>&grave;</code> for apostrophes.

**Comment by clorichel** [comment]
@DirtyF sure!

- macOS Sierra 10.12.1
- with Docker Version 1.12.1 (build: 12133)

Get in your terminal:

```bash
git clone https://github.com/jekyll/jekyll.git
cd jekyll
docker run -it -p 4000:4000 --rm -w /jekyll -v $(pwd):/jekyll ruby:2.3 /bin/bash
```

This will connect you to the `/bin/bash` of a throwable `ruby:2.3` Docker container, mapping current directory `$(pwd)` to `/jekyll` in the container, setting `/jekyll` as the working directory in the container (so you don't have to `cd /jekyll` inside your container), automatically removing the container when it exits (`--rm`).

Then, within your Docker container:

```bash
gem install jekyll
bundle install
cd site
jekyll serve -H 0.0.0.0 # there you got the error
exit # automatically remove the container thanks to `--rm`
```

**Comment by DirtyF** [comment]
@clorichel thanks, looks like that's something @jekyll/core should be aware of.

**Comment by envygeeks** [comment]
@jekyllbot: merge +minor

**Comment by envygeeks** [comment]
Oh, hey @clorichel there is a conflict do you mind resolving it so we can merge? Thanks!

**Comment by parkr** [comment]
This is now `docs/_sass/_gridism.scss`. 😄

**Pull request merged**
