### PR TITLE
Allow documents to override output property in front-matter

### LINKED ISSUE #2956: `published:false` doesn't seem to work with collections?
Setting `published: false` still renders my collection. It seems as though neither that, nor setting `output: false`, will do what I want it to: not create a resulting file (for just one collection item).

### PR DESCRIPTION
**Pull request by alfredxing**
Allow documents to override the collection's `output` property in its front-matter. Fixes #2956. Should be a non-breaking change.

### CODE REVIEW

**Comment by mattr-** [comment]
@alfredxing one more rebase so it'll merge?

**Comment by parkr** [comment]
:shipit:

**Comment by alfredxing** [comment]
Awesome, I'll rebase once I get home from my vacation this afternoon!

**Comment by alfredxing** [comment]
Rebased & ready for :ship:

**Pull request merged**
