### PR TITLE
check if relative URL contains a colon

### LINKED ISSUE #2834: URL should validate output
Colons, for example, should not be allowed

https://github.com/jekyll/jekyll-paginate/issues/8

### PR DESCRIPTION
**Pull request by Crunch09**
fixes #2834 

screen shot 2016-07-08 at 20 35 47

### CODE REVIEW

**Comment by parkr** [comment]
Yes! Perfect! This LGTM. @jekyll/core, what say you?

**Comment by parkr** [comment]
@envygeeks do you want to take a look at this, or?

**Comment by envygeeks** [comment]
LGTM! :shipit:

**Comment by parkr** [comment]
@jekyllbot: merge +minor

**Comment by akoeplinger** [comment]
This breaks using URLs with colons in the jekyll-redirect-from plugin: https://github.com/jekyll/jekyll-redirect-from/issues/119

**Comment by icai** [comment]
I don't think this is a good idea which check including colons(:) or not.
should use blacklist(year, month...) with colons to check URL, but not `if sanitized_url.include?(":")`

https://github.com/jekyll/jekyll/issues/5261

**Pull request merged**
