### PR TITLE
Update troubleshooting documentation to include fix for issue with vendored gems

### PR DESCRIPTION
**Pull request by cchorn**
update to include an error for a jekyll build related to issues ...
https://github.com/jekyll/jekyll/issues/5267
https://github.com/jekyll/jekyll/issues/2938

### CODE REVIEW

**Comment by ashmaroli** [comment]
Looks good. 

(For the maintainers):
May i suggest editing the title to : 
_**Update Troubleshooting doc to include Issue #xxxx**_ ?

**Comment by parkr** [comment]
@jekyllbot: merge +site

**Comment by parkr** [comment]
Thank you!

**Comment by cchorn** [comment]
Thanks!

**Pull request merged**
