### PR TITLE
Do not output SmartyPants warnings

### PR DESCRIPTION
**Pull request by jekyllbot**
PR automatically created for @pathawks.

### CODE REVIEW

**Comment by pathawks** [comment]
Since the SmartyPants warnings will never be relevant to the user, and kramdown insists on warning that the output is not wrapped in an HTML block element, let's just not output kramdown warnings for SmartyPants.

**Comment by DirtyF** [comment]
No more warnings on Jekyll's website ❤️

**Comment by pathawks** [comment]
Fixed Rubocop's complaints.

**Comment by pathawks** [comment]
Nevermind. I know how to _fix_ this.

#6565

**Comment by Crunch09** [comment]
Thanks @pathawks !

**Pull request closed without merging**
