### PR TITLE
Update pagination.md

### PR DESCRIPTION
**Pull request by nicolewhite**
elsif -> elif

### CODE REVIEW

**Comment by mattr-** [comment]
Thanks for your contribution! :heart:

**Comment by envygeeks** [comment]
Why did this need to change to `elif`? Liquid uses Rubyism's and in Ruby `elsif` is it, and even the documentation for Liquid itself states that: https://docs.shopify.com/themes/liquid-documentation/tags/control-flow-tags#elsif-else

**Comment by nicolewhite** [comment]
Apologies, I thought it was a typo since all the examples I've seen use `elif`.

**Comment by envygeeks** [comment]
So elif works? If elif works then I have no complaints and carry on.

**Pull request merged**
