### PR TITLE
Minor updates and corrections

### PR DESCRIPTION
**Pull request by gep13**
- Corrected highlighting on multi-line sections
- Replace `cinst` with `choco install` for consistency

### CODE REVIEW

**Comment by parkr** [comment]
@gep13 Thanks! What is `cinst`? Is it the old way of writing `choco install`?

/cc @jekyll/windows If you wouldn't mind double-checking this, please! ❤️

**Comment by gep13** [comment]
>@parkr said...
@gep13 Thanks! What is cinst? Is it the old way of writing choco install?

Exactly that, yes.  `cinst` is being phased out, although it still works, in favour of `choco install`.

**Comment by parkr** [comment]
LGTM.

**Comment by parkr** [comment]
@jekyllbot: merge +site

**Comment by gep13** [comment]
@parkr thanks for getting this merged in! Out of curiosity, what are you guys using to power your bot?

**Comment by parkr** [comment]
@gep13 My pleasure! Our bot is a home-grown Go app that takes in webhook payloads and does stuff. Basically just glue around https://github.com/google/go-github

**Pull request merged**
