### PR TITLE
Fix broken link in resources

### PR DESCRIPTION
**Pull request by jordanthornquest**
`jordanthornque.st` should be `jordanthornquest.com`. That's been remedied!

### CODE REVIEW

**Comment by parkr** [comment]
Fixes #3437.

**Comment by parkr** [comment]
You must have very recently made this change – just today? It was fine just a couple hours ago.

**Comment by parkr** [comment]
Man, that resources page needs some cleaning.

**Comment by jordanthornquest** [comment]
Yuppers, I just changed it. Again, I apologize for the inconvenience!

**Comment by parkr** [comment]
No problem! Thanks for the pull. :)

**Comment by jordanthornquest** [comment]
Last time, I promise. I'm moving to a more blog-focused platform, so the url will be changing to `http://blog.jordanthornquest.com/post/119506660470/building-dynamic-navbars-in-jekyll`. Thanks again!

**Comment by parkr** [comment]
@jordanthornquest ok – just submit a PR when you're ready.

**Comment by jordanthornquest** [comment]
Yuppity. Sorry, not Jekyll :P

**Pull request merged**
