### PR TITLE
Fix state leakage in Kramdown test

### LINKED ISSUE #4250: Fix flaky test
Part of #4109 was an update to our tests for them. One seems to be flaking out somewhat frequently in Ruby 2.2:

```text
Finished tests in 114.908768s, 4.7255 tests/s, 7.9193 assertions/s.
Failure:
TestKramdown#test_: kramdown should render fenced code blocks with syntax highlighting.  [/home/travis/build/jekyll/jekyll/test/test_kramdown.rb:59]
Minitest::Assertion: Failed refutation, no message given
543 tests, 910 assertions, 1 failures, 0 errors, 0 skips
```

@envygeeks, know why that would sometimes not work?

### PR DESCRIPTION
**Pull request by spudowiar**
Fixes #4250, one occurence of #4617

### CODE REVIEW

**Comment by spudowiar** [comment]
@parkr can we have this merged ASAP?

**Comment by parkr** [comment]
@spudowiar Almost seems too easy! Thanks! :smile: Also, for the future, we all have to work at our own pace and it may take a few days to see something through. You're welcome to merge your commits into the other branch you're working on if they do indeed fix the problem. 

No Travis build was spawned for this. I'm going to run CI locally and confirm it all passes. I'll merge then.

**Comment by parkr** [comment]
@jekyllbot: merge +dev

**Comment by spudowiar** [comment]
Anyway, this shouldn't be necessary. Something somewhere is enabling Pygments for all the tests and we need to fix tests like that.

**Comment by envygeeks** [comment]
@spudowiar that's the plan with RSpec which I really need to finish up, it actually has a mocker for Jekyll that creates a completely clean state for each test so there is no leakage.  Thanks for the fix too!

**Pull request merged**
