### PR TITLE
Backport #7250 to 3.8.x

### PR DESCRIPTION
**Pull request by oe**
backport #7250

### CODE REVIEW

**Comment by ashmaroli** [comment]
> Not sure why neither Travis nor AppVeyor are responding...

There's an error in the configs.. `/*-stable/` is not a valid regexp..

**Comment by oe** [comment]
@ashmaroli I (think) I've fixed it on `master`, but AppVeyor doesn't have a branch limitation configuration option, does it?

**Comment by DirtyF** [comment]
> 856 tests, 1533 assertions, 0 failures, 0 errors, 3 skips

Tests are now passing, they were a few style offenses.

**Comment by ashmaroli** [comment]
> I (think) I've fixed it on `master`, but AppVeyor doesn't have a branch limitation configuration option, does it?

`backport-.*` is not needed actually.. but doesn't matter..
AppVeyor only builds `master` and `themes` branches..

**Comment by oe** [comment]
I'm going to merge this PR manually since branch protection needs Travis to pass before merging.

**Pull request merged**
