### PR TITLE
Forward-port: Add ExcerptDrop and remove excerpt's ability to refer to itself in Liquid

### PR DESCRIPTION
**Pull request by pathawks**
Merge #4907 into **master**

#4911

### CODE REVIEW

**Comment by pathawks** [comment]
Did I do it right? Should I do a separate PR to mirror each PR that needs to be ported forward?

**Comment by pathawks** [comment]
I was just using `cherry-pick`; is there a better way?

**Comment by pathawks** [comment]
> I was just using cherry-pick; is there a better way?

This is what interactive rebase was built for. Someday I will learn to use Git 😜

**Comment by parkr** [comment]
LGTM! @pathawks, would you mind rebasing on `master`? Conflicts :(

**Comment by parkr** [comment]
I can merge manually! Amazing.

**Pull request merged**
