### PR TITLE
Perform jekyll-paginate deprecation warning correctly.

### LINKED ISSUE #3393: Incorrect deprecation warning for jekyll-paginate gem
I’ve just updated to the latest build, and now getting this message:

```
Deprecation: You appear to have pagination turned on, but you haven't included the `jekyll-paginate` gem. Ensure you have `gems: [jekyll-paginate]` in your configuration file.
```

I'm not loading my Jekyll gems by listing them in my config file, but via the `:jekyll_plugins` Gemfile group, i.e.:

```ruby
group :jekyll_plugins do
  gem 'jekyll-archives'
  gem 'jekyll-assets'
  gem 'jekyll-paginate'
  gem 'jekyll-sitemap'
end
```

So this warning is incorrect. Is there a better way to test for the existence of `jekyll-paginate`?

### PR DESCRIPTION
**Pull request by parkr**
Fixes #3393 

Could you please try this out, @paulrobertlloyd?

### CODE REVIEW

**Comment by paulrobertlloyd** [comment]
Thanks for taking a look at this @parkr. Just tested this, but still getting the same deprecation message, sadly. Here is my [Gemfile](https://github.com/paulrobertlloyd/paulrobertlloyd.com/blob/5394aea187e83a39cc946b76db30c2783566562c/Gemfile) and [Jekyll config](https://github.com/paulrobertlloyd/paulrobertlloyd.com/blob/5394aea187e83a39cc946b76db30c2783566562c/config/jekyll.yml). These look correct, right? I also checked that I was using this fix branch. Hmmm…

**Comment by parkr** [comment]
@paulrobertlloyd Try this rev?

**Comment by paulrobertlloyd** [comment]
@parkr Bingo! That works as expected. Thank-you!

**Comment by parkr** [comment]
:dance:

**Pull request merged**
