### PR TITLE
Use the proper names

### PR DESCRIPTION
**Pull request by chrisfinazzo**
To me, it's still Mac OS X. Old habits die hard...

### CODE REVIEW

**Comment by envygeeks** [comment]
Well why didn't you change 1.9.1 to 2.0.0 too then? :smiling_imp:

**Comment by chrisfinazzo** [comment]
@envygeeks,

It's updated now, is this what you were looking for? Looking through `rbenv install --list` I don't see anything about a patch level, so I would assume this is correct...

**Comment by parkr** [comment]
:shipit:

**Comment by alfredxing** [comment]
:tada:

**Comment by envygeeks** [comment]
:heart:

**Pull request merged**
