### PR TITLE
Fix #4066: Move Convertible#render_liquid to using render!

### LINKED ISSUE #4066: Including a symlinked file in safe mode outputs the error to the rendered document, exits 0
## Steps to reproduce

1. Create an `index.html` file with the content:
  
    ```
    ---
    ---
    
    {% include foo.html %}
    ```

2. Make `_includes/foo.html` a symlink to a file outside your source directory

3. `jekyll build --safe`

## Expected

* Exit status > 0
* Red output to STDOUT with the text `Liquid error: The included file ‘_includes/foo.html’ should exist and should not be a symlink`
* `_site/index.html` should be blank

## Actual

* Exit status of 0 
* No error output
* `cat _site/index.html` returns:

    ```
   <p>Liquid error: The included file ‘/Users/benbalter/projects/jekyll-test/_includes/foo.html’ should exist and should not be a symlink</p>
   ```

(Note the full path, which we don't use elsewhere AFAIK).

I believe this to be a regression from 2.x to 3.x.

To note, the symlink file is properly *not* included.

### PR DESCRIPTION
**Pull request by envygeeks**
/cc @benbalter @fw42 @jekyll/core 
https://travis-ci.org/envygeeks/jekyll-symlink-test/builds/88182863

### CODE REVIEW

**Comment by fw42** [comment]
Thanks! :+1:

**Comment by fw42** [comment]
Should probably add a regression test for this

**Comment by parkr** [comment]
@fw42 great idea.

I found the errors in the templates helpful, too... But I guess terminal errors would be better because they'd break the build which is what we want when something goes wrong.

**Comment by parkr** [comment]
LGTM pending the regression test.

**Comment by envygeeks** [comment]
I'll add the test after I finish up with my other pull requests.

**Comment by benbalter** [comment]
Cowabunga

**Comment by envygeeks** [comment]
It took a while to write that test, it was crazy because I couldn't figure out why it wasn't getting output and it turned out there might be a slight bug in POSIX::Spawn::Child somewhere.

**Comment by fw42** [comment]
I would have just tested that `render_liquid` doesn't swallow exceptions, but I guess this works too

**Comment by envygeeks** [comment]
I considered that, but then I decided that we want the errors to bubble at the UX so tested it in Cucumber.

**Comment by parkr** [comment]
:shipit:

**Pull request merged**
