### PR TITLE
Trials with Nokogiri 1.11.x

### PR DESCRIPTION
**Pull request by ashmaroli**
https://github.com/sparklemotion/nokogiri/releases/tag/v1.11.0.rc1

### CODE REVIEW

**Comment by DirtyF** [comment]
### Profile Memory Allocation

```diff
- Total allocated: 424.44 MB (4021894 objects)
+ Total allocated: 405.37 MB (3544629 objects)
- Total retained:  19.78 MB (107009 objects)
+ Total retained:  19.77 MB (106547 objects)
```

**Comment by DirtyF** [comment]
@ashmaroli Why this minor update is considered as experimental.

**Comment by ashmaroli** [comment]
Because it is testing a pre-release version. The final release will be automatically installed by existing directives on `master`.

**Comment by DirtyF** [comment]
###  Profile Memory Allocation

```diff
--  Total allocated: 204.96 MB (1193919 objects)
--  Total retained:  40.77 MB (130586 objects)
++ Total allocated: 201.77 MB (1169763 objects)
++ Total retained:  40.76 MB (130449 objects)
```

**Comment by DirtyF** [comment]
I wonder if there's a cache dependency issue here, but the docs build looks faster:

### Profile Docs

```diff         
- done in 5.32 seconds.
+ done in 4.479 seconds.
```

**Comment by ashmaroli** [comment]
@DirtyF The third-party-repo will not use Nokogiri 1.11-prereleases because the third-party Gemfile is different.

**Comment by DirtyF** [comment]
So when do we drop support for 2.4? 😇

**Comment by ashmaroli** [comment]
> So when do we drop support for 2.4?

Ideally, when the need arises &mdash; when the codebase starts using a method or syntax introduced in Ruby 2.5.
But since Ruby 2.5 itself is slated to reach EOL this March, lets wait a bit more..

**Pull request closed without merging**
