### PR TITLE
Fix gem quote consistency on docs

### PR DESCRIPTION
**Pull request by akirataguchi115**
## Summary
Changed all documentation double quotes to single quotes. In some places there already was a use of single quotes and this is what Bundler suggests to use.

## Context
Documentation.

### CODE REVIEW

**Comment by mattr-** [comment]
:wave: Jekyll's style guide says to prefer double quotes over single quotes.

Rather than switch things to single quotes, would you be willing to switch things to double quotes instead?

**Comment by akirataguchi115** [comment]
Good to know! And yeah sure I'm willing to amend the commit to double quotes instead of single quotes instead. Could you link me the style guide first?

**Comment by mattr-** [comment]
.rubocop.yml in this repository are the rules. We don't have anything "officially" documented 😅

**Comment by akirataguchi115** [comment]
That's good enough documentation for me. I changed the single quotes to double quotes on all .md pages.

**Review by mattr- — APPROVED** [review]
Thanks!

@jekyllbot: merge +docs

**Comment by chmaynard** [comment]
Not sure if this is related, but the Jekyll docs site is no longer working correctly. See issues #9527 and #9528.

**Pull request merged**
