### PR TITLE
[ImgBot] optimizes images

### PR DESCRIPTION
**Pull request by ImgBotApp**
Hey there. I've just optimized all of your images. They are the same dimensions and quality as before, only they take up less space now.

*Total: 156.87kb -> 131.07kb (16.45%)

\docs\img\jekyll-sticker.jpg -- 114.17kb -> 111.83kb (2.05%)
\docs\img\jekylllayoutconcept.png -- 39.27kb -> 18.86kb (51.97%)
\test\fixtures\test-theme\assets\img\logo.png -- 3.43kb -> 0.38kb (89.04%)

### CODE REVIEW

**Comment by pathawks** [comment]
Could somebody review this to make sure the images are _actually_ the same quality as before? Need to make sure no color profiles have been lost or anything.

I am inclined to keep `docs\img\jekyll-sticker.jpg` as is, since the savings is so small, and JPEG recompression can be lossy, and there are no details given in this PR about the process used to compress the images.

**Comment by pathawks** [comment]
https://github.com/dabutvin/ImgBot/issues/26

**Comment by dabutvin** [comment]
@pathawks ImgBot uses [Imagemagick](http://www.imagemagick.org) to optimize images through the `LosslessCompress()` routine from the The .NET wrapper [Magick.NET](https://github.com/dlemstra/Magick.NET).

That image in https://github.com/dabutvin/ImgBot/issues/26 is the only case I've seen so far of any color issue like that and I've just opened an issue with ImageMagick to see if we can track down why. 
https://github.com/dlemstra/Magick.NET/issues/124

I understand you may want to keep some images from being optimized.  This is why ImgBot offers an ignore option

```
// .imgbotconfig
{
    "ignoredFiles": [
        "jekyll-sticker.jpg"
    ]
}
```

see https://github.com/dabutvin/imgbot#configuration

**Comment by dabutvin** [comment]
FYI
There has been some progress on the the jpeg issue
https://github.com/dlemstra/Magick.NET/issues/124

**Comment by parkr** [comment]
This is so cool!!!!! Folks on high latency & low bandwidth connections are going to love this. We could optimize more (like our fonts being custom slowing things down & so on) but this represents a big reduction in bandwidth that’s a huge win for the average visitor :smile:

**Comment by DirtyF** [comment]
@jekyllbot: merge +site

I'll replace the sticker image with more lighter one.

**Comment by pathawks** [comment]
Did somebody check to make sure the images are actually lossless?

**Comment by envygeeks** [comment]
There is no way you can achieve an 89.4% reduction in size on lossless compression unless that image had so much metadata and junk from it's image writer that stripping that reduced the size significantly.

**Comment by parkr** [comment]
They were generated with Adobe software, so it’s always possible there was that much bloat :joy:

**Comment by dabutvin** [comment]
FYI ImageMagick.NET released a fix for the missing color profile in the JPEG Optimizer that is running in ImgBot now. 

see https://github.com/dlemstra/Magick.NET/commit/1725159e6a2ad4dacef4c54bcb7194e6c8b03d17

**Comment by pathawks** [comment]
The biggest thing that worries me is the difference between Lossless and anything in the category of “perceptually lossless.”

Just trying a thousand iterations of Gzip compression is cool, but once the actual image data is being changed it seems that a reviewer needs to inspect the image carefully in different browsers and devices.

But clearly I’m alone in this, so I’m probably just being paranoid.

**Comment by dabutvin** [comment]
@pathawks you're not alone :) we had a very similar conversation over here about the same thing https://github.com/dlemstra/Magick.NET/issues/124#issuecomment-342285405

Perceptually lossless vs actually lossless. 

For the most general scenario of releasing something like a website i think perceptually lossless is all that matters and is actually ideal. 

That being said, because images cut across so many different mediums and concepts in software, there is likely a segment where this would be an important distinction and offering options and configuration is going to be important in these cases.

**Pull request merged**
