### PR TITLE
Use a real theme in the example

### PR DESCRIPTION
**Pull request by jekyllbot**
Following https://github.com/jekyll/jekyll/issues/7047#issuecomment-404138910

Is it more clear @nheirbaut?

### CODE REVIEW

**Comment by DirtyF** [comment]
@kenman345 We use an existing theme to show how to change theme, but you better pick a non-existing name when you create a new theme.

**Comment by kenman345** [comment]
Understood, Maybe we should make that more clear in the documentation then.

**Comment by nheirbaut** [comment]
@jekyllbot Looks good to me. Thank you for the fast response.

**Comment by DirtyF** [comment]
@jekyllbot: merge +docs

**Comment by nheirbaut** [comment]
@ashmaroli In that case: thanks @DirtyF and you too.

**Pull request merged**
