### PR TITLE
Update 2019-08-19-jekyll-4-0-0-released.markdown

### PR DESCRIPTION
**Pull request by XhmikosR**
Fix minor typo

### CODE REVIEW

**Comment by XhmikosR** [comment]
Try again. There's a typo "it's".

**Comment by DirtyF** [comment]
https://english.stackexchange.com/questions/76337/its-as-a-possessive-pronoun

**Comment by XhmikosR** [comment]
Yes, exactly. `it's front matter` means it is front matter. Hence this patch.

**Comment by DirtyF** [comment]
@XhmikosR I don't know how I manage to think you were suggesting the opposite 😄

**Pull request merged**
