### PR TITLE
Cache Convertible#to_liquid

### PR DESCRIPTION
**Pull request by larryfox**
So we were evaluating Jekyll's performance under various circumstances, and one test case that raised a red flag was a site with 1000 posts, where each page contains a list of all posts. Hopefully unlikely in the real world but our current system performed much better. I did some digging, and was led to `Convertible#to_liquid`.

This patch memoizes the return value of `to_liquid` in a hash key'd by the attributes passed to `to_liquid`. The gotcha is that `to_liquid` is generally called as an [argument for `do_layout`](https://github.com/jekyll/jekyll/blob/80f63949cd79ab55bc39500b4f8a688d6c31a582/lib/jekyll/post.rb#L273) and `do_layout` [calls `content=`](https://github.com/jekyll/jekyll/blob/80f63949cd79ab55bc39500b4f8a688d6c31a582/lib/jekyll/convertible.rb#L246-L247), so the entire cache has to be reset or content with liquid would remain unrendered. So I reset the cache at the beginning of `do_layout`.

All test's pass, and the speed improvements for complex liquid layouts are great, but it might want a once over by someone more familar with the inner workings of Jekyll.

**Runtime of our complex site before**

```bash
$ time be jekyll build
            Source: jekyll
       Destination: jekyll/_site
 Incremental build: enabled
      Generating...
                    done in 168.475 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
bundle exec jekyll build -s   167.49s user 1.28s system 99% cpu 2:49.51 total
```

**Runtime of our complex site after**

```bash
$ time be jekyll build
            Source: jekyll
       Destination: jekyll/_site
 Incremental build: enabled
      Generating...
                    done in 32.063 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
bundle exec jekyll build -s   31.75s user 0.76s system 98% cpu 33.148 total
```

Building off the naive comparason in #3693, here's the runtime for Jekyll's site.
Maybe a slight improvement, but no apparent regresion.

```bash
$ time be jekyll build -s site
Configuration file: site/_config.yml
            Source: site
       Destination: _site
 Incremental build: enabled
      Generating...
                    done in 3.859 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
bundle exec jekyll build -s site  4.34s user 0.25s system 99% cpu 4.592 total

$ mv _site _site_master
$ rm -rf **/.jekyll-metadata
$ git checkout cache-convertible-to_liquid
$ time be jekyll build -s site
Configuration file: site/_config.yml
            Source: site
       Destination: _site
 Incremental build: enabled
      Generating...
                    done in 3.276 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
bundle exec jekyll build -s site  3.78s user 0.25s system 100% cpu 4.030 total

$ diff -r _site/feed.xml _site_master/feed.xml
14,15c14,15
<     <pubDate>Wed, 10 Jun 2015 11:19:59 -0400</pubDate>
<     <lastBuildDate>Wed, 10 Jun 2015 11:19:59 -0400</lastBuildDate>
---
>     <pubDate>Wed, 10 Jun 2015 11:18:10 -0400</pubDate>
>     <lastBuildDate>Wed, 10 Jun 2015 11:18:10 -0400</lastBuildDate>
```

And here's some profiling from rendering the Jekyll site before and after.

**RubyProf Before**

```
Measure Mode: wall_time
Thread ID: 70249865331160
Fiber ID: 70249856863080
Total: 3.480446
Sort by: self_time

 %self      total      self      wait     child     calls  name
  4.67      0.218     0.162     0.000     0.056    12231  *Hash#each_key
  3.48      0.150     0.121     0.000     0.029       92  *Kernel#load
  3.37      1.312     0.117     0.000     1.195    46919  *Array#map
  3.27      0.114     0.114     0.000     0.000   341260   Kernel#is_a?
  2.95      0.103     0.103     0.000     0.000    35697   Symbol#to_proc
  2.23      0.078     0.078     0.000     0.000    25317   <Class::File>#join
  2.19      0.126     0.076     0.000     0.050    11677   Array#index
  2.08      0.072     0.072     0.000     0.000    61278   String#to_s
  1.76      0.061     0.061     0.000     0.000    33206   Kernel#class
  1.51      0.373     0.052     0.000     0.321    17764   Jekyll::Post#relative_path
  1.44      0.061     0.050     0.000     0.011    18492   Array#reject
  1.42      0.050     0.050     0.000     0.000   233790   BasicObject#equal?
  1.09      0.038     0.038     0.000     0.000     5839   <Class::Hash>#[]
  1.06      0.510     0.037     0.000     0.473    24369  *Class#new
  1.01      0.186     0.035     0.000     0.151    17582   Hash#fetch
  1.00      0.044     0.035     0.000     0.009    89793   Kernel#respond_to?
  0.99      0.034     0.034     0.000     0.000    19504   <Class::Thread>#current
  0.90      0.040     0.031     0.000     0.008    18777   Liquid::Context#increment_used_resources
  0.88      0.078     0.031     0.000     0.047    15481  *Kernel#dup
  0.86      0.077     0.030     0.000     0.047    11812   Jekyll::FrontmatterDefaults#valid_sets
  0.84      0.029     0.029     0.000     0.000    13990   Hash#initialize_copy
  0.82      0.029     0.029     0.000     0.000        6   <Module::Marshal>#load
  0.81      0.068     0.028     0.000     0.039    18772   <Class::Liquid::Profiler>#current_profile
  0.76      0.026     0.026     0.000     0.000    12313   String#=~
  0.75      0.125     0.026     0.000     0.099    11812   Jekyll::FrontmatterDefaults#matching_sets
  0.75      0.067     0.026     0.000     0.041     9477   Array#each_index
  0.73      0.300     0.026     0.000     0.274    11971  *Jekyll::Utils#deep_merge_hashes
  0.73      0.025     0.025     0.000     0.000    25327   StringScanner#scan
  0.70      0.024     0.024     0.000     0.000    11761   <Class::File>#dirname
  0.69      0.024     0.024     0.000     0.000     8225   String#sub
  0.68      0.027     0.024     0.000     0.004    12361  *Array#select
  0.67      0.038     0.023     0.000     0.015    17556   Jekyll::Post#url
  0.65      1.441     0.023     0.000     1.418     5834   Jekyll::Convertible#to_liquid
```

**RubyProf After**

```
Measure Mode: wall_time
Thread ID: 70316898779600
Fiber ID: 70316898748640
Total: 2.171760
Sort by: self_time

 %self      total      self      wait     child     calls  name
  5.60      0.149     0.122     0.000     0.027       92  *Kernel#load
  3.63      0.079     0.079     0.000     0.000    82969   String#hash
  2.58      0.056     0.056     0.000     0.000    33206   Kernel#class
  2.20      0.048     0.048     0.000     0.000   124500   Kernel#is_a?
  1.63      0.500     0.035     0.000     0.465    24445  *Class#new
  1.60      0.114     0.035     0.000     0.080     6265   Array#hash
  1.51      0.043     0.033     0.000     0.011    89793   Kernel#respond_to?
  1.49      0.032     0.032     0.000     0.000        6   <Module::Marshal>#load
  1.44      0.031     0.031     0.000     0.000    19504   <Class::Thread>#current
  1.36      0.038     0.029     0.000     0.009    18777   Liquid::Context#increment_used_resources
  1.27      0.063     0.028     0.000     0.035    18772   <Class::Liquid::Profiler>#current_profile
  1.25      0.027     0.027     0.000     0.000    25327   StringScanner#scan
  1.14      0.025     0.025     0.000     0.000    12313   String#=~
  1.08      0.064     0.023     0.000     0.041     9477   Array#each_index
  1.04      0.029     0.023     0.000     0.006     7835  *Array#join
  0.98      0.235     0.021     0.000     0.213     7451   Liquid::Context#find_variable
  0.94      0.020     0.020     0.000     0.000     1160   StringScanner#scan_until
  0.89      0.019     0.019     0.000     0.000      419   <Class::IO>#read
  0.83      0.018     0.018     0.000     0.000    11711   Array#last
  0.73      0.016     0.016     0.000     0.000    18772   Liquid::Context#resource_limits_reached?
  0.72      0.016     0.016     0.000     0.000     3677   String#gsub
  0.69      0.022     0.015     0.000     0.007    14343   Liquid::Context#lookup_and_evaluate
  0.67      0.185     0.014     0.000     0.171     5834   Jekyll::Convertible#to_liquid
```

**StackProf Before**

```
==================================
  Mode: object(100)
  Samples: 2111622 (0.00% miss rate)
  GC: 0 (0.00%)
==================================
     TOTAL    (pct)     SAMPLES    (pct)     FRAME
    215250  (10.2%)      215250  (10.2%)     Jekyll::Post#relative_path
   3879419 (183.7%)      109376   (5.2%)     Liquid::Block#render_all
    512583  (24.3%)       93150   (4.4%)     Jekyll::Convertible#to_liquid
    308594  (14.6%)       81482   (3.9%)     block in Jekyll::Convertible#to_liquid
     57666   (2.7%)       57666   (2.7%)     Liquid::Variable#taint_check
     55219   (2.6%)       54475   (2.6%)     Liquid::VariableLookup#initialize
   1418636  (67.2%)       49876   (2.4%)     block (2 levels) in Liquid::For#render
     42573   (2.0%)       42573   (2.0%)     Liquid::Lexer#tokenize
    514631  (24.4%)       42256   (2.0%)     Liquid::Block#parse
```

**StackProf After**

```
==================================
  Mode: object(100)
  Samples: 1613892 (0.00% miss rate)
  GC: 0 (0.00%)
==================================
     TOTAL    (pct)     SAMPLES    (pct)     FRAME
   2380943 (147.5%)      109376   (6.8%)     Liquid::Block#render_all
     57666   (3.6%)       57666   (3.6%)     Liquid::Variable#taint_check
     55219   (3.4%)       54475   (3.4%)     Liquid::VariableLookup#initialize
    923900  (57.2%)       49876   (3.1%)     block (2 levels) in Liquid::For#render
     42573   (2.6%)       42573   (2.6%)     Liquid::Lexer#tokenize
    514631  (31.9%)       42256   (2.6%)     Liquid::Block#parse
     40527   (2.5%)       40527   (2.5%)     #<Module:0x007fd5011f6228>.sanitized_path
     38377   (2.4%)       38377   (2.4%)     Kramdown::Utils::Html#escape_html
     55237   (3.4%)       37435   (2.3%)     Kramdown::Utils::Html#html_attributes
```

### CODE REVIEW

**Comment by envygeeks** [comment]
Hi, this sounds great but I have a few questions:

1. What version of Jekyll are you on?
2. Where is the cache busting? When I hear caching I want to bust it.
3. Where are the tests?

**Comment by larryfox** [comment]
1. Comparisons were all done against master.
2. The "cache busting" is on line [235](https://github.com/larryfox/jekyll/blob/fad91c041667b8589e260fd07fbe6124e271ac20/lib/jekyll/convertible.rb#L235).
3. This is just memoization of the existing method, what kind of tests would you like to see?

**Comment by envygeeks** [comment]
You changed something and regressions happen, refactors need to happen.  Your code does not ensure that a refactoring and reorganization of that class continues to hold what you expect to be true to a standard.  That's an edge that needs to be covered.

**Comment by parkr** [comment]
The speed update from this is amazing. I'd be interested in seeing this land before 3. If you can't do that, we'll consider it for a later iteration of Jekyll.

**Comment by larryfox** [comment]
I'll try finding some time this weekend to push this along.

**Comment by envygeeks** [comment]
:+1:

**Comment by envygeeks** [comment]
Any update on this @larryfox the window to get this into 3.0 is closing quickly.

**Comment by parkr** [comment]
This can always make it into a later release, like 3.1. It'd be nice for 3.0, but I'm not confident that the cache will be busted appropriately when regenerating.

**Comment by parkr** [comment]
I think the solution here is to use Liquid Drops so the only data that is generated is the stuff that is used. That alone should give us a huge performance benefit. Tracking here: #3224.

**Pull request closed without merging**
