### PR TITLE
Add an issue template for new issues

### PR DESCRIPTION
**Pull request by parkr**
What do you think of these questions? Based on https://github.com/benbalter/problem_child/issues/14

/cc @jekyll/core @benbalter

### CODE REVIEW

**Comment by parkr** [comment]
Let's start with this for now – feel free to submit a PR!

**Comment by envygeeks** [comment]
Since when the hell?

**Comment by parkr** [comment]
:smiley:

**Comment by parkr** [comment]
For anyone following along: https://github.com/blog/2111-issue-and-pull-request-templates

**Pull request merged**
