### PR TITLE
Allow profiling converters

### PR DESCRIPTION
**Pull request by ashmaroli**
With this, running `bundle exec jekyll build --profile` will output a table for Liquid and another table for every other converters

/cc @jekyll/build

### CODE REVIEW

**Comment by DirtyF** [comment]
Example output:

```
Liquid Rendering Profile
------------------------

Filename                                         | Count |    Bytes |  Time
-------------------------------------------------+-------+----------+------
_layouts/default.html                            |   125 | 3300.51K | 1.936
_includes/top.html                               |   126 |  385.20K | 1.521
_layouts/docs.html                               |    49 | 1087.38K | 1.329
_includes/docs_contents_mobile.html              |    49 |  141.35K | 0.617
_includes/docs_contents.html                     |    49 |  142.84K | 0.567
_includes/docs_option.html                       |    49 |  113.55K | 0.555
_includes/docs_ul.html                           |    49 |  129.01K | 0.515
_layouts/news.html                               |    67 | 1164.76K | 0.351
_includes/header.html                            |   125 |  166.29K | 0.207
_includes/news_item.html                         |     2 |  293.52K | 0.162
sitemap.xml                                      |     1 |   14.90K | 0.160
_includes/news_contents.html                     |    67 |  226.16K | 0.157
_includes/news_contents_mobile.html              |    67 |  473.58K | 0.157
feed.xml                                         |     1 |   41.62K | 0.113
news/index.html                                  |     1 |  157.77K | 0.096
_includes/section_nav.html                       |    49 |   21.80K | 0.093
_layouts/news_item.html                          |    65 |  159.10K | 0.089
news/releases/index.html                         |     1 |  136.23K | 0.085
_docs/history.md                                 |     1 |  223.20K | 0.073
_includes/mobile-nav-items.html                  |   125 |   37.43K | 0.049
_includes/primary-nav-items.html                 |   125 |   28.52K | 0.049
_layouts/tutorials.html                          |     6 |  123.85K | 0.048
_includes/analytics.html                         |   126 |  117.26K | 0.038
_includes/footer.html                            |   125 |   68.24K | 0.028
_layouts/error.html                              |     1 |    5.37K | 0.016
_docs/includes.md                                |     1 |    6.32K | 0.016
_includes/tutorials_contents_mobile.html         |     6 |    4.41K | 0.013
_includes/tutorials_contents.html                |     6 |    3.84K | 0.012
_posts/2014-03-27-jekyll-1-5-1-released.markdown |     1 |    1.09K | 0.012
_docs/collections.md                             |     1 |   11.78K | 0.009
_includes/section_nav_tutorials.html             |     6 |    2.52K | 0.009
_includes/tutorials_ul.html                      |     6 |    3.19K | 0.008
_includes/tutorials_option.html                  |     6 |    2.84K | 0.008
_includes/anchor_links.html                      |   126 |  127.97K | 0.006
_tutorials/convert-existing-site-to-jekyll.md    |     1 |   23.21K | 0.006
_includes/search/input.html                      |   125 |    9.03K | 0.006
_includes/search/script.html                     |   125 |   45.65K | 0.006
_docs/templates.md                               |     1 |   18.96K | 0.003
_tutorials/orderofinterpretation.md              |     1 |    6.55K | 0.003
_tutorials/navigation.md                         |     1 |   18.82K | 0.002
community/index.md                               |     1 |    3.96K | 0.002
_layouts/redirect.html                           |     7 |    3.32K | 0.002
_docs/permalinks.md                              |     1 |   13.38K | 0.002
_posts/2016-10-06-jekyll-3-3-is-here.md          |     1 |    5.04K | 0.002
_posts/2016-04-19-jekyll-3-0-4-released.markdown |     1 |    1.04K | 0.001
_posts/2017-03-09-jekyll-3-4-2-released.markdown |     1 |    1.73K | 0.001
_docs/structure.md                               |     1 |    6.82K | 0.001
_includes/docs_version_badge.html                |     5 |    0.48K | 0.001
robots.txt                                       |     1 |    0.04K | 0.001
_docs/configuration.md                           |     1 |   27.70K | 0.001


Markup Rendering Profile
------------------------
  Markdown Parser: kramdown

Filename                                                | Count |   Bytes |  Time
--------------------------------------------------------+-------+---------+------
_docs/history.md                                        |     2 | 589.08K | 1.239
_posts/2013-05-08-jekyll-1-0-1-released.markdown        |     2 |   2.52K | 0.515
css/screen.scss                                         |     2 |  69.20K | 0.278
_docs/plugins.md                                        |     2 | 138.03K | 0.133
_tutorials/convert-existing-site-to-jekyll.md           |     2 |  77.18K | 0.097
_tutorials/navigation.md                                |     2 |  98.86K | 0.078
_docs/configuration.md                                  |     2 |  88.23K | 0.076
_docs/themes.md                                         |     2 |  37.72K | 0.064
_docs/templates.md                                      |     2 |  52.89K | 0.048
_docs/permalinks.md                                     |     2 |  33.22K | 0.043
_docs/includes.md                                       |     2 |  31.01K | 0.042
_docs/collections.md                                    |     2 |  43.96K | 0.041
_docs/upgrading/0-to-2.md                               |     2 |  15.63K | 0.031
_docs/troubleshooting.md                                |     2 |  29.12K | 0.030
_tutorials/orderofinterpretation.md                     |     2 |  26.16K | 0.030
_docs/posts.md                                          |     2 |  35.84K | 0.029
_docs/deployment-methods.md                             |     2 |  29.96K | 0.029
_docs/contributing.md                                   |     2 |  24.08K | 0.029
_docs/continuous-integration/travis-ci.md               |     2 |  25.71K | 0.029
_docs/windows.md                                        |     2 |  31.52K | 0.028
_docs/upgrading/2-to-3.md                               |     2 |  19.96K | 0.028
_posts/2016-10-06-jekyll-3-3-is-here.md                 |     2 |  13.41K | 0.026
_posts/2013-05-06-jekyll-1-0-0-released.markdown        |     2 |   1.77K | 0.026
_docs/pagination.md                                     |     2 |  31.74K | 0.024
_posts/2016-07-26-jekyll-3-2-0-released.markdown        |     2 |   7.34K | 0.016
_docs/maintaining/merging-a-pull-request.md             |     2 |   8.92K | 0.015
_docs/variables.md                                      |     2 |  22.33K | 0.014
_docs/datafiles.md                                      |     2 |  19.48K | 0.014
_tutorials/custom-404-page.md                           |     2 |   7.26K | 0.013
community/index.md                                      |     2 |  10.35K | 0.013
_docs/quickstart.md                                     |     2 |   9.50K | 0.013
_docs/assets.md                                         |     2 |   8.72K | 0.013
_docs/installation.md                                   |     2 |  13.14K | 0.013
_docs/usage.md                                          |     2 |  11.70K | 0.013
_docs/github-pages.md                                   |     2 |  15.15K | 0.013
_docs/static_files.md                                   |     2 |   9.38K | 0.011
_docs/resources.md                                      |     2 |  12.36K | 0.011
_posts/2017-10-19-diversity-open-source.markdown        |     2 |  11.54K | 0.011
_docs/continuous-integration/circleci.md                |     2 |  11.49K | 0.011
_posts/2014-06-28-jekyll-turns-21-i-mean-2-1-0.markdown |     2 |   3.55K | 0.011
_posts/2017-06-14-jekyll-3-5-0-released.markdown        |     2 |   7.49K | 0.010
_posts/2017-03-09-jekyll-3-4-2-released.markdown        |     2 |   5.11K | 0.010
_posts/2014-05-06-jekyll-turns-2-0-0.markdown           |     2 |  10.72K | 0.009
_posts/2013-11-04-jekyll-1-3-0-released.markdown        |     2 |   3.92K | 0.009
_docs/pages.md                                          |     2 |   8.26K | 0.009
_docs/maintaining/triaging-an-issue.md                  |     2 |  10.18K | 0.009
_posts/2014-09-09-jekyll-2-4-0-released.markdown        |     2 |   4.10K | 0.009
_docs/maintaining/special-labels.md                     |     2 |   5.05K | 0.009
_posts/2017-03-21-jekyll-3-4-3-released.markdown        |     2 |   5.60K | 0.008
_posts/2014-08-10-jekyll-2-3-0-released.markdown        |     2 |   4.42K | 0.008

                    done in 14.827 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
```

**Comment by DirtyF** [comment]
> css/screen.scss                                         |     2 |  69.20K | 0.278

It seems to include Sass converter as well

**Comment by ashmaroli** [comment]
> It seems to include Sass converter as well

Yes.. every converter used by current site..

**Comment by ashmaroli** [comment]
@DirtyF can you post the profile output using `CommonMarker` as well.. (for comparison)? Thanks :smiley:

**Comment by DirtyF** [comment]
Example output with `jekyll-commonmark` plugin:

```sh
Liquid Rendering Profile
------------------------

Filename                                         | Count |    Bytes |  Time
-------------------------------------------------+-------+----------+------
_layouts/default.html                            |   125 | 3090.70K | 1.559
_layouts/docs.html                               |    49 |  949.86K | 1.337
_includes/top.html                               |   126 |  386.04K | 1.140
_includes/docs_contents_mobile.html              |    49 |  141.35K | 0.623
_includes/docs_option.html                       |    49 |  113.55K | 0.561
_includes/docs_contents.html                     |    49 |  142.84K | 0.559
_includes/docs_ul.html                           |    49 |  129.01K | 0.507
_posts/2014-03-27-jekyll-1-5-1-released.markdown |     1 |    1.09K | 0.476
_layouts/news.html                               |    67 | 1137.22K | 0.363
_includes/header.html                            |   125 |  166.29K | 0.205
_includes/news_contents.html                     |    67 |  226.16K | 0.168
_includes/news_contents_mobile.html              |    67 |  473.58K | 0.157
sitemap.xml                                      |     1 |   14.90K | 0.137
_includes/news_item.html                         |     2 |  275.27K | 0.128
feed.xml                                         |     1 |   36.28K | 0.119
_docs/history.md                                 |     1 |  223.20K | 0.105
_layouts/news_item.html                          |    65 |  149.82K | 0.096
news/index.html                                  |     1 |  148.49K | 0.086
_includes/section_nav.html                       |    49 |   21.80K | 0.086
news/releases/index.html                         |     1 |  127.26K | 0.059
_includes/mobile-nav-items.html                  |   125 |   37.43K | 0.050
_includes/primary-nav-items.html                 |   125 |   28.52K | 0.047
_includes/analytics.html                         |   126 |  117.26K | 0.039
_layouts/tutorials.html                          |     6 |   78.76K | 0.037
_includes/footer.html                            |   125 |   68.24K | 0.028
_includes/tutorials_contents.html                |     6 |    3.84K | 0.012
_includes/tutorials_contents_mobile.html         |     6 |    4.41K | 0.010
_docs/collections.md                             |     1 |   11.78K | 0.010
_layouts/error.html                              |     1 |    5.37K | 0.010
_includes/section_nav_tutorials.html             |     6 |    2.52K | 0.008
_includes/tutorials_ul.html                      |     6 |    3.19K | 0.008
_includes/anchor_links.html                      |   126 |  127.97K | 0.006
_includes/tutorials_option.html                  |     6 |    2.84K | 0.006
_includes/search/input.html                      |   125 |    9.03K | 0.006
_includes/search/script.html                     |   125 |   45.65K | 0.006
_tutorials/convert-existing-site-to-jekyll.md    |     1 |   23.21K | 0.005
_docs/templates.md                               |     1 |   18.96K | 0.003
_posts/2016-10-06-jekyll-3-3-is-here.md          |     1 |    5.04K | 0.002
_tutorials/orderofinterpretation.md              |     1 |    6.55K | 0.002
community/index.md                               |     1 |    3.96K | 0.002
_layouts/redirect.html                           |     7 |    3.32K | 0.002
_docs/permalinks.md                              |     1 |   13.38K | 0.002
_tutorials/navigation.md                         |     1 |   18.82K | 0.002
_docs/datafiles.md                               |     1 |    3.56K | 0.002
_includes/docs_version_badge.html                |     5 |    0.48K | 0.001
_docs/configuration.md                           |     1 |   27.70K | 0.001
_docs/themes.md                                  |     1 |   12.76K | 0.001
_docs/plugins.md                                 |     1 |   49.22K | 0.001
_posts/2013-06-07-jekyll-1-0-3-released.markdown |     1 |    0.82K | 0.001
_posts/2013-07-24-jekyll-1-1-1-released.markdown |     1 |    0.82K | 0.001


Markup Rendering Profile
------------------------
  Markdown Parser: CommonMark

Filename                                                             | Count |   Bytes |  Time
---------------------------------------------------------------------+-------+---------+------
css/screen.scss                                                      |     2 |  69.20K | 0.312
_posts/2013-05-06-jekyll-1-0-0-released.markdown                     |     2 |   1.75K | 0.077
_docs/history.md                                                     |     2 | 544.87K | 0.012
_tutorials/convert-existing-site-to-jekyll.md                        |     2 |  54.96K | 0.009
_docs/configuration.md                                               |     2 |  59.79K | 0.008
_docs/plugins.md                                                     |     2 | 109.82K | 0.002
_docs/themes.md                                                      |     2 |  29.27K | 0.001
_posts/2014-05-06-jekyll-turns-2-0-0.markdown                        |     2 |  10.30K | 0.001
_docs/templates.md                                                   |     2 |  40.39K | 0.001
_docs/collections.md                                                 |     2 |  26.03K | 0.001
_docs/continuous-integration/travis-ci.md                            |     2 |  16.80K | 0.000
_docs/deployment-methods.md                                          |     2 |  23.51K | 0.000
_tutorials/navigation.md                                             |     2 |  44.34K | 0.000
_posts/2016-07-26-jekyll-3-2-0-released.markdown                     |     2 |   6.76K | 0.000
_docs/maintaining/special-labels.md/#excerpt                         |     2 |   0.58K | 0.000
_docs/contributing.md                                                |     2 |  20.19K | 0.000
_docs/troubleshooting.md                                             |     2 |  20.38K | 0.000
_docs/continuous-integration/circleci.md                             |     2 |   7.52K | 0.000
_docs/windows.md                                                     |     2 |  20.70K | 0.000
_docs/upgrading/2-to-3.md                                            |     2 |  14.17K | 0.000
_docs/datafiles.md                                                   |     2 |   8.71K | 0.000
community/index.md                                                   |     2 |   9.80K | 0.000
_posts/2016-10-06-jekyll-3-3-is-here.md                              |     2 |  11.21K | 0.000
_docs/posts.md                                                       |     2 |  23.26K | 0.000
_docs/variables.md                                                   |     2 |  26.07K | 0.000
_docs/continuous-integration/buddyworks.md                           |     2 |   6.34K | 0.000
_docs/includes.md                                                    |     2 |  15.46K | 0.000
_docs/permalinks.md                                                  |     2 |  28.72K | 0.000
_posts/2013-11-04-jekyll-1-3-0-released.markdown                     |     2 |   3.22K | 0.000
_tutorials/orderofinterpretation.md                                  |     2 |  15.75K | 0.000
_docs/maintaining/merging-a-pull-request.md                          |     2 |   7.66K | 0.000
_docs/assets.md                                                      |     2 |   6.21K | 0.000
_docs/resources.md                                                   |     2 |  11.84K | 0.000
_docs/usage.md                                                       |     2 |   9.15K | 0.000
_docs/github-pages.md                                                |     2 |  12.50K | 0.000
_posts/2013-06-07-jekyll-1-0-3-released.markdown                     |     2 |   1.90K | 0.000
_docs/upgrading/0-to-2.md                                            |     2 |  11.85K | 0.000
_posts/2016-08-24-jekyll-admin-initial-release.markdown              |     2 |   3.88K | 0.000
_posts/2017-03-21-jekyll-3-4-3-released.markdown                     |     2 |   4.42K | 0.000
_posts/2017-10-19-diversity-open-source.markdown                     |     2 |  11.05K | 0.000
_posts/2013-05-08-jekyll-1-0-1-released.markdown                     |     2 |   2.33K | 0.000
_docs/pagination.md                                                  |     2 |  15.34K | 0.000
_docs/installation.md                                                |     2 |  10.72K | 0.000
_posts/2016-05-18-jekyll-3-1-4-released.markdown                     |     2 |   2.70K | 0.000
_docs/quickstart.md                                                  |     2 |   7.80K | 0.000
_posts/2017-03-02-jekyll-3-4-1-released.markdown                     |     2 |   8.40K | 0.000
_posts/2014-11-06-jekylls-midlife-crisis-jekyll-turns-2-5-0.markdown |     2 |   5.14K | 0.000
_tutorials/video-walkthroughs.md                                     |     2 |   6.19K | 0.000
_docs/maintaining/reviewing-a-pull-request.md                        |     2 |   7.77K | 0.000
_posts/2017-09-21-jekyll-3-6-0-released.markdown                     |     2 |   2.28K | 0.000

                    done in 11.769 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
```

**Comment by parkr** [comment]
Whoa, that's a lot of output. Could we combine the output?

I'd also love to see a total output for markdown and for liquid, so you'd see `kramdown: total 13s` or whatever.

**Comment by ashmaroli** [comment]
> Could we combine the output?

Don't see a clear route to that.. could lead to data clobbering..
What I can do is to split the output.. `--profile` remains as is but a new switch e.g. `--profile-markup` to output just the profiling from converters..

**Comment by parkr** [comment]
I don't think it needs to clobber the output. The profiler would be given different buckets for bytes & time, one for liquid, one for a given converter. Then you have two columns for each and a total at the bottom.

**Pull request closed without merging**
