### PR TITLE
Improve syntax-highlighting in documentation site

### PR DESCRIPTION
**Pull request by ashmaroli**
- This is a 🔦 documentation change.

## Summary

Most of the tokens generated by Rouge are colored `#ffffff` in the code-blocks in the documentation site. This pull request attempts to remedy this deficiency to a limited extent.

### CODE REVIEW

**Comment by DirtyF** [comment]
I don't see a huge difference, fine by me.

**Comment by DirtyF** [comment]
Much better 👍 
https://deploy-preview-8079--jekyllrb.netlify.com/docs/configuration/default/

Is this still  WIP?

**Comment by DirtyF** [comment]
@jekyll: merge +site

Thanks @ashmaroli 💄

**Comment by ashmaroli** [comment]
@DirtyF What is that lipstick emoji supposed to signify??

**Comment by DirtyF** [comment]
Thanks for making the site more beautiful (makeup) 😄

**Pull request merged**
