### PR TITLE
Add post_convert hook to modify HTML content before layout

### PR DESCRIPTION
**Pull request by ljcooke**
This is a 🙋 feature or enhancement.

## Summary

This adds a `post_convert` hook for plugins to modify the content _after_ converting to HTML but _before_ rendering the page layout.

## Context

Closes #7271

This was implemented in #4752 and #7271, but the feature specs were unfinished. I've rebased the changes onto `master` and fixed the feature specs.

See discussion in #4714 and #4752.

### CODE REVIEW

**Comment by ashmaroli** [comment]
Thank you for taking this feature to the finish line, @ljcooke 
I would like you to incorporate some additional changes though:
- It would be nice to have a debug log message output similar to the one for `pre_render` hooks
- There is no test covering the hook for `:documents`. Technically, it is the same for `:posts`, but would be better to have it for completion.

**Comment by ljcooke** [comment]
@ashmaroli Sounds good. 👍 Hopefully I'll find time to work on these changes tomorrow.

**Comment by ljcooke** [comment]
@ashmaroli I've made those changes. Ready for review again. :)

**Review by ashmaroli — APPROVED** [review]

**Comment by ashmaroli** [comment]
Once again, thank you very much @ljcooke :smiley:

**Comment by ljcooke** [comment]
Awesome, thanks @ashmaroli!

**Pull request merged**
