### PR TITLE
Add documentation for relative_url and absolute_url

### PR DESCRIPTION
**Pull request by parkr**
@benbalter @pathawks I can't *believe* I forgot this! Follow-up to #5399 for documentation.

screen shot 2016-09-23 at 2 27 23 pm

### CODE REVIEW

**Comment by parkr** [comment]
Oh! Forgot to /cc @jekyll/documentation on this. Slated for Jekyll 3.3.

**Comment by parkr** [comment]
@jekyllbot: merge +site

**Comment by QXSoftware** [comment]
The absolute_url is good, but it can only return **http** url. What about a **https** absolute_url ?

**Comment by pathawks** [comment]
> The absolute_url is good, but it can only return **http** url. What about a **https** absolute_url?

I'm not sure I understand. When does it _not_ return an **https** url?

**Pull request merged**
