### PR TITLE
Configuration: allow users to specify a collections.posts.permalink directly

### PR DESCRIPTION
**Pull request by parkr**
…instead of overwriting with permalink.

Duplicates #4753 for `master`, i.e. v3.2.

If you have a config file with

```yaml
permalink: date
collections:
  posts:
    output: true
    permalink: /blog/:title/
```

then Post permalinks will match `permalink` (i.e. `"/:categories/:year/:month/:day/:title:output_ext"`) instead of `collections.posts.permalink` (i.e. `"/blog/:title/"`)

I'd like to ship a 3.0.4 for this and push it out to GitHub Pages.

/cc @benbalter @jekyll/gh-pages @jekyll/core

### CODE REVIEW

**Comment by parkr** [comment]
Note to self: integration #4846 into this.

**Comment by benbalter** [comment]
Didn't review the code, but :+1: to the change.

**Comment by parkr** [comment]
Have to check that this was a part of 3.1.3...

**Comment by parkr** [comment]
Have to check that this was a part of 3.1.3...

**Comment by parkr** [comment]
Fixed in #4942.

**Pull request closed without merging**
