### PR TITLE
Wrap lines

### PR DESCRIPTION
**Pull request by chrisfinazzo**

### CODE REVIEW

**Comment by chrisfinazzo** [comment]
@jekyll/core,

In addition to the 301 error, I did see errors while running `rake test`...not sure if they are related. If it helps, I will post the output here.

[here]: https://circleci.com/gh/jekyll/jekyll/191

**Comment by envygeeks** [comment]
This is a superficial change.  Fix your editor so it can softwrap.  :-1:

**Comment by chrisfinazzo** [comment]
Ahem.

screen shot 2015-03-11 at 9 24 34 pm

**Comment by envygeeks** [comment]
I don't know what you were trying to prove but you just proved your editor has software so use it?

**Comment by chrisfinazzo** [comment]
It's still soft-wrapping lines, although I'm not sure how wide the guide is.

However, the last time I sent a PR from this branch, @parkr asked me to wrap at 80 characters. (#3396)

**Comment by parkr** [comment]
It's cool @envygeeks, i wanted it. It is superficial but it helps for conformance with the rest of the site.

**Comment by chrisfinazzo** [comment]
Stupid CircleCI. I don't remember at this point, but why was this added? Just seems like a pain in the butt when it comes to making changes, regardless of size.

**Comment by parkr** [comment]
Chris, can you please squash the merge commits and such?

I can disable it - it's meant to proof the website so when you make a change, we know the site still works.

**Comment by chrisfinazzo** [comment]
Will do. I'll probably squash everything in that group, especially considering that it's really one fix.

**Pull request merged**
