### PR TITLE
Remove configuration of theme sass files from Core

### PR DESCRIPTION
**Pull request by ashmaroli**
- I read the contributing document at https://jekyllrb.com/docs/contributing/
- This is a 🐛 bug fix.

## Summary

Configuring Sass from theme-gem should be handled by the bundled `jekyll-sass-converter` plugin

## Context

So that when the converter plugin chooses to drop support for `sass-ruby`, Jekyll wouldn't care..

## Requirements

- [x] Move the "configuring function" to `jekyll-sass-converter` plugin (https://github.com/jekyll/jekyll-sass-converter/pull/80)
- [x] `jekyll-sass-converter` ships a new version containing the "function"
- [x] Travis CI and AppVeyor Passes

### CODE REVIEW

**Comment by mattr-** [comment]
What can we do to get this fixed up? I'd still like to ship this for 4.0.

**Comment by DirtyF** [comment]
@jekyllbot: merge +fix

**Comment by ashmaroli** [comment]
This was waiting for `jekyll-sass-converter-2.0.0`.. Oh well, `¯\_(ツ)_/¯`

**Comment by DirtyF** [comment]
https://github.com/jekyll/jekyll-sass-converter/releases/tag/v2.0.0

**Comment by ashmaroli** [comment]
Thank you @DirtyF :tada: :smiley:

**Comment by DirtyF** [comment]
Thanks YOU @ashmaroli

**Pull request merged**
