### PR TITLE
Add Jekyll 3.6.0 release post

### PR DESCRIPTION
**Pull request by parkr**
Hey y'all! Let's get 3.6.0 out the door.

I'd like to also ask that this be my last minor release for a while. I'd like to give y'all the power to merge contributions you think are worthy and make releases without me. I have been at this for 4+ years and want to ensure the project outlives my involvement in it! I'd also like to give y'all the ability to add new committers by giving you the ability to add new people to various teams on the org. What do you think?

Thanks ❤️

### CODE REVIEW

**Comment by DirtyF** [comment]
> I'd like to also ask that this be my last minor release for a while

@parkr You're the very reason I contribute to Jekyll, I am no developer but you make me feel welcome here and I tried to help as I could because I know how much you give to this project and I believe that even if Jekyll is fast nine years old, and other modern SSG are raising, it still has a lot to offer.

While I can relate to the maintainer fatigue and you aiming at other personal goals in your life, I wonder how a project like Jekyll, relatively tight to GitHub would continue without any review from anyone from Github (after all Jekyll powers more than a million GitHub Pages). 

But as you are only mentioning minor releases, I guess it doesn't mean you're quitting the project yet. Anyway, it's important to say that your involvement in this project is greatly appreciated by the community and I think the least we can do is try to make you proud and try to live up to your standards. 

🔥 Fan the flames 🔥

**Comment by parkr** [comment]
❤️ @DirtyF ❤️ 

> I wonder how a project like Jekyll, relatively tight to GitHub would continue without any review from anyone from Github

We've come a long way in the last few years. GitHub runs Pages in a very isolated environment and there's much less need for such strict security review. Using `Jekyll.sanitized_path` and `Site#in_source_dir` and so on go a long way toward making the security review faster. You'll notice, on the other hand, that we haven't added many features – Jekyll hasn't done much innovating over the last year or so. Part of that comes from lack of a central philosophy, and part comes from not wanting to break things for people. We have a central philosophy now (https://jekyllrb.com/philosophy) and we have better and better tests both in Jekyll and in Pages to reduce the likelihood that things will break. I'd like to start seeing the Jekyll community experiment with new kinds of plugins or bringing first-class features into Jekyll core. I think contributors aren't convinced their PR's will be accepted, so they don't send them. I see tons of documentation PR's because you, @pup, and @pathawks been superb at reviewing them and merging them. I'd like that same enthusiasm to be translated to code changes. Part of the reason I'm so tired is because I have been making most of the code-related decisions for the past few years, which is a product of me not being willing to let go and let others make decisions like that. I've gotten past that now and would like to see Jekyll innovate. It's OK to break things every once in a while. My efforts are best placed in ensuring GitHub's millions of Pages sites don't break, so investing in testing and other work to ensure the experience is seamless and that no breakages get shipped to Pages is where I should be focusing. Open source code is best when the community is vibrant and brimming with possibility; I think giving the keys to the kingdom to more fantastic contributors so more contributions can be merged is the best way to bring that vibrance and sense of possibility to the community.

**Comment by ashmaroli** [comment]
@parkr Saddened to know that you won't likely be actively involved in maintaining the Jekyll codebase. Hope that you're able to recuperate (from the maintainer-fatigue) and invest your time and energy in contributing to the developer-community as a whole.

Hope that Jekyll doesn't stray too far from its core nature, now that the "keys have been handed over to the kingdom.."

Either ways, cheers to your time spent at Jekyll! Cheers to the next chapter you're starting..!
:clinking_glasses: :+1: :+1: :gift:

**Comment by Crunch09** [comment]
@parkr Thank you for all your hard work maintaining Jekyll in the last years!! ❤️ 🙇  I think you did a tremendous job as lead maintainer and i learned a lot from your reviews and commits 👍  Hope you find some rest and eventually come back!

> I think contributors aren't convinced their PR's will be accepted, so they don't send them.
FWIW i never felt that way and i hope everyone accepts that the decision to merge a PR is in the hands of the maintainers (for good reason!) and that there is still lots to learn from PR's that don't get accepted.

**Pull request merged**
