### PR TITLE
Test Travis on Windows

### PR DESCRIPTION
**Pull request by ashmaroli**
Trials to test Windows build on Travis

### CODE REVIEW

**Comment by pathawks** [comment]
Ruby is unsupported on Windows 😭😭😭

**Comment by ashmaroli** [comment]
:sob: :sob: :sob:

**Comment by DirtyF** [comment]
> The language 'ruby' is currently unsupported on the Windows Build Environment.
> Let us know if you'd like to see it: https://travis-ci.community/c/windows. Thanks for understanding!

**Comment by XhmikosR** [comment]
From my experience, AppVeyor seems to be faster in most cases. But unfortunately they don't have parallel builds in the free plan, which Travis has.

That being said, Windows on Travis is way in early stage...

On the other hand personally I was testing [Linux on AppVeyor](https://ci.appveyor.com/project/jdorfman/bootstrapcdn/builds/19454353) and it worked quite nicely. But the no parallel builds is quite important.

**Comment by DirtyF** [comment]
GitHub Actions now support Linux, Mac and Windows.

**Comment by DirtyF** [comment]
closing as Travis still does not support Ruby for Windows and that we're using GitHub Actions.

**Pull request closed without merging**
