### PR TITLE
Scan `assert_equal` methods and rectify any offenses with a custom Rubocop cop

### LINKED ISSUE #7107: assert_equal called with constant as `actual`
In several places in our tests, we call `assert_equal` with `expected` and `actual` swapped.

```ruby
assert_equal @affected.data["key"], "val"
```

I wonder if it would be possible to create a Rubocop cop that complains when the second parameter passed to `assert_equal` is clearly a constant.

### PR DESCRIPTION
**Pull request by ashmaroli**
Closes #7107 

- [x] Implement Cop
- [x] Initial Run with detected offenses &mdash; indirectly test if the cop works
- [x] Correct offenses with `--autocorrect, -a`
- [x] CI Passes 100% &mdash; indirectly test if the autocorrect aspect works properly

### CODE REVIEW

**Comment by kenman345** [comment]
Should we extend this for other assert statements and refute statements? 

I.e. `refute_match`, `assert_match`

**Comment by ashmaroli** [comment]
> Should we extend this for other assert statements and refute statements?
> 
> I.e. `refute_match`, `assert_match`

Do they have similar API? i.e., are they defined as `assert_match(expected, actual, msg=nil)
(I'll have to check)

**Comment by kenman345** [comment]
I will look but we also have `refute_equal` that most certainly follows the same pattern

**Comment by ashmaroli** [comment]
Apparently, they do have similar or same API..
https://apidock.com/ruby/MiniTest/Assertions/assert_match

**Comment by ashmaroli** [comment]
I dunno if we should have a Cop for every definition.. Might as well have a dedicated `gem` for it then.. :stuck_out_tongue:

**Comment by kenman345** [comment]
I think the idea of the cop is to ensure that we are consistent with a standard so at least refute_equal should follow for this cop and I’m indifferent about a secondary cop for matches assert or refutes if that’s deemed worthy of also being enforced

**Comment by ashmaroli** [comment]
Correct. And I agree completely.
`refute_equal` can be checked by extending this PR's cop a bit.

But all of that is beyond my authority. I'll defer to the Core maintainers
/cc @jekyll/core

**Comment by DirtyF** [comment]
> I dunno if we should have a Cop for every definition.. Might as well have a dedicated gem for it then.. 

A `rubocop-minitest` gem would be nice 🤖 💎

**Comment by ashmaroli** [comment]
> A `rubocop-minitest` gem would be nice

my thoughts exactly..

**Comment by kenman345** [comment]
Okay but does that mean do not merge this in and/or make the adjustments to make this work for all assert and refute methods that follow that pattern?

**Comment by kenman345** [comment]
Also note: [assert_same](https://apidock.com/ruby/v1_9_3_392/MiniTest/Assertions/assert_same) and [refute_same](https://apidock.com/ruby/v1_9_3_392/MiniTest/Assertions/refute_same) also have the same pattern as is in this cop.

If you want to make a gem for this stuff, I'm all for it. I would love to try and help with that but I think an autocorrect function from this cop handling these other methods as well could help clean up this repository in the meantime.

**Comment by DirtyF** [comment]
@jekyllbot: +dev

**Pull request merged**
