### PR TITLE
Fix the docs contents menu

### LINKED ISSUE #9527: [Docs]: The Jekyll Docs site is broken and always displays "Deployment" as the page heading.
[Quickstart](https://jekyllrb.com/docs/) displays the content of its page, but has "Deployment" as headline.

[Installation](https://jekyllrb.com/docs/installation/) displays the content of its page, but has "Deployment" as headline.

The same goes for all other pages in section docs, except the step-by-step tutorial.

In the [step-by-step tutorial](https://jekyllrb.com/docs/step-by-step/01-setup/) "Deployment" becomes the second headline.

And the last menu item in the right docs sidebar called "Deployment" has broken styling.

### PR DESCRIPTION
**Pull request by mattr-**
This is a 🐛 bug fix.

## Summary

Captures are static so we can't use one here otherwise the last page to
include the file is what wins due to the way include caching works
during generation.

## Context

Closes #9527

### CODE REVIEW

**Comment by heironimus** [comment]
When I apply this PR, the docs still show "Deployment" for all the headers

**Comment by heironimus** [comment]
If I completely revert [this commit](https://github.com/jekyll/jekyll/commit/55e993be2594e3bfbd71825fc4dbfbd6e5b0621c) it fixes this issue. I've added a comment there.

**Comment by velle** [comment]
> When I apply this PR, the docs still show "Deployment" for all the headers

Agree. If I manually remove `{%- capture item_html -%}` and `{%- endcapture -%}`, that does not fix it.

**Comment by mattr-** [comment]
The fact that it's broken is why it's still a draft PR 😄

There's a better fix available now though so I'll close this one out.

**Pull request closed without merging**
