### PR TITLE
Update structure.md

### PR DESCRIPTION
**Pull request by jaybe-jekyll**
Add in references to _data formats and extensions options of .csv, .json, etc., consistent with _docs/datafiles.md

### CODE REVIEW

**Comment by parkr** [comment]
Thanks! Not sure if you meant to remove the styling but unfortunately I don't believe the backticks work there for anything more than plain ol' backticks.

**Comment by envygeeks** [comment]
AFAIW all Markdown processors recognize '` as `<code>` because it's listed in the official page.

**Comment by pathawks** [comment]
I believe that, because it is listed inside a `<p>` tag, Markdown processors will ignore everything and just treat it as raw HTML, which is why the `<code>` tag was there.

**Comment by envygeeks** [comment]
I didn't even notice that, thanks for pointing that out.

**Comment by parkr** [comment]
Merged in 4c1427c. Thanks, @jaybe-jekyll

**Comment by jaybe-jekyll** [comment]
Thanks; in my haste I did not update to match existing styling; and it should match. Thanks!

**Pull request closed without merging**
