### PR TITLE
Jekyll views router plugin

### PR DESCRIPTION
**Pull request by nyufac**
Add link to my plugin in list

### CODE REVIEW

**Comment by envygeeks** [comment]
Why was the old one closed and a new one opened?

**Comment by nyufac** [comment]
Travis reported build failed, but i cannot figure out why.

**Comment by envygeeks** [comment]
Please do not do that, if a failure happens you can force push and rebuild or you can ping one of us and we can manually restart a test to see if it was a Travis fluke which happens on 2.1 randomly because of some reason we've not been able to figure out.

**Comment by nyufac** [comment]
Ok, sorry.

**Comment by parkr** [comment]
This lgtm! Thanks! :shipit:

**Pull request merged**
