### PR TITLE
Update usage.md re: _config.yml not reloaded during regeneration

### PR DESCRIPTION
**Pull request by jaybe-jekyll**
_config.yml not reloaded during automatic regeneration

### CODE REVIEW

**Comment by envygeeks** [comment]
Any reason for the brackets around `_config.yml`?

**Comment by jaybe-jekyll** [comment]
Purpose was to call out as special; i.e. code, file, path, etc. I modeled styling off of block below; I see now the brackets are being used for variables and directives and not files.

To style or not to style; that is the question. Let me know your thoughts and I'll adjust.

**Comment by envygeeks** [comment]
I'm not against it so I'll merge and if there are complaints we can go back and correct it.

**Comment by jaybe-jekyll** [comment]
Looking at where and how `_config.yml` has been referenced throughout the documentation, it is referenced as:

```html
<code>_config.yml</code>
```

I would prefer to adjust and recommit with consistent style and approach.

**Comment by envygeeks** [comment]
If you wish you can submit another pull and we can merge it without a history mark, otherwise I'll correct it later this afternoon after I get done working on some stuff.

**Pull request merged**
