### PR TITLE
Revert "Replace regex arg to :gsub with a string arg"

### PR DESCRIPTION
**Pull request by ashmaroli**
Reverts jekyll/jekyll#7189

### CODE REVIEW

**Comment by ashmaroli** [comment]
2 days.. n Utterson is still on vacation... :beach_umbrella:

**Comment by pathawks** [comment]
[Faster, but less than 1%](https://utterson.pathawks.com/fea85d185bd47ee73d48aa9e4b22dd5e5fef0857.html) 🤷‍♂️

**Comment by ashmaroli** [comment]
So, by inference, this PR ought to be closed..
But then again, :man_shrugging:

**Comment by oe** [comment]
Closing this PR then!

**Pull request closed without merging**
