### PR TITLE
Should this have the "Warning" label?

### PR DESCRIPTION
**Pull request by chrisfinazzo**

### CODE REVIEW

**Comment by parkr** [comment]
The entire section is called `Gotchas` so not sure if it makes sense here. :)

**Comment by chrisfinazzo** [comment]
I know, this is kind of iffy. I wonder if we really need an entire section, as there's only one item there (Just stop at 3). I put it out here because the consequences of not following this instruction in a Travis setup is so bad. The only other place I could see putting this would be under *Troubleshooting*, but I'm not sure it belongs there.

**Comment by parkr** [comment]
> I wonder if we really need an entire section, as there's only one item there (Just stop at 3).

:+1:

**Comment by parkr** [comment]
Can you also put the `highlight` in the body of that?

**Comment by chrisfinazzo** [comment]
Like this?

screen shot 2015-04-08 at 3 57 57 pm

That's...OK. I guess that's one way to do it. 😕

**Comment by parkr** [comment]
oh ew.

**Comment by parkr** [comment]
what does it look like now?

**Pull request merged**
