### PR TITLE
Migrate TravisCI jobs to GitHub Actions

### PR DESCRIPTION
**Pull request by ashmaroli**
## Background

Because TravisCI.org is shutting down, its web workers are being retired gradually and consequently jobs take ages to get queued and then run.
Migrating to TravisCI.com is an option but it is not entirely free even for FOSS projects &mdash; builds consume finite amount of minutes allotted per month.

## Summary

Use GH Actions to handle CI for Linux platform by running Jekyll's test suite on Rubies 2.5 and 2.7
Once everything is running as expected, TravisCI will only be running tests on JRuby and RuboCop-based script.

- Remove `.travis.yml` entirely
- Modify `workflows/ci.yml`
- Remove redundant badges from README document

### CODE REVIEW

**Comment by DirtyF** [comment]
> Also, we are fast approaching the end of a lengthy migration process from travis-ci.org to travis-ci.com, which was initially announced in 2018. This migration enables all accounts - including open source - to receive the benefits of new features and infrastructure improvements under a single platform. Open source accounts, as always, will be completely free under travis-ci.com.

**Comment by ashmaroli** [comment]
The following is from TravisCI Community Forum:
https://travis-ci.community/t/org-com-migration-unexpectedly-comes-with-a-plan-change-for-oss-what-exactly-is-the-new-deal/10567/7

> We will be offering an allotment of OSS minutes that will be reviewed and allocated on a case by case basis. Should you want to apply for these credits please open a request with Travis CI support stating that you’d like to be considered for the OSS allotment. Please include: Your account name and VCS provider (like travis-ci.com/github/[your account name] ) How many credits (build minutes) you’d like to request (should your run out of credits again you can repeat the process to…

**Review by DirtyF — APPROVED** [review]
Awesome!

**Comment by DirtyF** [comment]
@jekyllbot: merge +dev

**Pull request merged**
