### PR TITLE
Add collection support to the "post_url" tag

### PR DESCRIPTION
**Pull request by Mizumi**
These changes add very simplistic support for collections to the post_url tag, making it easier to link to files that reside within collections (in response to Jekyll issue #2540). ;D

Functionally, these changes cause the post_url tag to split the tag input parameter on all spaces. If the array generated by the split operation is exactly two elements long, the post_url tag will use the first element as the name of the collection and the second element as the document to find in the collection. If the array is not exactly two elements long, post_url will act as normal.

This is my first time playing around with the Jekyll source, so I'd be happy to have some feedback; I'm sure there's a better way to parse out multiple tag arguments, but split(" ") was the best I could find right now. It might also be reasonable to instead parse the incoming URL to see if it starts with a known collection name, and go from there.

### CODE REVIEW

**Comment by envygeeks** [comment]
Please add tests as this is unacceptable without tests. Thanks.

**Comment by Mizumi** [comment]
Ok, cool. I'll write up the tests when I get some time.

**Comment by parkr** [comment]
@Mizumi You can look forward to the `link` tag in 3.2! #4624

**Comment by Mizumi** [comment]
Awesome! Totally missed that one, thanks. ;D

**Pull request closed without merging**
