### PR TITLE
Update Jekyll on macOS (macos.md) and current ruby version to 3.1.3 in ruby.yml

### LINKED ISSUE #9194: [Docs]: Jekyll on macOS - Step 2: "Install chruby and the latest Ruby with ruby-install" Fails Due to Outdated Ruby Version in Doc
## Motivation

I followed the [Jekyll on macOS](https://jekyllrb.com/docs/installation/macos/) guide to install and run Jekyll for the first time earlier today. I restarted Terminal per the guide at the end of step 2 in the guide and got an error message saying "chruby: unknown Ruby: ruby-3.1.2" as shown below:

image

## Suggestion

To fix it, "echo "chruby ruby-**3.1.2**" >> ~/.zshrc" should be "echo "chruby ruby-**3.1.3**" >> ~/.zshrc" in step 2 in the [Jekyll on macOS](https://jekyllrb.com/docs/installation/macos/) guide.

When I updated the line in .zshrc, I was able to proceed and install Jekyll successfully.

image

### PR DESCRIPTION
**Pull request by masaki9**
This is a 🔦 documentation change.

 I've updated the current ruby version to 3.1.3 in ruby.yml to update the ruby version referenced in the [Jekyll on macOS](https://jekyllrb.com/docs/installation/macos/) guide.

## Summary

Ruby version 3.1.3 was released yesterday, November 24, 2022, and step 2 in the [Jekyll on macOS](https://jekyllrb.com/docs/installation/macos/) guide currently references ruby version 3.1.2. The pull request change updates the current ruby version in ruby.yml to 3.1.3 from 3.1.2 to update the guide.

## Context

Fixes #9194

### CODE REVIEW

**Review by muzir — APPROVED** [review]

**Comment by postmodern** [comment]
I was just about to submit my own issue or PR about this. Additionally, the documentation should not recommend `ruby-install ruby` as that will install the current stable version, which will soon be 3.2.0. If Jekyll requires ruby 3.1.x, then it should explicitly install it with `ruby-install ruby-3.1` or `ruby-install ruby-3.1.3`.

**Comment by masaki9** [comment]
@postmodern I appreciate your comment. I just updated the doc to use _ruby-install {{ site.data.ruby.current_version }}_. It should show _ruby-install ruby 3.1.3_ instead of _ruby-install ruby_. 

Ruby 3.2 was released on Dec 25, but I did not update the ruby version to 3.2 in ruby.yml as a few issues with ruby 3.2, such as #9231 and #9233 were reported for this project.

**Comment by ashmaroli** [comment]
@masaki9 Are you able to install gem `liquid-c` on Ruby 3.1.3?

**Comment by masaki9** [comment]
@ashmaroli I was able to install liquid-c on ruby 3.1.3 and macOS Monterey ver. 12.6, as shown in the attached screenshot. liquid-c does not seem to be causing any issues. My site is running fine with it. 

liquid-c

**Comment by ashmaroli** [comment]
> Is there any known issue with ruby 3.1.3 and liquid-c?

`liquid-c` failed to install on our CI running on **Linux (Ubuntu)**. Another user too reported being able to install successfully on **macOS**. So, until we get more input from the community, I'll see this as a *linux-only issue*.

**Comment by masaki9** [comment]
@ashmaroli You are right. I set up a Ubuntu system and attempted to install liquid-c on Ruby 3.1.3. It fails on Ubuntu with Ruby 3.1.3, but it is OK on Ruby 3.1.2. I opened an issue at https://github.com/Shopify/liquid-c.

This PR changes the Ruby version number to 3.1.3 in ruby.yml, which is used for macOS documentation and does not affect the Jekyll installation on Linux or your CI running Ubuntu. If you follow the [Jekyll on Ubuntu](https://jekyllrb.com/docs/installation/ubuntu/) guide, you will run `sudo apt-get install ruby-full` (which does not specify a Ruby version) and install Ruby 3.0.4 as of now.

Is your plan to wait till your CI works on Ruby 3.1.3?

**Review by ashmaroli — APPROVED** [review]

**Comment by ashmaroli** [comment]
Thank you @masaki9.
I was waiting for confirmation from the user-base that `liquid-c` fails to install on Linux / Ubuntu.
Now that you have provided the confirmation and got the ball rolling to have it addressed it source, this can be merged without further delay.

@jekyllbot: merge +doc

**Review by barbarita1975 — COMMENTED** [review]
Jc

**Pull request merged**
