### PR TITLE
Add reference to Liquid to plugin docs

### LINKED ISSUE #6793: Clarify Plugin Syntax / Missing docs?
Hi all,

I am having trouble writing my first Jekyll plugin, and I wonder if this is a gap in the documentation that should be addressed. The [plugin documentation](https://github.com/jekyll/jekyll/blob/master/docs/_docs/plugins.md) mentions this syntax for adding new tags, but does not explain any of the arguments:
```
    def initialize(tag_name, text, tokens)
      super
      @text = text
    end
```
- What is tag_name?
- What is text?
- What is tokens?

I would expect at least a word or two about the type and the intended contents.
Is this written down somewhere else?

PS: Thanks for making this! You guys rock.

### PR DESCRIPTION
**Pull request by HeinrichHartmann**
Fixes #6793

### CODE REVIEW

**Comment by HeinrichHartmann** [comment]
Messed up the Link syntax. Let me squash that real quick ...

**Comment by ashmaroli** [comment]
@HeinrichHartmann  Please the add he following in the PR's blank post:
```
Fixes #6793
```

**Comment by ashmaroli** [comment]
One more small request:
*Please ammend the commit message to not include the reference to `#6793`*:
```
Add reference to Liquid to plugin docs
```

**Comment by HeinrichHartmann** [comment]
All done. Sorry for the noise, ironed out a few more nits.

**Comment by HeinrichHartmann** [comment]
Cool. Happy merging!

**Comment by DirtyF** [comment]
Another useful link to ship jekyll gem plugins is https://ayastreb.me/writing-a-jekyll-plugin/

**Comment by ashmaroli** [comment]
> Another useful link to ship jekyll gem plugins

It's a good write-up, but I don't think it needs to be mentioned in the official docs..

**Comment by oe** [comment]
@jekyllbot: merge +docs

**Pull request merged**
