### PR TITLE
[docs] Info about the help command usage

### PR DESCRIPTION
**Pull request by DirtyF**
Help users getting help.

A reply to this feedback: https://github.com/jekyll/jekyll/issues/5260#issuecomment-243580868

/cc @jekyll/documentation, @stffndk

### CODE REVIEW

**Comment by DirtyF** [comment]
jekyll-help-command


LGTM 

What do you think @jekyllbot?

**Comment by stffndk** [comment]
I would love to see it added to the /quickstart/ page as well.

**Comment by parkr** [comment]
LGTM!

**Comment by admhlt** [comment]
Nitpick — how about:
> You can use the `help` command at any time to remind you of all available options and usage. It also works with...

That makes the sentence focus on the user and not the command.

**Comment by chrisfinazzo** [comment]
@stffndk By this, do you mean the same Information block? Would like to keep things DRY if possible.

Perhaps something like the following:

The `help` command is available to remind you of all available options and usage patterns. It also works in conjunction with the `build`, `serve`, and `new` subcommands, e.g, `jekyll help new` or `jekyll help build`.

**Comment by DirtyF** [comment]
@admhlt done.

@chrisfinazzo yeah, I was a bit relunctant too, but I inserted a slightly modified version less visible at the end of the quickstart page to give it a shot though. It can not hurt.

@parkr and we're good for another round of LGTM 😄

**Comment by chrisfinazzo** [comment]
@DirtyF Gotcha 👍🏻

**Comment by parkr** [comment]
👍 

LGTM!

**Comment by parkr** [comment]
@DirtyF Please fix the conflicts (you should be able to do it in your browser) then merge at will! Thanks!

**Comment by DirtyF** [comment]
@jekyllbot: merge +doc

**Pull request closed without merging**
