### PR TITLE
Add support for `*.xhtml` files

### PR DESCRIPTION
**Pull request by ExE-Boss**
This adds proper support for `*.xhtml` files when using `jekyll serve`.

### CODE REVIEW

**Comment by pathawks** [comment]
I haven't seen `.xhtml` actually used as an extension; only XHTML served with `.html` extension.

Can you describe why this change is needed?

**Comment by DirtyF** [comment]
This does not look like a 90% user case, I'm tempted to label this as a `wontfix`

**Comment by ExE-Boss** [comment]
`.xhtml` is the extension for [`application/xhtml+xml`](https://www.iana.org/assignments/media-types/application/xhtml+xml), whereas `.html` automatically denotes [`text/html`](https://www.iana.org/assignments/media-types/text/html). Because of this XHTML files won’t be served correctly as `application/xhtml+xml` without the `.xhtml` extension.

Also, GitHub Pages supports `.xhtml` correctly, while this doesn’t.

**Comment by pathawks** [comment]
> `.xhtml` is the extension for `application/xhtml+xml`

Where are you getting this information? I do not believe that is correct.

**Comment by pathawks** [comment]
I tend to agree with @DirtyF that this change wouldn't add value for the majority of our users, but if it brings the behavior of `jekyll serve` closer to that of GHP... 🤷‍♂️

/cc: @jekyll/stability

**Comment by oe** [comment]
One thing - this could have some tests, just to future-proof it.

**Comment by ExE-Boss** [comment]
@oe I’ve now implemented the tests (I actually kind‑of forgot about this until I checked my open PRs because [of this article I came across on Medium prompting readers to do so](https://medium.com/pnpm/why-package-managers-need-hook-systems-b8125d8b3dc7)).

**Comment by oe** [comment]
@jekyllbot: merge +minor

**Comment by oe** [comment]
@ExE-Boss Thank you for coming back to this!

**Pull request merged**
