### PR TITLE
#3392 copy page code from octopress-hooks

### PR DESCRIPTION
**Pull request by stevecrozz**
This commit adds support for all the page hooks from the octopress-hooks project

### CODE REVIEW

**Comment by envygeeks** [comment]
I'm definitely :-1: on this, encapsulate it.  I'm not a fan of skynet classes.

**Comment by envygeeks** [comment]
Would you be willing to encapsulate the hooks and then use that in the class?

**Comment by stevecrozz** [comment]
@envygeeks sure. In that case, I'd like to just disregard https://github.com/jekyll/jekyll/pull/3392 entirely which I was following along with and restart this effort. I'll close this one now and target my next PR to master.

**Comment by willnorris** [comment]
> I'm definitely :-1: on this, encapsulate it.  I'm not a fan of skynet classes.

@envygeeks: okay, just for my edification, what are "skynet classes"? :) I mean, I get the skynet reference, just not sure about the application here.

**Comment by envygeeks** [comment]
@willnorris A Skynet class (to me) is for example what people often do with service classes or models in Rails when they first start (I'm not saying you or @stevecrozz are new at Rails btw, it's just a great example,) they put everything into the same class instead of encapsulating concerns.  The class gets too smart and too big for itself and ends up figuratively killing it's master by killing development and takes over everything.

**Comment by willnorris** [comment]
got it :smile:  And I have zero experience with Rails (and very little with Ruby), so absolutely no offense taken.  All of my coding is in Go these days, so I'm happy to learn what it idiomatic in Ruby.

**Pull request closed without merging**
