### PR TITLE
Define path with __dir__

### PR DESCRIPTION
**Pull request by bogdanvlviv**
> ".. with \_\_dir\_\_ we can restore order in the Universe."

### CODE REVIEW

**Comment by bogdanvlviv** [comment]
@parkr Thank you for the review! I finally finished this PR.

**Comment by bogdanvlviv** [comment]
@parkr please review

**Comment by parkr** [comment]
@jekyllbot: merge +dev

**Comment by parkr** [comment]
Thank you, @bogdanvlviv! The consistency is wonderful.

**Comment by bogdanvlviv** [comment]
@parkr Thanks!

**Pull request merged**
