### PR TITLE
Lock to cucumber 3.0.1 on Ruby 2.1

### PR DESCRIPTION
**Pull request by ashmaroli**
Cucumber 3.0.2 has dropped support for Ruby 2.1

### CODE REVIEW

**Comment by DirtyF** [comment]
I"m all with @mattr and @pathawks we shouldn't patch to support a EOL Ruby version. Let's bump Jekyll to a major version and remove EOL Ruby dependencies.

**Comment by ashmaroli** [comment]
By the end of March 2018, even 2.2 will go EOL.. so I thinks its best we put off `4.0` till dependencies start to drop support for Ruby 2.2 as well.. or latest by May 2018..

**Comment by ashmaroli** [comment]
Cucumber is just a dev dependency.. much like `nokogiri`
https://github.com/jekyll/jekyll/blob/9c7ef8f14ecab04611517651936ad0d9fab65c6f/Gemfile#L30

**Comment by DirtyF** [comment]
> Cucumber is just a dev dependency.. much like nokogiri

So why do we need to lock the dev dependencies to Ruby < 2.2 exactly? (pardon my ignorance)

**Comment by ashmaroli** [comment]
> So why do we need to lock the dev dependencies to Ruby < 2.2 exactly? (pardon my ignorance)

so that our CI continues as usual, till the library code drops support for EOL ruby versions..

**Comment by pathawks** [comment]
> By the end of March 2018, even 2.2 will go EOL

Let's just say that 4.0 only supports >= 2.3, no matter when we release it. Problem solved.

**Comment by DirtyF** [comment]
@jekyllbot: merge +dev

**Pull request merged**
