### PR TITLE
Added title tag to Twitter SVG icon

### PR DESCRIPTION
**Pull request by HugoGiraudel**
I think it would be good for accessibility to add a `<title>` tag to the SVG icons. Here is one for the Twitter logo.

### CODE REVIEW

**Comment by DirtyF** [comment]
@HugoGiraudel FYI you can also help improve https://github.com/jekyll/minima the future Jekyll default theme

**Comment by HugoGiraudel** [comment]
Ah, good to know! :)

**Comment by envygeeks** [comment]
/cc @jglovier @parkr does this come from an upstream somewhere?
I'm :shipit:

**Comment by parkr** [comment]
Please submit this to `jekyll/minima` as @DirtyF mentioned. 😄

**Pull request closed without merging**
