### PR TITLE
Update rake task site:publish to fix minor bugs.

### PR DESCRIPTION
**Pull request by flyinprogrammer**
*  Automate creating gh-pages directory
*  Ensure gh-pages dir always has correct branch checked out
*  Purge gh-pages of files so that a sync of site truly occurs
*  Ensure dot files are synced
*  Be exact with our exclusions to eliminate guess work

### CODE REVIEW

**Comment by flyinprogrammer** [comment]
This will ensure the latest .gitignore from 'site' is copied, and that README and _sass/.sass-cache/89a83dca448ff37810b0714f8b03e869032bdae6/normalize.scssc are removed from gh-pages.

We might consider adding '.jekyll-metadata' to .gitignore, not sure though. :neutral_face:

**Comment by parkr** [comment]
Very thorough work. Thank you!

**Comment by penibelst** [comment]
@flyinprogrammer Why didn’t you use `Rake::FileList#exclude`?

**Comment by flyinprogrammer** [comment]
@penibelst - Well, haha, truth be told I didn't know Rake had a FileList helper. Since this was my first commit to this project I was focusing on keeping the code simple and consistent with patterns that were in place.

Personally I've always used Dir.glob, but I see no reason why FileList could not be used. I'd be more than happy to submit another pull request using FileList if you'd like.

**Pull request merged**
