### PR TITLE
deprecator.rb: fix typo for --serve command

### PR DESCRIPTION
**Pull request by ashmaroli**
Mostly a personal preference, not sure how it affects overall performance

/cc @pathawks

### CODE REVIEW

**Comment by pathawks** [comment]
I don't mind, but it might be worth not making changes that would muddy `git blame`

**Comment by ashmaroli** [comment]
hmm, okay.. I'll use this PR to correct the typo and remove just the `\n` at towards the end of the file then.. k?

**Comment by ashmaroli** [comment]
Since jekyllbot doesn't squash and merge, I'll manually rebase once the new diff is approved..

**Comment by DirtyF** [comment]
@jekyllbot: merge +bug

**Comment by ashmaroli** [comment]
Well I'll be a....... JekyllBot does squash and merge.. Cool!
Thanks Frank :smiley:

**Comment by pathawks** [comment]
I forgot about that 😜👍🏼

**Pull request merged**
