### PR TITLE
Format config file for easy editing

### PR DESCRIPTION
**Pull request by ashmaroli**
This PR is to format _config.yml to increase readability and enable easy editing.

### CODE REVIEW

**Comment by envygeeks** [comment]
All this does is force me to look right.

**Comment by DirtyF** [comment]
If you want to make it easier to scan, properties should be right aligned:
http://uxmovement.com/forms/form-label-proximity-right-aligned-is-easier-to-scan/

That's what @envygeeks expressed. Sorry but it's a 👎  for me on this one.

**Comment by mdxprograms** [comment]
I'm ok with it as is. I don't think reading a config file is that difficult in the first place. Especially using YAML.

**Comment by mdxprograms** [comment]
👎 for me

**Comment by mattr-** [comment]
Thanks for the edits. I can understand your point of view. We'll keep the file as is though.

**Comment by ashmaroli** [comment]
Thank you all for your feedback.

**Pull request closed without merging**
