### PR TITLE
Attain Ruby 3.0 compatibility

### LINKED ISSUE #7947: warning: Using the last argument as keyword parameters is deprecated (Ruby 2.7.0)
## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System |     macOS       |
| `jekyll`         | Latest     |
| `ruby`   | Latest     |

---

## Expected Behaviour

No warnings output when generating jekyll website with Ruby 2.7.0

## Current Behavior

```
bundle exec rake site:generate

/code/jekyll/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/code/jekyll/lib/jekyll/document.rb:466: warning: Using the last argument as keyword parameters is deprecated
/code/jekyll/lib/jekyll/document.rb:432: warning: Passing the keyword argument as the last hash parameter is deprecated
/code/jekyll/lib/jekyll/document.rb:75: warning: The called method `merge_data!' is defined here
/code/jekyll/lib/jekyll/document.rb:439: warning: Passing the keyword argument as the last hash parameter is deprecated
/code/jekyll/lib/jekyll/tags/include.rb:179: warning: Using the last argument as keyword parameters is deprecated
```

For more explanation on what is deprecated, see https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/

### PR DESCRIPTION
**Pull request by ashmaroli**
So that Ruby 2.7 doesn't issue warnings for deprecated use of keyword arguments

fix #7947

### CODE REVIEW

**Comment by ashmaroli** [comment]
The changes here are purely based on the warnings visible in the CI builds on `master`. I do not have Ruby 2.7 installed on my local machine and therefore cannot guarantee this to remove all possible deprecation warnings from the codebase.

**Comment by DirtyF** [comment]
@ashmaroli yay it does break Jekyll website: https://deploy-preview-7948--jekyllrb.netlify.com/resources/ (sidebar is missing)

**Comment by ashmaroli** [comment]
Nice catch @DirtyF !!
Looking into it right now..

**Comment by ashmaroli** [comment]
@DirtyF This is the same on `master` as well: https://jekyllrb.com/resources/

**Comment by DirtyF** [comment]
oh my god, we broke the website, I'll look into this.

**Comment by ashmaroli** [comment]
The sidebar is rendered only for `/docs/` and `/news/`..

**Comment by rayheffer** [comment]
Using this with Ruby 2.7.0-1 for Windows, and no warnings are showing. Working.

**Comment by ashmaroli** [comment]
@jekyllbot: merge +dev

**Comment by Ollymid** [comment]
@ashmaroli Using Jekyll 4.0 with Ruby 2.7.0 but I am getting loads of these warning messages when I run Jekyll serve
Screenshot 2020-02-10 at 13 39 06

Any advice? Is there something I've missed?

**Comment by ashmaroli** [comment]
@Ollymid This patch has not been released yet and will be included as part of Jekyll 4.1
Until then you can point your Gemfile to the `master` branch of this repo:
```diff
- gem "jekyll", "~> 4.0"
+ gem "jekyll", github: "jekyll/jekyll"
```

**Comment by Ollymid** [comment]
@ashmaroli thanks for clarification and for getting back to me so quickly

**Comment by IanLee1521** [comment]
Could this get added to the [Jekyll 4.1](https://github.com/jekyll/jekyll/projects/2) project for keeping track of it that it's fixed when that version lands?

**Comment by mattr-** [comment]
The best place to check if a version of Jekyll takes care of something
you're looking for is to check the history file when we release. I imagine
for something like Ruby 3 compatibility, we'll mention it in the release
blog post as well.

>

**Comment by DirtyF** [comment]
@ashmaroli If we are backporting fixes to 3.8, I'd definitely add this one.

**Comment by mattr-** [comment]
Yup. Should be fine.

**Pull request merged**
