### PR TITLE
Register reload hooks in Server#process

### PR DESCRIPTION
**Pull request by ashmaroli**
Resolves issue mention in https://github.com/jekyll/jekyll/pull/5142#issuecomment-349786108

Calling `:register_reload_hooks` in `#process` after the site starts to `generate...` instead of much earlier in the build-process..

/cc @awood

### CODE REVIEW

**Comment by DirtyF** [comment]
It works 👍 

port is displayed only if I had `"livereload_port" => 35_729,`, shouldn't it by the default?

**Comment by ashmaroli** [comment]
> port is displayed only if..

I see the following with just `bundle exec jekyll s --livereload` and I feel its adequate.. though it would be better if the `http://` protocol was included as well..
```
LiveReload address: 127.0.0.1:35729
```

**Comment by DirtyF** [comment]
@ashmaroli The port is displayed if you pass the --livereload option on the CLI but not if you only pass the livereload option to the options hash and then call `Jekyll::Commands::Serve.process(options)` (in a rake task for example).

**Comment by ashmaroli** [comment]
I see.. I was running `bundle exec jekyll s` from within the `docs/` folder..
FWIW, the `LiveReload address: 127.0.0.1:35729` message appears when I serve the `docs/` folder with `livereload: true` in `./docs/_config.yml`

**Comment by awood** [comment]
@ashmaroli Thanks for fixing this so quickly.

**Comment by ashmaroli** [comment]
@awood You're welcome.
A question:  If a user opts to run the server using the `--ssl-key` and `--ssl-cert` switches, will the LiveReload Address run on the `https://` address?

**Comment by DirtyF** [comment]
@jekyllbot: merge +fix

**Pull request merged**
