### PR TITLE
Added new website in sites made by jekyll

### PR DESCRIPTION
**Pull request by loctauxphilippe**
Added the Ozon website in the list of sites made by jekyll

### CODE REVIEW

**Comment by envygeeks** [comment]
Please change your commit message to reflect what you did properly. Thanks. :heart:

**Comment by loctauxphilippe** [comment]
@envygeeks the commit name or add a comment?

**Comment by envygeeks** [comment]
Your actual commit message is "Update sites.md" it should reflect that you added your site.

**Comment by loctauxphilippe** [comment]
@envygeeks done!

**Comment by envygeeks** [comment]
You updated the pull request title, in order to update the commit message you need to `git commit --amend` on the feature branch (from your local system) and then `--force push`

**Comment by loctauxphilippe** [comment]
@envygeeks I did my best

**Comment by envygeeks** [comment]
It'll do, it should really say: "Added <mydomain.com> to sites.md" please remember for next time.

**Comment by parkr** [comment]
I think your link really belongs on the Wiki page: https://github.com/jekyll/jekyll/wiki/sites

This page is not for every site made with Jekyll, just a select few great examples.

**Comment by pathawks** [comment]
And why was this site "hand-picked for learning purposes?"

**Comment by envygeeks** [comment]
Oh sorry massa @pathawks I didn't know.

**Pull request merged**
