### PR TITLE
Add `jekyll-random` plugin to docs

### PR DESCRIPTION
**Pull request by codecalm**
Hi!
I've created a Jekyll plugin to generate a large amount of random data. The data is generated based on `forloop.index`, so that every time when you run `jekyll build` the generated data is the same.

It would be nice to list it on plugins page. 
Thanks!

### CODE REVIEW

**Comment by DirtyF** [comment]
@jekyllbot: merge +docs

**Comment by codecalm** [comment]
thanks!

**Comment by DirtyF** [comment]
@chrisfinazzo yes, we haven't figure out an automated solution to list all themes and plugins, so for now you'll have to [follow the README](https://github.com/jekyll/directory#adding-your-plugin-or-your-theme)

**Comment by chrisfinazzo** [comment]
PR is [here][].

[here]: https://github.com/jekyll/directory/pull/44

**Comment by chrisfinazzo** [comment]
See Directory [#44][] for the associated PR.

[#44]: https://github.com/jekyll/directory/pull/44

**Comment by DirtyF** [comment]
@chrisfinazzo https://jekyll.github.io/directory/plugins/jekyll-random/

If people start adding plugins there, that might give me some motivation to work on this :)

**Comment by DirtyF** [comment]
@parkr work in progres on https://jekyll-directory.netlify.com/ 😉

**Pull request merged**
