### PR TITLE
Lock to Rubygems 2.6.14 to have Travis passing again

### LINKED ISSUE #6515: JRuby build is failing
All PRs are currently failing CI because the JRuby build is failing 😭😭😭

### PR DESCRIPTION
**Pull request by ashmaroli**
Resolve #6515 

I kinda traced the bug to the recent release from Rubygems. Attempting to patch using the last known working version..

### CODE REVIEW

**Comment by ashmaroli** [comment]
okay.. apparently, there's an error installing Rubygems `v 2.7.0`. Travis has fallen back to pre-installed `v2.6.13`..

**Comment by ashmaroli** [comment]
Rubygems `v 2.6.14` contains a security fix. Best, we try using that version then..

**Comment by DirtyF** [comment]
There's already a 2.7.1, I see no reason to stick to a old Rubygems version.

**Comment by ashmaroli** [comment]
> There's already a 2.7.1

2.7.1 was the reason why the JRuby build broke.. If a PR can be sent that changes our tests to suit that, this can be closed..

**Comment by Crunch09** [comment]
@ashmaroli Do you know if there is already an issue filed for `rubygems/rubygems` ? There seem to be a couple of issues regarding 2.7.1 already but not sure our JRuby issue is included.

**Comment by ashmaroli** [comment]
> Do you know if there is already an issue filed for `rubygems/rubygems` ?

I did skim through their issue list.., did not find any recently opened tickets related to our issue. I did not open one myself because I don't have a clear idea as to how to reproduce the bug because it breaks only our JRuby build. So the issue might as well be with how JRuby implements YAML loading.. again, not sure at all..
And I don't have a local JRuby installation to experiment with.. I was hoping to have this (or another better alternative) merged and deal with issue in due time..

**Pull request closed without merging**
