### PR TITLE
'jekyll clean': also remove .sass-cache

### LINKED ISSUE #4649: jekyll clean should remove .sass-cache
###### What version of Jekyll are you using (`jekyll -v`)?
jekyll 3.1.2

###### What operating system are you using?
Fedora 23 (Linux) x86_64

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
`jekyll clean`

###### What did you expect to see?
Removal of .sass-cache

###### What did you see instead?
.sass-cache left in place

### PR DESCRIPTION
**Pull request by parkr**
Fixes #4649. /cc @ctubbsii

/cc @jekyll/build @jekyll/stability

### CODE REVIEW

**Comment by parkr** [comment]
@envygeeks I think your bot thinks named parameters are a hash? Or can I not use named parameters?

**Comment by ctubbsii** [comment]
+1 LGTM

**Comment by envygeeks** [comment]
@parkr The bot has no real way to distinguish between keyword arguments and hashes because it's hard without us building more context driven detection.

**Comment by parkr** [comment]
@jekyllbot: merge +minor

**Pull request merged**
