### PR TITLE
Add permalinks to docs in '/maintaining/'

### LINKED ISSUE #5531: 404 on http://jekyllrb.com/docs/maintaining/
Links on the http://jekyllrb.com/docs/maintaining/ page return 404 errors because of the trailing slash.

- http://jekyllrb.com/docs/maintaining/affinity-team-captain/ -> 404
- http://jekyllrb.com/docs/maintaining/affinity-team-captain -> 200

### PR DESCRIPTION
**Pull request by ashmaroli**
fix #5531 

/cc @jekyll/documentation

### CODE REVIEW

**Comment by DirtyF** [comment]
@jekyllbot: merge+site

**Comment by DirtyF** [comment]
@ashmaroli thanks!

**Comment by parkr** [comment]
Wait I removed these on purpose. Why did you add them back in? Was something wrong?

**Comment by ashmaroli** [comment]
> Wait I removed these on purpose. Was something wrong?

@parkr  Issue #5531 happened.. though merging this did not solve it..

**Comment by DirtyF** [comment]
@parkr troubleshooting with default permalink I guess as now we can observe opposite behavior: 

- http://jekyllrb.com/docs/maintaining/affinity-team-captain is OK  
- http://jekyllrb.com/docs/maintaining/affinity-team-captain/ is 404


Sorry for merging this too quickly and being naïve as it all worked fine locally.

**Pull request closed without merging**
