### PR TITLE
Incremental: handle deleted/renamed/moved dependencies

### LINKED ISSUE #3716: Incremental regeneration prevents rebuilding if a file is deleted... ever.
If a file is deleted (either before, after or even during Jekyll) then incremental regeneration falls down trying to read a file that doesn't exist, it does not even try to correct this behavior, it just prevents Jekyll from loading at all.

```shell
docker run -p 127.0.0.1:4000:4000 --volume $(pwd):/srv/jekyll --name jekyll --rm -it jekyll/jekyll:beta jekyll serve --watch --trace
Configuration file: /srv/jekyll/_config.yml
            Source: /srv/jekyll
       Destination: /srv/jekyll/_site
 Incremental build: enabled
      Generating... 
/usr/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta5/lib/jekyll/regenerator.rb:105:in `mtime': No such file or directory @ rb_file_s_mtime - /srv/jekyll/_layouts/post.html (Errno::ENOENT)
	from /usr/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta5/lib/jekyll/regenerator.rb:105:in `modified?'
	from /usr/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta5/lib/jekyll/regenerator.rb:101:in `block in modified?'
	from /usr/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta5/lib/jekyll/regenerator.rb:100:in `each'
	from /usr/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta5/lib/jekyll/regenerator.rb:100:in `modified?'
	from /usr/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta5/lib/jekyll/regenerator.rb:79:in `source_modified_or_dest_missing?'
	from /usr/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta5/lib/jekyll/regenerator.rb:22:in `regenerate?'
	from /usr/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta5/lib/jekyll/site.rb:189:in `block in write'
	from /usr/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta5/lib/jekyll/site.rb:326:in `block (2 levels) in each_site_file'
	from /usr/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta5/lib/jekyll/site.rb:325:in `each'
	from /usr/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta5/lib/jekyll/site.rb:325:in `block in each_site_file'
	from /usr/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta5/lib/jekyll/site.rb:324:in `each'
	from /usr/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta5/lib/jekyll/site.rb:324:in `each_site_file'
	from /usr/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta5/lib/jekyll/site.rb:188:in `write'
	from /usr/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta5/lib/jekyll/site.rb:59:in `process'
	from /usr/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta5/lib/jekyll/command.rb:28:in `process_site'
	from /usr/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta5/lib/jekyll/commands/build.rb:60:in `build'
	from /usr/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta5/lib/jekyll/commands/build.rb:35:in `process'
	from /usr/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta5/lib/jekyll/commands/serve.rb:26:in `block (2 levels) in init_with_program'
	from /usr/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from /usr/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /usr/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /usr/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /usr/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /usr/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /usr/lib/ruby/gems/2.2.0/gems/jekyll-3.0.0.pre.beta5/bin/jekyll:17:in `<top (required)>'
	from /usr/local/bin/jekyll:23:in `load'
	from /usr/local/bin/jekyll:23:in `<main>'
```

/cc @alfredxing

### PR DESCRIPTION
**Pull request by alfredxing**
Should fix #3716. Added a test as well.

First PR in a long long time! :tada:

### CODE REVIEW

**Comment by envygeeks** [comment]
Fix the problem I had :+1:

**Comment by alfredxing** [comment]
Good to hear!
Why does JRuby have to be so slow... :snail:

**Comment by envygeeks** [comment]
It's because we can only test right now on JRuby head because there were some problem with Gem and jruby17 so we have to not only download it (fresh) but we have to set it up :cry: hopefully it'll only be at max a few months.  I might hit up @headius and see if he can figure out why the bundle+gem install problem regressed in the latest version.

**Comment by alfredxing** [comment]
But even running the test suite is going at a crawl. Looking at the build, the `script/cibuild` command took 289.12s (just under 5 minutes)...

**Comment by alfredxing** [comment]
Anyway, I'm pretty excited; I just noticed that this will be my 100th commit to the project! :confetti_ball:
I'll wait for @parkr to take a look, unless you want to merge it in now.

**Comment by envygeeks** [comment]
That I can't explain tbh, I could be doing something wrong, I'll have a look at performance options for JRuby in a few minutes and see what I can push up to speed up our tests.  There are tons of options.  I'm fine waiting for @parkr since I already merged it locally!

**Comment by envygeeks** [comment]
Oh and congrats :tada: on your 100th commit!

**Comment by parkr** [comment]
:shipit:

**Pull request merged**
