### PR TITLE
docs: add Layer0 deployment guide

### PR DESCRIPTION
**Pull request by rishi-raj-jain**
This is a 🔦 documentation change.

### CODE REVIEW

**Review by mattr- — APPROVED** [review]
Thanks for the contribution!

**Comment by mattr-** [comment]
Would you mind updating the spell check dictionary at `.github/actions/spelling/expect.txt` with the two new words pointed out by the spell check build?

**Comment by rishi-raj-jain** [comment]
Sure thing, @mattr-!

**Comment by rishi-raj-jain** [comment]
Done 🤞🏻

**Review by ashmaroli — APPROVED** [review]

**Comment by ashmaroli** [comment]
Thank you @rishi-raj-jain
@jekyllbot: merge +doc

**Pull request merged**
