### PR TITLE
Fix typo from 'Github' to 'GitHub'

### PR DESCRIPTION
**Pull request by sadikkuzu**
Github -> GitHub

This is a 🔦 documentation change. 

## Summary

Just a tiny little typo fix.

## Context

This is not related to any GitHub issues.

### CODE REVIEW

**Comment by ashmaroli** [comment]
@sadikkuzu Thank you for submiting this patch. Will you be able to edit the commit message to the following and update the branch..?
```
Fix typo from 'Github' to 'GitHub'
```
To update the commit message locally:
```
$ git commit --amend
$ git push origin patch-1 --force
```

**Comment by sadikkuzu** [comment]
Hi @ashmaroli 
I've edited the commit message.
Thanks in advance.
Have a nice day.

**Comment by ashmaroli** [comment]
@jekyllbot: merge +docs

**Comment by ashmaroli** [comment]
Thank you once again @sadikkuzu

**Pull request merged**
