### PR TITLE
Use Jekyll Feed for jekyllrb.com

### PR DESCRIPTION
**Pull request by benbalter**
This pull request swaps out the existing `/feed.xml` template for Jekyll Feed when building the documentation at jekyllrb.com. 

See https://github.com/jekyll/jekyll-feed for more information.

### CODE REVIEW

**Comment by envygeeks** [comment]
:+1:

**Comment by parkr** [comment]
Let's resolve https://github.com/jekyll/jekyll-feed/issues/52 first.

**Comment by envygeeks** [comment]
Can you rebase this @benbalter ? Looks like the issue was resolved but this is outdated.

**Comment by benbalter** [comment]
> Can you rebase this @benbalter ? Looks like the issue was resolved but this is outdated.

Donezo.

**Pull request merged**
