### PR TITLE
Optimize `Jekyll::Utils.parse_date`

### PR DESCRIPTION
**Pull request by fauno**
This is a 🔨 code refactoring.

## Summary

Same as #8424, let me know if I should write a benchmark :)

### CODE REVIEW

**Comment by ashmaroli** [comment]
Similar to #8424, `Jekyll::Utils` is a `module` as well.
Instance variables should be used carefully since modules can be *mixed-in* into various classes.

Would like to see your profiling / benchmark results. Is `Time.parse(input)` slower or `Time.parse(input).localtime` ?
If it is just `Time.parse(input)`, then we could just cache the result of `Time.parse(input)` and call `:localtime` on it to get a (mutable) non-cached string result.

**Comment by fauno** [comment]
It seems to be `Time.parse` rather than `:localtime`

**Review by DirtyF — APPROVED** [review]
LGTM

**Comment by ashmaroli** [comment]
@fauno I just came across an observation that calling `:localtime` on a `Time` object actually mutates the given `Time` object. Can you confirm..?

**Comment by fauno** [comment]
Sorry, I came back to see what happened with this PR and it seems I missed the email!  I confirmed with documentation and a quick freeze test (`Time.now.utc.freeze.localtime` throws `FrozenError`) so I changed the PR a little. Should I rebase?

**Comment by ashmaroli** [comment]
You need not rebase just yet, @fauno unless you'd like to use this branch in one of your projects.

**Comment by fauno** [comment]
Ok, everything seems fine, thanks for reviewing :)

**Comment by DirtyF** [comment]
@jekyll: merge +minor

**Pull request merged**
