### PR TITLE
Update sites.md

### PR DESCRIPTION
**Pull request by carsongross**
I'm using Jekyll to manage the intercooler.js site, cut releases, etc.

### CODE REVIEW

**Comment by envygeeks** [comment]
Please add your site here: https://github.com/jekyll/jekyll/wiki/Sites

**Comment by parkr** [comment]
Context may be here: https://twitter.com/jekyllrb/status/689889114703814660

**Comment by envygeeks** [comment]
Oh snap, I do apologize, I forgot about that post even though I seen it.

**Comment by carsongross** [comment]
Nah, my bad, I just clicked and started editing.  Sorry for the confusion.

**Pull request closed without merging**
