### PR TITLE
update appveyor.yml

### PR DESCRIPTION
**Pull request by ashmaroli**
Updating appveyor.yml to [support latest releases of Ruby vers](https://github.com/appveyor/website/blob/4cf4be275b18140b86ebfcadc4b8cceed851e769/NJekyll/site/_updates/2016-08-09.md) 
(... and experimenting with Build Cache)

\cc @XhmikosR

### CODE REVIEW

**Comment by XhmikosR** [comment]
I don't see the need for those changes.

**Comment by ashmaroli** [comment]
A big :-1: ?
 :sob: 

oh well.. :walking: :broken_heart:

**Comment by XhmikosR** [comment]
Because the changes are very bad.

1. The gems path is the same so your change broke that
2. The cache changes will prevent invalidating it

I hope you see now how useless and wrong this PR is.

**Comment by ashmaroli** [comment]
I admit that some changes in this PR are unnecessary.
I changed the folder names coz I didnt like seeing `RUBY_FOLDER..` `GEMS_FOLDER..` in the logs.
I changed the cache to see if clearing the `-> <file>` would cause installed gems to be cached for consequent tests..
While I was on that, I saw that Appveyor had pushed support for latest rubies, n bundler ( both of which were initiated by you ). So I thought, y not try updating them here as well..

Only after your latest comment, do I even realize that the changes were wrong. My apologies.
Thank you for the clarification, though.

**Comment by envygeeks** [comment]
> Because the changes are very bad.
> The gems path is the same so your change broke that
> The cache changes will prevent invalidating it
> I hope you see now how useless and wrong this PR is.

These kind of comments are unacceptable, please be more respectful when declining an idea.

**Pull request closed without merging**
