### PR TITLE
Apply the highlight class

### PR DESCRIPTION
**Pull request by chrisfinazzo**
See comments in #3940.

### CODE REVIEW

**Comment by envygeeks** [comment]
I don't know how hard this would be to regression proof.  That page is updated from our actual CONTRIBUTING.md in the repo and sometimes just copied right over, so it has a very high chance of regressing... and I don't remember if @parkr even still tests the site so we could prevent a regression there.

**Comment by envygeeks** [comment]
OH: I was the one who requested that, well I'll stick to what I requested.

**Comment by parkr** [comment]
What about backtick code blocks? If those work on the site, then they'll be cross-compatible.

**Comment by chrisfinazzo** [comment]
Either way you guys would like is fine. The other style (say on the [Posts][] page) is visually distinct, but does seem "heavy" given that there are multiple lines where it would be applied. Examples are as follows: 

[Posts]: http://jekyllrb.com/docs/posts/

Backticks: 

screen shot 2015-10-18 at 11 22 54 pm

CSS w/ the "highlight" class: 

screen shot 2015-10-18 at 11 30 49 pm

**Pull request merged**
