### PR TITLE
Proposal: Affinity teams and their captains

### PR DESCRIPTION
**Pull request by parkr**
Hey, Jekyll community!

I had a neat chat with @benbalter recently about our affinity teams and all the work the @jekyll/core team has in handling the issues and PR's that come through. He proposed that we ask certain members from affinity teams to become **"Team Captains"** which would:

- triage issues and help find solutions
- review PR's, then pass along to the core team for merge
- determine correct affinity team if not theirs

@jekyllbot would automatically assign an issue to a random team captain for the mentioned affinity team and it would be their responsibility to ensure the issue is handled [according to our guidelines on "Triaging an Issue"](https://github.com/jekyll/jekyll/blob/master/docs/triaging-an-issue.md). @jekyllbot would politely nudge the user to mention an affinity team if they didn't. 

This would apply only to `jekyll/jekyll` for the time being, but could be extended out to plugin repos as well in the future.

I propose we add the following team captains (if you have a ? next to your name, it's because I haven't asked you yet):

- @jekyll/build – @parkr, @mattr-, @ayastreb 
- @jekyll/documentation – @benbalter, @DirtyF, @parkr
- @jekyll/ecosystem – @pathawks, @benbalter, @parkr
- @jekyll/performance – @envygeeks, @mattr-, @parkr
- @jekyll/stability – @parkr, @jaybe-jekyll (?), @fene 
- @jekyll/windows – @XhmikosR (?), @parkr, @juthilo (?), @envygeeks 

What do you think?

### CODE REVIEW

**Comment by fene** [comment]
i could technically captain for the stability team if anyone else is needed

**Comment by PaulFWatts** [comment]
This sounds like a great idea to me. Hopefully I will know enough about Jekyll in the next few months to be able to volunteer and contribute in some way.

**Comment by mattr** [comment]
I'll suggest that @mattr- should probably be a build team captain rather than me. No that I don't appreciate the invitation... ;)

**Comment by mattr-** [comment]
LOL. That stinkin' dash on my user name causes so many problems. 😕






On Mon, Aug 22, 2016 at 7:54 PM -0500, "Matt Redmond" <notifications@github.com> wrote:












I'll suggest that @mattr- should probably be a build team captain rather than me. No that I don't appreciate the invitation... ;)

**Comment by parkr** [comment]
@fene We'd love that! Done 😄 

@PaulFWatts Yes please!! Did you [join an affinity team?](https://teams.jekyllrb.com/)

@mattr MERP sorryyyyy, I bet that happens more often than not. Thanks for being chill about it. ❤️

**Comment by PaulFWatts** [comment]
I've just joined some affinity teams


Kind regards
______________________________
Paul Watts
Gold Coast, Australia
p:     07 5536 6721
m:    0467 705 464
email:  paul.watts@me.com


On 23 August 2016 at 1:25:26 PM, Parker Moore (notifications@github.com) wrote:

@fene We'd love that! Done 😄

@PaulFWatts Yes please!! Did you join an affinity team?

@mattr MERP sorryyyyy, I bet that happens more often than not. Thanks for being chill about it. ❤️

**Comment by envygeeks** [comment]
I would like to be placed into Windows as I do handle Windows problems here and I do know a lot about Windows internals even if I am a die hard Linux user.  I guess it's my fault for doing systems.

**Comment by parkr** [comment]
> I would like to be placed into Windows as I do handle Windows problems here and I do know a lot about Windows internals even if I am a die hard Linux user. I guess it's my fault for doing systems.

@envygeeks Done.

**Comment by parkr** [comment]
@jekyll/core: Could I get 2 "LGTM"'s, please? 😄

**Comment by envygeeks** [comment]
LGTM.

**Comment by mattr-** [comment]
LGTM

**Comment by parkr** [comment]
Thanks!

@jekyllbot: merge +dev

**Pull request merged**
