### PR TITLE
Fixes #3836. Fix site template header menu iteration variables

### LINKED ISSUE #3836: Site template overwrites `page` variable
The loop at site template [header.html][1] overwrites the page variable and therefore it's not possible to use it anymore for example to see if the current page matches the entry in the list to make it selected/active.

[1]: https://github.com/jekyll/jekyll/blob/master/lib/site_template/_includes/header.html#L17

### PR DESCRIPTION
**Pull request by gynter**
Fixes issue #3836.

### CODE REVIEW

**Comment by parkr** [comment]
@envygeeks Can you please look into this JRuby error?

**Comment by jensechu** [comment]
@parkr The same tests failed on my PR for a CSS comment change that was merged in. I think something is up with master?

**Comment by envygeeks** [comment]
@jensechu @parkr it's neither our or your fault, it looks like there is a problem with current jRuby head.  I'll move jRuby to an allow to fail matrix but you're fine on your end.

**Comment by gynter** [comment]
Has issues related to the builds resolved? If Yes then maybe merge this PR?

**Comment by envygeeks** [comment]
I will check to see in a little bit, I know that they were fixed on head because @headius got Travis-CI to update their images for jruby-head but right now we are waiting for stable to come out.  If you guys feel this is safe to merge and I'll deal with the JRuby errors that pop up later since it's still experimental.

**Pull request merged**
