### PR TITLE
Windows: describe which option to choose

### PR DESCRIPTION
**Pull request by kirstin**
This is a 🔦 documentation change.

## Summary

I propose to install everything as I have no idea what shall be installed.
You have these options:
- MSYS2
- MSYS2 and MINGW development toolchain
By proposing to install everything, I hope to create a discussion in case people know what to choose at this step.
I chose the development toolchain so that compilation can take place.
Is that correct?

### CODE REVIEW

**Review by DevBeatDad — APPROVED** [review]

**Review by mattr- — APPROVED** [review]
@jekyllbot: merge +docs

**Comment by mattr-** [comment]
oh, right. jekyllbot doesn't respond to comments in reviews. I'll let CI finish running and then merge this.

**Comment by mattr-** [comment]
@kirstin I just noticed that there's a spelling check error. Would you mind addressing that and updating your PR? You can add the word `toolchain` to `.github/actions/spelling/expect.txt`. Please add the word in alphabetical order.

**Comment by kirstin** [comment]
Hi, I added a space between tool and chain. I think the dictionary should be fine with that now.

**Comment by parkr** [comment]
@jekyllbot: merge +docs

**Comment by parkr** [comment]
> oh, right. jekyllbot doesn't respond to comments in reviews.

Now it does! https://github.com/jekyll/jekyllbot/pull/17 😄

**Pull request merged**
