### PR TITLE
Set kramdown gem version from 1.3 to 1.9 in jekyll.gemspec

### PR DESCRIPTION
**Pull request by SuriyaaKudoIsc**
@parkr @mojombo 

New kramdown version: https://rubygems.org/gems/kramdown!

### CODE REVIEW

**Comment by pathawks** [comment]
Why do you need to specifically disallow older versions of Kramdown?

**Comment by SuriyaaKudoIsc** [comment]
I would like to set Kramdown to the newest version.

**Comment by pathawks** [comment]
> I would like to set Kramdown to the newest version.

Right. By default the newest version of Kramdown will be installed. But some users may want to use an older version of Kramdown.

Your change does nothing to allow the latest version of Kramdown, it only blocks users from using a version older than 1.9.

**Comment by parkr** [comment]
I think we will remain more flexible about this for now. Thanks, though! You can update your version with `gem update kramdown` or `bundle update kramdown`. :smile

**Comment by SuriyaaKudoIsc** [comment]
:+1:

**Pull request closed without merging**
