### PR TITLE
Bump codeclimate-test-reporter to v1.0.5

### LINKED ISSUE #5796: Update dependency constraint to allow for codeclimate-test-reporter v1.0.5
Hey there! :wave:

I noticed that the constraint you have for codeclimate-test-reporter doesn't allow for the latest version to be used.

The constraint I found was `~> 0.6.0`, and the latest version available is `1.0.5`.

Can you look into updating that constraint so our users can use the latest and greatest version? Thanks! :revolving_hearts:

### PR DESCRIPTION
**Pull request by DirtyF**
Fix #5796 

V1.0 changes: https://github.com/codeclimate/ruby-test-reporter/blob/master/CHANGELOG.md#v100-2016-11-03

- [x]  run codeclimate-test-reporter as a separate step in our build

### CODE REVIEW

**Comment by DirtyF** [comment]
```
This usage of the Code Climate Test Reporter is now deprecated. Since version 1.0, we now require you to run `SimpleCov` in your test/spec helper, and then run the provided `codeclimate-test-reporter` binary separately to report your results to Code Climate.
```

**Comment by parkr** [comment]
> run codeclimate-test-reporter as a separate step in our build

What do you mean by this checkbox? Is this still something you mean to accomplish?

**Comment by DirtyF** [comment]
@parkr sorry, I should have checked it after my last commit 😕  

I followed [the docs ](https://docs.codeclimate.com/docs/travis-ci-ruby-test-coverage) and CI passes, so apparently all is fine. What do you say?

**Comment by parkr** [comment]
@jekyllbot: merge +dev

**Pull request merged**
