### PR TITLE
bump i18n

### PR DESCRIPTION
**Pull request by jekyllbot**
PR automatically created for @DirtyF.

```text
bump i18n
```

### CODE REVIEW

**Comment by ashmaroli** [comment]
Looks like we can't bump `i18n` without bumping `activesupport` to *at least* `v5.1.6`.
Lets tackle this in `4.0`.. whatsay?

**Comment by pathawks** [comment]
Looks like we need to drop 2.2 before we can merge this. :+1:

**Comment by oe** [comment]
Let's try this again!

**Comment by ashmaroli** [comment]
@DirtyF this would benefit from merging the changes made to `master` :wink:

**Comment by DirtyF** [comment]
rebased and now 💚

**Comment by DirtyF** [comment]
@jekyllbot: merge +major

**Pull request merged**
