### PR TITLE
Where filter should work on string values with spaces

### PR DESCRIPTION
**Pull request by jekyllbot**
PR automatically created for @pathawks.

```text
Where filter should work on string values with spaces
```

### CODE REVIEW

**Comment by pathawks** [comment]
Fixes #5586

**Comment by pathawks** [comment]
This reverts 6245ddb14d0291ff7b581a937e804f871f792c30 which was introduced in #4555.

Should I make note of that in a commit message, or is leaving a breadcrumb here enough?

**Comment by pathawks** [comment]
> Just needs a test.

I have added a test, but the situation is unusual in that this test will not fail without these changes unless Jekyll-Assets is running, so that's weird.

**Comment by parkr** [comment]
It sounds like you're addressing a bug here. I'd love to have some way to ensure we don't regress and reintroduce the bug and a test is the easiest way to accomplish that. Am I understanding this wrong?

**Comment by parkr** [comment]
Sorry! I misread your comment. Perhaps we don't have a reproducible example with just Jekyll core?

**Comment by pathawks** [comment]
[This is the code](https://github.com/envygeeks/extras/blob/d5da6d59e63c002c48a164384687270be8252587/lib/extras/string.rb#L25-L30) that **Jekyll-Assets** is including that messes with the way strings are converted to arrays.

Honestly this is a bit over my head, but this PR does successfully work around that code. ¯\\\_(ツ)\_/¯

**Comment by pathawks** [comment]
This is [a problem with the *extras* gem](https://github.com/envygeeks/extras/blob/d5da6d59e63c002c48a164384687270be8252587/lib/extras/string.rb#L25-L30), not with Jekyll.

**Pull request closed without merging**
