### PR TITLE
Problematic UTF+bom files

### PR DESCRIPTION
**Pull request by DirtyF**
add test files for #2853

### CODE REVIEW

**Comment by parkr** [comment]
Let's see if CI fails. It should.

**Comment by DirtyF** [comment]
Why? I didn't add a test with this files.

**Comment by Crunch09** [comment]
@DirtyF 👍 I'll try to send a PR to your `utf8-bom` branch which adds failing tests.

**Comment by pathawks** [comment]
Shouldn't this cause the fixture site to fail to build?

**Comment by DirtyF** [comment]
@pathawks I just merged @Crunch09 related tests, let's see if CI fails.

**Comment by pathawks** [comment]
I've never been so happy to see CI fail :rofl:

**Comment by parkr** [comment]
I have a potential fix in https://github.com/jekyll/jekyll/pull/6433.

**Comment by pathawks** [comment]
@jekyllbot: merge +bug

**Comment by pathawks** [comment]
Shoot, I meant to change the title to something that would be more descriptive in the changelog. Oops.

**Pull request merged**
