### PR TITLE
Add random filter

### PR DESCRIPTION
**Pull request by BrendanBerkley**
Solution for #1890.

### CODE REVIEW

**Comment by parkr** [comment]
From a UX perspective, I would expect

```liquid 
{% my_array | sample %}
```

to return one random item (not an array). In contrast, I'd expect

```liquid
{{ random }}
```

to return a random float in the range [0,1), and

```liquid
{{ random:5 }}
```

to return a random integer in the range [0,5).

Does that seem reasonable? Don't want `random` to confuse folks.

**Comment by BrendanBerkley** [comment]
Seems reasonable. I'll work it out.

**Comment by penibelst** [comment]
I’m glad randomness is not evil anymore.

The proposed implementation draws exactly one ball from the [urn](https://en.wikipedia.org/wiki/Urn_problem) an then returns it back. Next time the same ball can be drawn again. It’s impossible to draw more than one ball at a time.

My rejected proposal #1892 works for any number of balls.

## 1 ball

```
{{ balls | shuffle | first }}
```

## *n* balls

```
{% assign shuffled_balls = balls | shuffle %}
{% for ball in shuffled_balls limit:n %}
  {{ ball }}
{% endfor %}
```

What do you think about drawing more than one ball?

**Comment by parkr** [comment]
@penibelst Why not `sample:n`?

```liquid
{{ balls | sample:12 | first }}
```

**Comment by penibelst** [comment]
@parkr I like the `sample:n` notation too.

## 1 ball

```
{{ balls | sample: 12 | first }}
```

## *n* balls

```
{% assign shuffled_balls = balls | sample: n %}
{% for ball in shuffled_balls %}
  {{ ball }}
{% endfor %}
```

**Comment by envygeeks** [comment]
Personally I feel like sample is where it's at.  It just feels right.

**Comment by BrendanBerkley** [comment]
I'm with @envygeeks here - I like the simpler approach. Though I suppose it would be possible to do `{{ thing | sample }}` as well as `{{ thing | sample:12 }}`, right?

This is my first time doing a pull request where people don't agree on what to do, so I'm not sure how to move forward! I don't want to keep working on something that people won't want to use.

Also, @parkr - for the random filter idea, you used filter notation, but that'd have to be a custom tag right? I got something working locally as a tag but not as a filter, and I didn't see a precedent in the existing filters for something like you suggested.

**Comment by parkr** [comment]
> for the random filter idea, you used filter notation, but that'd have to be a custom tag right? I got something working locally as a tag but not as a filter, and I didn't see a precedent in the existing filters for something like you suggested.

Can you clarify with liquid examples?

**Comment by parkr** [comment]
Merged the `sample` filter. #4223

**Pull request closed without merging**
