### PR TITLE
initial implementation of posts as a collection

### LINKED ISSUE #3169: Make pages and posts instances of Jekyll::Document.
Can't take credit for this idea. @benbalter said it. The idea is that posts are a sort of collection, and pages are as well if you think kind of tilt your head and squint a little. It would make sense for them all to share a common interface. We abolish the Convertible module and make anything that was once convertible a Document, et voila.

### PR DESCRIPTION
**Pull request by parkr**
This PR moves posts functionality into `Collection` and `Document`. Still very much a work-in-progress.

To-do list:

- [ ] Permalink style/structure consistency (dates!)
- [ ] Liquid consistency
- [x] Filename validation (right now, not customizable)
- [x] `published?`
- [ ] Categories from subdirs
- [x] Categories from metadata
- [x] Tags from metadata
- [ ] Excerpts (auto-generate only when asked for (Liquid::Drop?))
- [ ] Auto-generated titles from slug
- [ ] Custom `<=>` with the date in there (maybe we get that for free with the `YYYY-MM-DD-` prefix?)
- [x] Permalink style shortcuts (currently only allowed for "dated" documents in the posts collection)
- [ ] `id` ~> `slug`
- [ ] `previous`, `next`
- [ ] `draft?`
- [ ] Reading in drafts at all.

Fixes #3169.

/cc @benbalter

### CODE REVIEW

**Comment by benbalter** [comment]
yessssss

tears of joy

**Comment by AJ-Acevedo** [comment]
I'm curious about the line item above:
`id` (do we need this?)

If this is referring to having an id or each collection this would be pretty awesome! Using Jekyll for a knowledge base would be great to have a unique id instead of only having a pretty permalink for the URI.

**Comment by envygeeks** [comment]
@AJ-Acevedo please comment on the line not in an ambiguous spot that we have no idea. Thanks.

**Comment by parkr** [comment]
@AJ-Acevedo you mean in the checklist in my PR description? Each post has an `id` used to uniquely identify it, useful for things like Atom feeds.

**Comment by AJ-Acevedo** [comment]
@parkr Yes, I mean in the checklist in the PR description. Thank you for the clarification.

**Comment by parkr** [comment]
Made obsolete by #4055.

**Pull request closed without merging**
