### PR TITLE
Incorporate `relative_url` filter in `link` tag

### LINKED ISSUE #5682: link tag should use URL filters
The `{% link %}` tag should use the new URL filter's logic to output either absolute URLs or URLs that are relative to site source.

### LINKED ISSUE #5943: Allow filters on link tag
- [x] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [x] This is a feature request.
- [x] I am on (or have tested on) ***Debian/Ubuntu*** GNU/Linux
- [x] I am on (or have tested on) ***Windows*** 10+

## Summary

I'd like some alternative for the `link` tag that would allow anyone to make the link relative or absolute!

## Details

Currently, if I use `link` tag I need to use it as such:

```html
<a href="{{ site.baseurl }}{% link about.md %}">About</a>
```

That will create a relative link to the about.md generate link. For an absolute link, I could use the following:

```html
<a href="{{ '/' | absolute_url }}{% link about.md %}">About</a>
```

This doesn't seem ideal to me...

## Proposal

Create a new `link_relative` and `link_absolute` tags, which would basically take the existing functionality from `link` tag, and pass on to the `relative_url` and `absolute_url` filters.

```html
<a href="{% link_relative about.md %}">About</a>

<a href="{% link_absolute about.md %}">About</a>
```

## Benefits

Easier coding and maintainability!

### PR DESCRIPTION
**Pull request by ashmaroli**
Resolves #5682 
Closes #5943 

With this, `{% link about.md %}` will return `/blog/about/` for a site configured with
 `baseurl: /blog` and `permalink: pretty`

**`BREAKING-CHANGE`**

- [x] Initial implementation
- [x] ~~Unit test/~~ Cucumber feature
~~Documentation~~

### CODE REVIEW

**Comment by pathawks** [comment]
I like this.
This could break just about every site that uses Jekyll.

**Comment by ashmaroli** [comment]
> This could break just about every site that uses Jekyll.

Yes, hence the big red label :wink:
Alternatively, we can release this as a new tag entirely..

**Comment by pathawks** [comment]
> Alternatively, we can release this as a new tag entirely..

No, I agree that it should be a clean break.

I wonder about an automated migration assistant. 🤔

**Comment by ashmaroli** [comment]
> I wonder about an automated migration assistant.

`Jekyll::Doctor` would like to hire an intern to help.. :grin:

**Comment by DirtyF** [comment]
At least breaking changes should be displayed in the post-install message.

**Comment by ashmaroli** [comment]
@DirtyF @oe Why not just print the link to our Migration docs since there are going to be numerous *breaking-changes*..?

**Comment by oe** [comment]
@ashmaroli Let's merge this! Could you add a short post-install message?

**Comment by DirtyF** [comment]
what about post_url?

**Comment by DirtyF** [comment]
@jekyllbot: merge +major

**Pull request merged**
