### PR TITLE
add 'bundler' as a dependency

### PR DESCRIPTION
**Pull request by ashmaroli**
Technically, Bundler is only a `development_dependency` but specifying it as a `runtime_dependency` has it installed along with Jekyll.

This removes the need for 
```
$ gem install jekyll bundler
```
and possible errors otherwise:
```
~/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler (LoadError)
```

### CODE REVIEW

**Comment by ashmaroli** [comment]
An earlier [suggestion](https://github.com/jekyll/jekyll/pull/5237#issuecomment-239393692) was [turned down](https://github.com/jekyll/jekyll/pull/5237#issuecomment-239564097). 
(Requesting a proper clarification.)

/cc @jekyll/core

**Comment by ashmaroli** [comment]
any updates on this?
/cc @parkr @pathawks

**Comment by pathawks** [comment]
@ashmaroli I'm afraid this sort of decision is beyond my expertise.

**Comment by parkr** [comment]
Please see https://github.com/jekyll/jekyll/issues/5684#issuecomment-290616936 – in short, the hard reliance on a `Gemfile` makes this impossible, as many users don't use `Gemfile`s. Thanks for the PR!

**Comment by pathawks** [comment]
Currently, `jekyll new` fails spectacularly without `bundler` installed:

> ```
>   Dependency Error: Yikes! It looks like you don't have bundler or one of
> its dependencies installed. In order to use Jekyll as currently configured,
> you'll need to install this gem. The full error message from Ruby is:
> 'cannot load such file -- bundler' If you run into trouble, you can find
> helpful resources at https://jekyllrb.com/help/! 
> jekyll 3.5.2 | Error:  bundler
> ```

It seems like there must be _some_ better way to handle this.

**Comment by ashmaroli** [comment]
we can perhaps disable automatic `bundle install` if the `LoadError` is raised..?

**Comment by pathawks** [comment]
Closing this in favor of #6377

**Pull request closed without merging**
