### PR TITLE
Docs: Assorted accessibility tweaks.

### PR DESCRIPTION
**Pull request by XhmikosR**
jekkylrb.com:
jekyllrb-com

this branch:
access-branch

### CODE REVIEW

**Comment by parkr** [comment]
I'm pretty happy with this. Not super excited about the darker background color for the footer and the code block but I'm open to it.

@cobyism Any thoughts here?

**Comment by XhmikosR** [comment]
You can try http://squizlabs.github.io/HTML_CodeSniffer/ yourself.

**Comment by parkr** [comment]
That's a cool tool! I'll have to look up why the contrast ratio is expected at that particular level.

**Comment by cobyism** [comment]
This all seems fine to me. I think the darker background for the terminal window is a good move, however I’m not sure the other colour changes are really that much of a win. I don’t have any problems with them though, so :+1:

**Comment by XhmikosR** [comment]
In case it's not clear, I tried to bump the colors enough so that they pass WCAG2AA, nothing more :)

**Comment by XhmikosR** [comment]
As for the empty `span`, personally I'd rather add a new `sr-only` class and make use of it everywhere for the screen readers. Let me know if you agree with that and I'll make the change adapting the class from Bootstrap.

**Comment by cobyism** [comment]
> I'd rather add a new sr-only class and make use of it everywhere for the screen readers.

Sounds good, yeah. Would another option be to add a `title` attribute or something similar to the icon element?

**Comment by XhmikosR** [comment]
Not sure about title in this case, since the icon is just a helper IMO. I'll add the `sr-only` class and let you know.

**Comment by XhmikosR** [comment]
Done. I added a `title` in the `a` element too.

**Pull request merged**
