### PR TITLE
Rename CODE_OF_CONDUCT to show in banner

### PR DESCRIPTION
**Pull request by crispgm**
`CONDUCT.markdown` is not recognized.

### CODE REVIEW

**Comment by DirtyF** [comment]
@jekyllbot: merge+minor

**Comment by parkr** [comment]
This is a site/docs change, right? Not a minor enhancement?

**Comment by DirtyF** [comment]
yeah, wrong label 😩

**Comment by pup** [comment]
i dont think jekyllbot even recognized that it was a minor change

**Pull request merged**
