### PR TITLE
default source folder

### PR DESCRIPTION
**Pull request by noraj1337**
- add a default source folder
- modify the documentation to take into account the change

### CODE REVIEW

**Comment by ashmaroli** [comment]
sorry mate, simply adding a line to the config file does not change a core functionality that has been around since inception. This PR in its current state will be closed as it simply creates confusion..even though the intent has been to illustrate an idea..

**Comment by noraj1337** [comment]
@ashmaroli There is no core fonctionnality to change, they mecanism already exist, we just need to change the default value.

**Comment by DirtyF** [comment]
I get the idea but this is a breaking change for Github Pages while it adds little value.

/cc @jekyll/stability

**Comment by benbalter** [comment]
@noraj1337 Thanks for the pull request! :smile: 

Can you share a bit more about why you think we should make the change?

**Comment by noraj1337** [comment]
@DirtyF Are you sure about that? I didn't see [anything](https://help.github.com/articles/using-jekyll-as-a-static-site-generator-with-github-pages/) and you can still build Jekyll locally and deploy the `_site` folder on gh-pages only (that's why I'm doing with Hexo).

@benbalter I explained it on the issue https://github.com/jekyll/jekyll/issues/6105

**Comment by benbalter** [comment]
> I explained it on the issue #6105

To confirm, the motivation is not having e.g., your Gemfile or README in the same folder as markdown files?

**Comment by noraj1337** [comment]
@benbalter This should answer your question:

```
$ tree                                                                      noraj@manji
.
├── _config.yml
├── Gemfile
├── Gemfile.lock
├── _public
│   ├── about
│   │   └── index.html
│   ├── assets
│   │   └── main.css
│   ├── feed.xml
│   ├── index.html
│   └── jekyll
│       └── update
│           └── 2017
│               └── 05
│                   └── 31
│                       └── welcome-to-jekyll.html
└── _sources
    ├── about.md
    ├── index.md
    └── _posts
        ├── 2017-05-31-welcome-to-jekyll.markdown
        └── test.md

10 directories, 12 files
```

**Comment by pathawks** [comment]
@noraj1337 The question is with regard to motivation, not a particular directory hierarchy.

**Comment by noraj1337** [comment]
@pathawks I don't agree, putting all source files in the root directory is a mess.

**Comment by parkr** [comment]
This is a backwards-incompatible change and will not be accepted. You have the opportunity to use the `--source` flag for the CLI and `source` setting in your `_config.yml` and that is its purpose: to set apart your source from other files.

**Comment by noraj1337** [comment]
@parkr I know the option but this should have been default...
No need for me anywayn using middleman now, this is more hackable and cleaner.

**Pull request closed without merging**
