### PR TITLE
Trials with repository version of Liquid

### PR DESCRIPTION
**Pull request by ashmaroli**
Experiment to gauge compatibility with unreleased changes in Liquid.

### CODE REVIEW

**Comment by DirtyF** [comment]
Note: getting a build error when trying to build our documentation site:

```ruby
  Liquid Exception: uninitialized constant Liquid::Expression::MethodLiteral in /Users/frank/code/jekyll/jekyll/docs/_layouts/docs.html
bundler: failed to load command: jekyll (/Users/frank/code/jekyll/jekyll/vendor/bundle/ruby/2.6.0/bin/jekyll)
NameError: uninitialized constant Liquid::Expression::MethodLiteral
  /Users/frank/code/jekyll/jekyll/lib/jekyll/filters.rb:407:in `compare_property_vs_target'
  /Users/frank/code/jekyll/jekyll/lib/jekyll/filters.rb:199:in `block in where'
  /Users/frank/code/jekyll/jekyll/lib/jekyll/filters.rb:198:in `select'
  /Users/frank/code/jekyll/jekyll/lib/jekyll/filters.rb:198:in `where'
```

**Comment by ashmaroli** [comment]
> getting a build error

Liquid has changed some internal public API..
Addressed via https://github.com/jekyll/jekyll/pull/8443/commits/ec275388457e1aac948e34bc6f48ba93e2686fae

**Comment by DirtyF** [comment]
Getting an error when building with --livereload option

```ruby
 Auto-regeneration: enabled for '/Users/frank/code/frank.taillandier.me'
#<Thread:0x00007fded0287290@/Users/frank/code/jekyll/jekyll/lib/jekyll/commands/serve/live_reload_reactor.rb:41 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	5: from /Users/frank/code/jekyll/jekyll/lib/jekyll/commands/serve/live_reload_reactor.rb:44:in `block in start'
	4: from /Users/frank/code/frank.taillandier.me/vendor/bundle/ruby/2.6.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
	3: from /Users/frank/code/frank.taillandier.me/vendor/bundle/ruby/2.6.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
	2: from /Users/frank/code/jekyll/jekyll/lib/jekyll/commands/serve/live_reload_reactor.rb:47:in `block (2 levels) in start'
	1: from /Users/frank/code/frank.taillandier.me/vendor/bundle/ruby/2.6.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:531:in `start_server'
/Users/frank/code/frank.taillandier.me/vendor/bundle/ruby/2.6.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:531:in `start_tcp_server': no acceptor (port is in use or requires root privileges) (RuntimeError)
bundler: failed to load command: jekyll (/Users/frank/code/frank.taillandier.me/vendor/bundle/ruby/2.6.0/bin/jekyll)
RuntimeError: no acceptor (port is in use or requires root privileges)
  /Users/frank/code/frank.taillandier.me/vendor/bundle/ruby/2.6.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:531:in `start_tcp_server'
  /Users/frank/code/frank.taillandier.me/vendor/bundle/ruby/2.6.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:531:in `start_server'
  /Users/frank/code/jekyll/jekyll/lib/jekyll/commands/serve/live_reload_reactor.rb:47:in `block (2 levels) in start'
  /Users/frank/code/frank.taillandier.me/vendor/bundle/ruby/2.6.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
  /Users/frank/code/frank.taillandier.me/vendor/bundle/ruby/2.6.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
  /Users/frank/code/jekyll/jekyll/lib/jekyll/commands/serve/live_reload_reactor.rb:44:in `block in start'
```

**Comment by DirtyF** [comment]
Note: builds do not feel faster.

**Comment by DirtyF** [comment]
Closing in favor of #8662

**Pull request closed without merging**
