### PR TITLE
Docs: move permalinks from documents into config

### PR DESCRIPTION
**Pull request by parkr**
Reverts jekyll/jekyll#5532 in favor of a global permalink 😄

### CODE REVIEW

**Comment by parkr** [comment]
`script/proof` with `--disable-external`:

```text
- ./_site/docs/maintaining/becoming-a-maintainer/index.html
  *  internally linking to reviewing-a-pull-request.md, which does not exist (line 311)
  *  internally linking to triaging-an-issue.md, which does not exist (line 299)
- ./_site/docs/maintaining/merging-a-pull-request/index.html
  *  internally linking to reviewing-a-pull-request.md, which does not exist (line 295)
- ./_site/docs/maintaining/reviewing-a-pull-request/index.html
  *  internally linking to ../CONDUCT.markdown, which does not exist (line 293)
- ./_site/docs/maintaining/special-labels/index.html
  *  internally linking to triaging-an-issue.md#staleness-and-automatic-closure, which does not exist (line 305)
  *  trying to find hash of triaging-an-issue.md#staleness-and-automatic-closure, but /Users/parkr/jekyll/jekyll/_site/docs/maintaining/special-labels/index.html/triaging-an-issue.md does not exist (line 305)
htmlproof 2.6.4 | Error:  HTML-Proofer found 6 failures!
```

Gonna fix those here too.

**Comment by parkr** [comment]
Welp. 7af41649e953bb2da4743db6f5b8a7fc477fca86

**Comment by zdroid** [comment]
Seems fine to me. Just gotta resolve merge issues.

**Comment by parkr** [comment]
oh @DirtyF did you already fix these?

**Comment by DirtyF** [comment]
@parkr yes, everything was OK yesterday, the remaining conflict is just about a link I add in a page.

**Comment by DirtyF** [comment]
@jekyllbot: merge +site

**Pull request closed without merging**
