### PR TITLE
Add Appveyor testing

### PR DESCRIPTION
**Pull request by XhmikosR**
~~https://ci.appveyor.com/project/jekyll/jekyll~~
https://ci.appveyor.com/project/XhmikosR/jekyll

TODO:

- [x] Use the proper badge (/CC @parkr so that I can update my patch)
- [x] Rename the AppVeyor account to `jekyll` in https://ci.appveyor.com/account
- [x] **Enable gems caching**. ~~We need to make all the tests pass first, in order for this to take effect~~
- [x] ~~See why `gem update --system` seems to make the whole process halt~~ See **[here](https://github.com/github/pages-gem/pull/103#issuecomment-68770128)** for a workaround
- [ ] Fix tests to pass!!

### CODE REVIEW

**Comment by XhmikosR** [comment]
@FeodorFitsner: can you check the last build and shed some light? I'm guessing it's a PATH issue.

**Comment by parkr** [comment]
> @FeodorFitsner: can you check the last build and shed some light? I'm guessing it's a PATH issue.

Looks like it's a problem with my `script/test`. I do some magic to get the rake lib dir (problems with it in Ruby 2.2, so had to do this) https://github.com/jekyll/jekyll/blob/master/script/test#L14-L16

**Comment by XhmikosR** [comment]
@parkr: yeah that must be the reason. Even locally I get

```console
xmr@xmr-PC /c/Users/xmr/Desktop/jekyll
$ script/test
DL is deprecated, please use Fiddle
DL is deprecated, please use Fiddle
-e:1:in `<main>': uninitialized constant Specification (NameError)
No c:/Ruby21/lib/ruby/gems/2.1.0/gems/Gem. Installing Rake.
DL is deprecated, please use Fiddle
DL is deprecated, please use Fiddle
ERROR:  While executing gem ... (OptionParser::MissingArgument)
    missing argument: -v
+ bundle exec ruby -Ilib:test -Ic:/Ruby21/lib/ruby/gems/2.1.0/gems/Gem -Itest/ c:/Ruby21/lib/ruby/gems/2.1.0/gems/Gem/rake/rake_test_loader.rb ./test/test_cleaner.rb ./test/test_coffeescript.rb ./test/test_collections.rb ./test/test_command.rb ./test/test_configuration.rb ./test/test_convertible.rb ./test/test_document.rb ./test/test_draft.rb ./test/test_entry_filter.rb ./test/test_excerpt.rb ./test/test_filters.rb ./test/test_front_matter_defaults.rb ./test/test_generated_site.rb ./test/test_kramdown.rb ./test/test_layout_reader.rb ./test/test_liquid_extensions.rb ./test/test_log_adapter.rb ./test/test_metadata.rb ./test/test_new_command.rb ./test/test_page.rb ./test/test_path_sanitization.rb ./test/test_plugin_manager.rb ./test/test_post.rb ./test/test_rdiscount.rb ./test/test_redcarpet.rb ./test/test_redcloth.rb ./test/test_related_posts.rb ./test/test_sass.rb ./test/test_site.rb ./test/test_tags.rb ./test/test_url.rb ./test/test_utils.rb
DL is deprecated, please use Fiddle
ruby: No such file or directory -- c:/Ruby21/lib/ruby/gems/2.1.0/gems/Gem/rake/rake_test_loader.rb (LoadError)

real    0m0.658s
user    0m0.000s
sys     0m0.030s

xmr@xmr-PC /c/Users/xmr/Desktop/jekyll
$
```

Note that I have just run `bundle install` before this so everything is there.

**Comment by XhmikosR** [comment]
In fact `bundle exec ruby -e "puts Gem::Specification.find_by_name('rake').gem_dir.split('/').last + '/lib'"` seems to fail.

**Comment by parkr** [comment]
> Maybe it's a forward slashes issue?

Probably. There's a path separator variable we can use instead of `/`. Good catch!

**Comment by XhmikosR** [comment]
@parkr: sounds good! Please ping me when you have something working pushed to master so that I rebase and check again.

BTW, I think we need to merge this ASAP. I mean, problems will keep arising and we need this. Even if Windows isn't officially supported, having all the tests pass, is more than enough.

**Comment by XhmikosR** [comment]
Updated.

**Comment by parkr** [comment]
Almost there, then?

**Comment by XhmikosR** [comment]
It's the same error we got after the custom loader script :/

Rebased, let's see...

**Comment by XhmikosR** [comment]
@parkr: any news about this?

**Comment by parkr** [comment]
The error isn't particularly helpful – something is wrong with the $LOAD_PATH.

**Comment by XhmikosR** [comment]
This didn't happen before those loader changes...

**Comment by parkr** [comment]
> This didn't happen before those loader changes...

That's because it was trying to load in the rake loader (which is what I copied). The loader seems to work as expected. The stacktrace points to `test_coffeescript.rb`. What is the `$LOAD_PATH`?

**Comment by XhmikosR** [comment]
How can I check that? Please remember we are on Windows :)

**Comment by parkr** [comment]
> How can I check that? Please remember we are on Windows :)

It's a Ruby global variable. `p $LOAD_PATH`. :)

**Comment by XhmikosR** [comment]
I have no idea how to make that variable show its value :/

**Comment by parkr** [comment]
> I have no idea how to make that variable show its value :/

In `helper.rb`, add `p $LOAD_PATH`.

**Comment by XhmikosR** [comment]
In which line exactly?

**Comment by parkr** [comment]
At the top of the file. It has to be added.

**Comment by XhmikosR** [comment]
@parkr: pushed but you seem to have disabled AppVeyor?

**Comment by XhmikosR** [comment]
```console
xmr@xmr-PC /c/Users/xmr/Desktop/jekyll
$ bash ./script/cibuild
 ----------------------------------------------------------
          _   ______   _  __ __     __  _        _
         | | |  ____| | |/ / \ \   / / | |      | |
         | | | |__    | ' /   \ \_/ /  | |      | |
     _   | | |  __|   |  <     \   /   | |      | |
    | |__| | | |____  | . \     | |    | |____  | |____
     \____/  |______| |_|\_\    |_|    |______| |______|

 ----------------------------------------------------------
+ bundle exec ruby -Ilib:test -Itest/ -rloader test/test_cleaner.rb test/test_coffeescript.rb test/test_collections.rb test/test_command.rb test/test_configuration.rb test/test_convertible.rb test/test_document.rb test/test_draft.rb test/test_entry_filter.rb test/test_excerpt.rb test/test_filters.rb test/test_front_matter_defaults.rb test/test_generated_site.rb test/test_kramdown.rb test/test_layout_reader.rb test/test_liquid_extensions.rb test/test_log_adapter.rb test/test_new_command.rb test/test_page.rb test/test_path_sanitization.rb test/test_plugin_manager.rb test/test_post.rb test/test_rdiscount.rb test/test_redcarpet.rb test/test_regenerator.rb test/test_related_posts.rb test/test_sass.rb test/test_site.rb test/test_tags.rb test/test_url.rb test/test_utils.rb
DL is deprecated, please use Fiddle
["c:/Users/xmr/Desktop/jekyll/lib:test", "c:/Users/xmr/Desktop/jekyll/test", "c:/Ruby21/lib/ruby/gems/2.1.0/gems/bundler-1.7.12/lib", "c:/Ruby21/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib", "c:/Ruby21/lib/ruby/site_ruby/2.1.0", "c:/Ruby21/lib/ruby/site_ruby/2.1.0/i386-msvcrt", "c:/Ruby21/lib/ruby/site_ruby", "c:/Ruby21/lib/ruby/vendor_ruby/2.1.0", "c:/Ruby21/lib/ruby/vendor_ruby/2.1.0/i386-msvcrt", "c:/Ruby21/lib/ruby/vendor_ruby", "c:/Ruby21/lib/ruby/2.1.0", "c:/Ruby21/lib/ruby/2.1.0/i386-mingw32"]
method adapters is deprecated. use profiles instead
Coverage report generated for Unit Tests to c:/Users/xmr/Desktop/jekyll/coverage. 2 / 2 LOC (100.0%) covered.

real    0m3.786s
user    0m0.000s
sys     0m0.000s

xmr@xmr-PC /c/Users/xmr/Desktop/jekyll
$
```

**Comment by parkr** [comment]
The colon isn't the path separator on windows! Gotcha. Is it a semicolon?

**Comment by XhmikosR** [comment]
Yeah

**Comment by parkr** [comment]
Maybe the loader can pump them in instead of bash.

**Comment by parkr** [comment]
Unless you know of a better way.

**Comment by XhmikosR** [comment]
If you have a proposed patch I can certainly try it when I'm back, just to
make sure it indeed fixes the issue.

In theory this change seems pretty straightforward; we use a semicolon for
Windows and a comma otherwise.

**Comment by parkr** [comment]
@XhmikosR Rebase!

**Comment by XhmikosR** [comment]
@parkr: https://ci.appveyor.com/project/jekyll/jekyll/build/56/job/35yd40w77dbl99cw

>There was a ArgumentError while loading jekyll.gemspec:
Malformed version number string 3.0.0-beta1 from
C:/projects/jekyll/jekyll.gemspec:13:in `block in <main>'

**Comment by parkr** [comment]
> There was a ArgumentError while loading jekyll.gemspec:
> Malformed version number string 3.0.0-beta1 from

?! I've never seen this before. What version of RubyGems is the machine running? @FeodorFitsner, is there a way to upgrade RubyGems? This version incantation works fine for me.

**Comment by XhmikosR** [comment]
@parkr: there is a way but it's uber slow... Let's see.

**Comment by XhmikosR** [comment]
OK it works finally! Now someone has to make the tests pass...

**Comment by XhmikosR** [comment]
Most of the errors (not failures) are due to the yajl-ruby issue. https://github.com/tmm1/pygments.rb/pull/106

**Comment by XhmikosR** [comment]
@FeodorFitsner: even with the DNS change, `bundle install` takes a long time. Isn't there something you can do to speed this up? It's almost unusable if one has to wait 30 minutes...

**Comment by XhmikosR** [comment]
@FeodorFitsner: any news? Isn't there something you can do about this? Makes me wonder how no one else has complained about this huge slowdown yet. `bundle install` doesn't even finish now after `gem update --system 2.3.0 --quiet --no-ri --no-rdoc`.

**Comment by FeodorFitsner** [comment]
I've been noticing that multiple times too that `bundle install` slows down drastically when you do upgrade default gem coming with Ruby installation to the latest version with `gem update` command. I'd really love to help, but I don't have a clue what's going on there. Though I don't think it's something specific to AppVeyor environment.

Let's think on it. I'm going to provision a clean VM on Azure and try reproducing the issue there. So, is it only with Ruby 1.9.3?

Maybe @luislavena can suggest something?

**Comment by XhmikosR** [comment]
@FeodorFitsner: it's not 1.9.3 only; it happens with every Ruby version **only on AppVeyor**. On my dev VM everything installs in a timely manner.

**Comment by XhmikosR** [comment]
@parkr @alfredxing: now that one build managed to get past the install part, you can see the [failures](https://ci.appveyor.com/project/jekyll/jekyll/build/62/job/785al70tpg7ilkef).

**Comment by XhmikosR** [comment]
So what are we going to do with this guys? I'm in touch with @FeodorFitsner to fix the speed issues, but until then I have managed to work around it. So, now we see the failures fine.

**Comment by XhmikosR** [comment]
Note that it seems there's a new failure due to coffeescript that affects Travis too.

**Comment by parkr** [comment]
> @parkr: so any news?

I'd like to have the appveyor tests passing before merging the branch. Also, 18 minutes is just too long to wait for one build, let alone the potential 72 minute combined build time for all four environments.

**Comment by XhmikosR** [comment]
Well caching isn't in effect since tests fail hence the current duration.

There is nothing else we can do from our side unfortunately.  AppVeyor is
just slow.

**Comment by parkr** [comment]
:/

**Comment by XhmikosR** [comment]
@parkr: can't GitHub just get a paid plan? Although the first priority should be to just fix the tests and then see how things will go when caching is enabled. I also reduced the configurations tested; I don't see any point in testing all of 2.0-2.2 x64, I only kept one x64.

**Comment by XhmikosR** [comment]
@parkr: someone seems removed Appveyor from the project.

**Comment by envygeeks** [comment]
What purpose does Appveyor serve for the Jekyll project?

**Comment by XhmikosR** [comment]
Well, Jekyll has broken in the past for Windows only and none from the
development team noticed since they don't use Windows.

**Comment by envygeeks** [comment]
However, based on your past comments (admittedly by simply scanning without full context) it seems this service wants to charge money and you (might) even recommend it which makes this futile.

**Comment by XhmikosR** [comment]
Huh? Travis offers pro plans too. I don't care about AppVeyor or anything; it's just what I used. You are free to find any other better solution for Windows.

Anyway, I find futile this whole PR from the fact that I have it opened since November 2014. Closing and take care of Windows yourself.

**Comment by envygeeks** [comment]
Fair enough.  I hope you enjoy your day and sorry it didn't work out.

**Pull request closed without merging**
