### PR TITLE
Remove extra spaces

### PR DESCRIPTION
**Pull request by chrisfinazzo**

### CODE REVIEW

**Comment by DirtyF** [comment]
LGTM

cc @jekyll/documentation

**Comment by pathawks** [comment]
Is this worth confusing the Git history if we want to `blame` this line?

**Comment by envygeeks** [comment]
My thoughts echo @pathawks these kind of changes should come with
meaningful changes.

**Comment by parkr** [comment]
Agreed with @pathawks and @envygeeks. Thanks for the PR, though, @chrisfinazzo! 😄

**Pull request closed without merging**
