### PR TITLE
Removed .htaccess from the include filter in the main configuration. …

### PR DESCRIPTION
**Pull request by htmelvis**
…As stated in the docs you must add this file manually if you want to include. Exclude would not work on .htaccess.  This solves Issue #3958 
screen shot 2015-09-02 at 12 57 04 pm

### CODE REVIEW

**Comment by pathawks** [comment]
Looks like you accidentally modified `.gitignore` ?

**Comment by envygeeks** [comment]
Looks like it's using Intellij, sounds like a good idea to leave it there just in-case somebody else does in the future so we don't get commits of the settings.

**Comment by htmelvis** [comment]
agh! intelliJ ignores it's project files in my project

**Comment by envygeeks** [comment]
It looks like you caused tests to fail.

**Comment by htmelvis** [comment]
My Bad, I should have read the complete contributing doc. I will fix this and resubmit.

**Comment by htmelvis** [comment]
It looks like .htaccess has been added to almost every test as an input file to check against. I am still working on my version to not expect .htaccess and I am unsure if you want changes merged back in altered that way. It may be easier to change the docs (if your default dotfile makes sense) to reflect the dotfile being present in your test project.

**Comment by htmelvis** [comment]
Removed tests to watch for .htaccess file creation in the final build. I have commented out the main test "watch the dotfile" in ```create_sites.feature```

**Comment by parkr** [comment]
Hey @htmelvis, we can't accept this until 4.x as it would be considered a breaking change. One thing we could do is remove it if `.htaccess` is in `exclude`.

**Comment by htmelvis** [comment]
Ok, that sounds good, completely forgot about this.

**Pull request closed without merging**
