### PR TITLE
Add support for detached front matter (optional)

### PR DESCRIPTION
**Pull request by darwin**
Say you have $site/some/path/page.md. With this patch you can optionally
create $site/some/path/page.md.fm.yml (or .yaml) and it will be
recognized as a "detached YAML front matter". That means that data found
in this yaml file will be merged with data in normal inlined front
matter (inlined data override detached data).

Why?
My IntelliJ IDE is too "advanced" and cannot cope with YAML front
matters in various files. For example with .md , .scss or even .html it
breaks inspections[1] and bugs me about invalid syntax all day. This
allows me to remove inlined front matters and put them into separate
files and stop fighting with IntelliJ.

Why <page>.fm.yml?
This is by convention. File name prefix must match the associated
page file name. I don't want to introduce a clash with potentially
existing yaml files in exiting sites. And I need a way how
to detect these special yaml files and filter them out from site output.
Also the extension must be yml or yaml for IDEs to treat it as a proper
yaml file.

Notes:
1. this should be transparent to existing Jekyll users
2. interested users may incrementally move their inlined front matters
   into detached files as needed

[1] https://www.jetbrains.com/help/idea/2016.3/code-inspection.html

### CODE REVIEW

**Comment by DirtyF** [comment]
Interesting. IMHO that looks like a edge case to me and more related to IntelliJ than Jekyll itself, that's the reason why I would rather suggest you implement this in a plugin.

/cc @jekyll/core

**Comment by darwin** [comment]
This wasn't a problem for me when using TextMate or Sublime (5+ years using jekyll). Because front matter just confused syntax highlighting at the beginning of files. No big deal. But when I recently switched to IntelliJ with most of my web-dev work this started to be a real PITA, because additionally I rely on inspections being "clean" for my whole project. I guess most people use text editors with jekyll so they don't have issue with inlined front matters. And people using IDEs with deep introspections didn't care enough to fix this (AFAIK).

I don't see an easy way how to implement something like this with a plugin. And even if it was possible it would definitely involve heavy monkey-patching. btw. I have implemented [several Jekyll plugins](https://github.com/binaryage/site/tree/master/_plugins) over past years.

Just to be clear. This is just a proposal. I'm perfectly ok if this PR gets rejected. It does not block me, I will [simply roll my patches on top of jekyll](https://github.com/binaryage/site/blob/3f019f062cf0348ee3421ac59bc0fbe5c61d7efd/Gemfile#L3) master in [my own fork](https://github.com/binaryage/jekyll). Just wanted to share this for other folks to benefit from.

**Comment by parkr** [comment]
Prior art: https://github.com/jekyll/jekyll/issues/1082

We have considered this a few years ago and ultimately didn't feel like it was a good idea. This is a fairly fundamental change that is too big to just accept for the sake of helping IntelliJ users from annoyances.

I'm interested in the merits of why this feature should be considered *separate* from the IDE/text editor/syntax highlighter argument. What value does it add to separate YAML front matter from metadata?

**Comment by darwin** [comment]
Fair enough, thanks for taking time to reply @parkr.

**Pull request closed without merging**
