### PR TITLE
exe/jekyll comments

### PR DESCRIPTION
**Pull request by danielhaim1**
## Summary
Added comments to the code to explain its purpose and functionality.

This is a 🔦 documentation change

### CODE REVIEW

**Comment by ashmaroli** [comment]
Hello @danielhaim1, while I agree that comments to code help improve comprehension, I also believe that too much of something does more harm than good.

Also, your commentary for `$LOADPATH.unshift` is wrong. The instruction doesn't mean to "force printing something.." at all. Perhaps you meant to place it elsewhere? 😀

On the whole, I am not with the proposal / idea. Deferring for a second-opinion..

Pinging @parkr.

**Comment by danielhaim1** [comment]
Hold up, let me check the code. I had some trouble with branching this morning and things got really messy. Let's close this pull request, I'll review and amend in another one. 

Re the other PR, the docs for blank_template -- I think it might be helpful to see some option settings, and update some basic stuff in the template to explain how things work.

**Comment by danielhaim1** [comment]
@ashmaroli fixed, I had two branches for this file, but the comment was missing in one of them due to syncing issues. I'm currently reviewing and documenting the code to gain a better understanding to contribute more effectively.

**Comment by legionerlegion** [comment]
69

вс, 11 февр. 2024 г., 04:28 Daniel Haim ***@***.***>:

**Pull request closed without merging**
