### PR TITLE
Remove `ruby RUBY_VERSION` from generated Gemfile

### PR DESCRIPTION
**Pull request by ashmaroli**
I've had `ruby RUBY_VERSION` in all my Gemfiles generated by `jekyll new` on Windows. Ignored it because it never seemed to cause any issue.
Proposing interpolating the variable based on this [comment](https://github.com/jekyll/jekyll/issues/5719#issuecomment-274227923) to trigger a Travis build and check if this is a fix..

### CODE REVIEW

**Comment by ashmaroli** [comment]
okay.. dont know what burnt Travis. But local tests on my **Windows** system with `Ruby 2.3.3` and `Bundler 1.14.0` did not raise issues with `ruby RUBY_VERSION`

This PR may lead to future issues by having the subsequent blogs generated locked to a certain Ruby version.
Leaving it open for further feedback

label: `Discussion`, `dont-merge-yet`

**Comment by parkr** [comment]
We should probably just get rid of this line. I think it's only useful because Heroku requires it, but even then it's not that useful. I use the `ruby` pragma in `Gemfile` exactly never.

**Comment by ashmaroli** [comment]
> We should probably just get rid of this line

I like that idea. Would it be better if it were commented out instead?

**Comment by parkr** [comment]
> Would it be better if it were commented out instead?

Why comment it out? That seems like useless bloat.

**Comment by ashmaroli** [comment]
> That seems like useless bloat.

LOL! okay, will remove it entirely.

**Comment by ashmaroli** [comment]
The `do-not-merge` label ought to be removed, no?

**Comment by pathawks** [comment]
@ashmaroli Yeah! Who added that anyway?
…oh 😶

**Comment by DirtyF** [comment]
@jekyllbot: merge +dev

**Comment by parkr** [comment]
> @jekyllbot: merge +dev

This isn't a dev change, this is a change to the way `jekyll new` works.

**Pull request merged**
