### PR TITLE
Add blog post introducing Jekyll Talk

### PR DESCRIPTION
**Pull request by alfredxing**
Add a blog post on the site introducing the new Jekyll Talk forums (ref #3517).

@parkr :eyes:

### CODE REVIEW

**Comment by parkr** [comment]
This is AWESOME!!! I have no comments, actually, it's perfect. :clap:

**Comment by parkr** [comment]
@envygeeks anything else you'd like to see here?

**Comment by envygeeks** [comment]
:+1: this is good, I like it -- now we just need to do one for Docker once I get done with the Fedora imgs.

**Comment by parkr** [comment]
Published! Thanks so much @alfredxing :smile: 

https://twitter.com/jekyllrb/status/571416917510123520

**Comment by alfredxing** [comment]
:cloud:&nbsp;&nbsp;:rocket:
&nbsp;&nbsp;&nbsp;&nbsp;:cloud:&nbsp;&nbsp;:cloud:

**Comment by envygeeks** [comment]
I also updated CONTRIBUTING.md to inform them that we have a non-technical non-bug forum.

**Comment by parkr** [comment]
> I also updated CONTRIBUTING.md to inform them that we have a non-technical non-bug forum.

Nice! Thanks @envygeeks

**Pull request merged**
