### PR TITLE
CI: GitHub Actions

### PR DESCRIPTION
**Pull request by DirtyF**
Simple test to see if we could use GitHub Actions to test on Linux and Windows.

### CODE REVIEW

**Comment by ethomson** [comment]
👋 Just noticed this PR and I thought I'd say hi.  I'm both a Product Manager for GitHub Actions and a big jekyll fan (it powers both [my personal website](https://edwardthomson.com/) and [my podcast's website](https://allthingsgit.com/)).  Is there anything that I can do to help here?

**Comment by ashmaroli** [comment]
Hello @ethomson :wave: 
Always glad to meet a fan :smiley:.

I'm one of the Core contributors of Jekyll and my personal opinion is that this PR is ready for a review. But, if there's any way we can get the checks on Windows to pass in current state (tests pass on AppVeyor), I'm all ears.

Thank you very much.

---

P.S., Is there a way to cache the `bundle` across builds like on Travis and AppVeyor..?

**Comment by ethomson** [comment]
Cool, I'll take a look.  A quick glance suggests that it _looks_ like it might be related to (you guessed it) line ending configuration.  😫

We're working on caching now.  We hope to have it 🔜

**Comment by ashmaroli** [comment]
Superseded by #7822

**Pull request closed without merging**
