### PR TITLE
update recommended .gitignore code snippet

### PR DESCRIPTION
**Pull request by Strangehill**

### CODE REVIEW

**Comment by ashmaroli** [comment]
`.jekyll-metadata` is not a folder however.

**Comment by Strangehill** [comment]
is this update better? or would it better to making things a bit more concise?

**Comment by ashmaroli** [comment]
> would it better to making things a bit more concise?

I'd suggest having it express more clearly. A simple change would do:
```
# Ignore metadata file generated by Jekyll
.jekyll-metadata
```

**Comment by DirtyF** [comment]
The simplest way is to use https://gitignore.io/api/jekyll

**Comment by Strangehill** [comment]
gitigore.io has `.jekyll-cache` which is missing here too so how about adding it and remove references to 'files' or 'folders' and just refer to them both under a 'metadata' category allowing the final slash to speak for itself?

```
# Ignore metadata generated by Jekyll
_site/
.sass-cache/
.jekyll-cache/
.jekyll-metadata

# Ignore folders generated by Bundler
.bundle/
vendor/
```

**Comment by ashmaroli** [comment]
@Strangehill I'm fine with current diff.
But since you changed the PR title, would you like to change the commit message as well or merge as is? Your call.

**Comment by ashmaroli** [comment]
Thank you @Strangehill :slightly_smiling_face:

**Pull request merged**
