### PR TITLE
Add 'jekyll-fontello' to plugins

### PR DESCRIPTION
**Pull request by ericcornelissen**
Added a small plugin I made to download a webfont from [Fontello](https://github.com/fontello/fontello) to the list of plugins, generators.

### CODE REVIEW

**Comment by pathawks** [comment]
@DirtyF I feel the same way.
Perhaps we should state that explicitly, and remove existing Gists from our listing?

**Comment by DirtyF** [comment]
>  Perhaps we should state that explicitly, and remove existing Gists from our listing?

💯  I'll happily do that in a dedicated PR.

**Comment by oe** [comment]
@ericcornelissen If you want to add this plugin, feel free to copy the changes into a separate repository, release it as a gem, and then open another pull request!

**Comment by ericcornelissen** [comment]
@oe Sure! Just went with a Gist since I saw a couple others do the same 🙂

**Pull request closed without merging**
