### PR TITLE
Added JekyllConf page

### PR DESCRIPTION
**Pull request by mneumegen**
Lists all the JekyllConf talks. Also features one talk every build.

### CODE REVIEW

**Comment by envygeeks** [comment]
I'm :shipit: but this should be two commits not one.  There are other changes here.

**Comment by parkr** [comment]
I'm thinking this should be just at `jekyllrb.com/jekyllconf/` as it's not a docs page. But other than that, LGTM!

**Comment by mneumegen** [comment]
@envygeeks Yep sorry forgot I fixed that typo.

@parkr Sweet! Agreed but I'm not sure how to do this. The way the navigation is built it assumes the links are prefixed with /docs/:

`{% assign item_url = item | prepend:"/docs/" | append:"/" %}`

**Comment by parkr** [comment]
@mneumegen It'd be a stand-alone page, I think. I was thinking about adding a "Community" section that'd behave like `/docs/` or `/news/`, but have community-related resources.

**Pull request closed without merging**
