### PR TITLE
CSS refactoring - see pull request #3329

### PR DESCRIPTION
**Pull request by tkrotoff**
See pull request #3329

(Unfortunately I [cannot reopen](http://stackoverflow.com/a/12838195/990356) the existing merged and closed pull request)

### CODE REVIEW

**Comment by parkr** [comment]
:+1: from me. @alfredxing :shipit: if you think it's good, too.

**Comment by alfredxing** [comment]
@tkrotoff Thanks!

**Comment by parkr** [comment]
@alfredxing Did you update the History file?

**Comment by alfredxing** [comment]
@parkr Yep, just did!

**Pull request merged**
