### PR TITLE
Add find filters to optimize where-first chains

### PR DESCRIPTION
**Pull request by ashmaroli**
- This is a 🙋 feature or enhancement.
- I've added tests.
- I've adjusted the documentation.

## Summary

Introducing Liquid filters `find` and `find_exp` to optimize scenarios involving `first` chained to `where` and `where_exp` filter respectively.

### Purpose

`where` (`where_exp`) evaluates given conditions against *all items* in a given array and chaining the `first` filter returns a single object from the pool. This could be wasteful when the array is large with numerous items and the first winner is near the starting end.

i.e. say the array is `["apple", "lemonade", "spade", "sunglasses", "umbrella", "cola"]`
`{{ array | where: "type", "drink" | first }}` and `{{ array | find: "type", "drink" }}` are equivalent and return the same object (`"lemonade"`) but the latter stops processing after two items.

### CODE REVIEW

**Comment by DirtyF** [comment]
Is that something that already exists in Liquid? What's the expected gain?

**Comment by ashmaroli** [comment]
> Is that something that already exists in Liquid?

As of now, there is no `find` filter in upstream Liquid.

> What's the expected gain?

For the general user-base? Depends on how it is used.
For Jekyll's docs site, profiles for `PR#8172` should shed some light.

**Comment by ashmaroli** [comment]
I've added a benchmark script to compare the performance of the `find` filter vs `where` + `first` filters to illustrate the possible boost.

**Comment by ashmaroli** [comment]
> If liquid don't have it, why should we?

Liquid has a different implementation of `where` filter from ours. So even if they were to add a `find` filter, it would be based on their version of `where`. That could have a different outcome for our users.

**Comment by DirtyF** [comment]
@jekyll: merge +minor

**Pull request merged**
