### PR TITLE
docs: Add frontmatter date formatting information

### PR DESCRIPTION
**Pull request by jedd-ahyoung**
I saw [this question](http://stackoverflow.com/q/18362317/677526) on StackOverflow, and realized that having the answer in the documentation would be beneficial.

### CODE REVIEW

**Comment by parkr** [comment]
It's actually a bit more flexible. We use `Time.parse` under the hood so it can be as little as the YYYY-MM-DD or the whole string you give. There are other formats as well! But this is a good rule of thumb format. :+1:

**Comment by BM5k** [comment]
:+1:

**Comment by parkr** [comment]
Slight technicalities, but let's get this up there and address those later.

**Comment by envygeeks** [comment]
:heart:

**Pull request merged**
