### PR TITLE
Add documentation for smartify Liquid filter

### PR DESCRIPTION
**Pull request by pathawks**
Add documentation for jekyll/jekyll#4323

Sorry, this probably should have been part of that PR.

### CODE REVIEW

**Comment by parkr** [comment]
Ah, yes! Thank you. :)

**Comment by parkr** [comment]
@jekyllbot: merge +site

**Comment by jhabdas** [comment]
@pathawks et. al, would it be useful to also indicate in the documentation `smartify` will handle converting `--` into an ndash? Also, I noticed the filter works with `page.title` but not `content`. If that's expected, is it also worth mentioning?

**Comment by pathawks** [comment]
> Also, I noticed the filter works with page.title but not content. If that's expected, is it also worth mentioning?

Can you provide a bit more detail?

**Comment by jhabdas** [comment]
> Can you provide a bit more detail?

`{{ content | smartify }}` results in `--` output to page where content contains `--`. I tried this at both the `_default.md` layout with and without using the [`_compress` layout](http://jch.penibelst.de/).

**Comment by jhabdas** [comment]
Ah, that makes good sense. Thanks @pathawks

**Comment by pathawks** [comment]
@jhabdas You could open a PR if you think this is worth mentioning in the docs :+1:

**Comment by jhabdas** [comment]
Sounds good to me. Need to grok our discussion in https://github.com/gettalong/kramdown/pull/299 a little more before I do. Thanks for staying on top of these issues and all of your helpful feedback, @pathawks.

**Pull request merged**
