### PR TITLE
Remove 'cache_dir' during `jekyll clean`

### LINKED ISSUE #4227: Consolidate caches and create a _cache folder for *all* to use.
Today we did an audit for our biggest Jekyll site and noticed it has like 8 cache folders, this is pretty big and unwieldy, it also makes it harder for us to control the caching on our build servers.  We should create a `_cache` folder and consolidate all Jekyll caching into that folder, and then ask plugin authors to place their caches in that folder too with or without prefixes.  Exp:
- `_cache/jekyll/incremental`
- `_cache/jekyll-assets/assets`
- `_cache/jekyll/sass`

Now cleanup went from "let me figure out what is what" to `rm -rf _cache`

### PR DESCRIPTION
**Pull request by pathawks**
Fixes #4227

### CODE REVIEW

**Comment by pathawks** [comment]
We will probably want to move `.sass-cache/` and `.jekyll-metadata` into this directory.

**Comment by parkr** [comment]
We have site.in_source_dir() which is a helpful method for not worrying about File.join’s. What do you think about site.in_cache_dir() as well? Doesn’t have to be this PR, but I think it would add value for plug-in authors.

**Comment by pathawks** [comment]
> We had talked about making this `_cache` instead of a dot directory. What do you think?

My original instinct was to use `_cache/`, but I changed it to the dot directory because of 
https://github.com/jekyll/jekyll/issues/4227#issuecomment-310653092 and because it's what we use for `.jekyll-metadata`. 

I have no preference regarding the default name. If somebody has a preference, we can change it :+1:

**Comment by parkr** [comment]
Ah, ok!

**Comment by pathawks** [comment]
@jekyllbot: :shipit: +major

**Pull request merged**
