### PR TITLE
Link tags should return URL relative to baseurl

### PR DESCRIPTION
**Pull request by jekyllbot**
PR automatically created for @pathawks.

```text
Link tags should return URL relative to baseurl
```

### CODE REVIEW

**Comment by pathawks** [comment]
Thank you @jekyllbot ❤️

**Comment by pathawks** [comment]
Is this a breaking change, or a bugfix? It will probably require modification of any sites that rely both on these tags and `baseurl`, so maybe a 4.0 change?

**Comment by parkr** [comment]
Oh man, it's a breaking change for folks with `site.baseurl` already there. So I guess documentation is all we can do? Ugh.

**Comment by parkr** [comment]
Look at that AppVeyor 🍏 . Yessssss. ✨ 

Closing as 4.0 is probably not going to happen for ages. Feel free to add a "all URL-related tags should use URL filters" and we can revisit it if we decide to go forward with Jekyll 4.0.

**Pull request closed without merging**
