### PR TITLE
Add comments in Gemfile

### PR DESCRIPTION
**Pull request by SuriyaaKudoIsc**
@parkr @mojombo

### CODE REVIEW

**Comment by envygeeks** [comment]
This just replicates what is implied by the group names.  Can you explain why this is necessary?

**Comment by SuriyaaKudoIsc** [comment]
The comments `#` already exists so I added the group names in the comments.

**Comment by envygeeks** [comment]
The `#` exists to make things easier to read, not to duplicate content.

**Comment by SuriyaaKudoIsc** [comment]
Oh, I see.

**Pull request closed without merging**
