### PR TITLE
Replace duplicate with postive local test in issue template

### LINKED ISSUE #5285: New issue template missing error on GitHub Pages reproduced locally
The *new issue* template says:

- [ ] I was trying to install.
- [ ] There is a broken Plugin API.
- [ ] I had an error on GitHub Pages, and I have not tested locally.
- [ ] I had an error on GitHub Pages, and GitHub Support said it was a Jekyll Bug.
- [ ] I had an error on GitHub Pages and I did not test it locally.
- [ ] I was trying to build.
- [ ] It was another bug.

These are essentially duplicates:

- [ ] I had an error on GitHub Pages, and I have not tested locally.
- [ ] I had an error on GitHub Pages and I did not test it locally.

You are missing something like:

- [ ] I had an error on GitHub Pages, and I have reproduced it testing locally.

### PR DESCRIPTION
**Pull request by DirtyF**
Fix #5285

### CODE REVIEW

**Comment by envygeeks** [comment]
I do like this much better, it nudges and encourages them to consider trying it locally.
LGTM!

:heart:

**Comment by envygeeks** [comment]
LGTM.

**Comment by benbalter** [comment]
LGTM. Thanks @DirtyF for keeping it positive. 🌴 🐢 🌵

**Comment by envygeeks** [comment]
@jekyllbot: merge +dev

**Comment by parkr** [comment]
❤️

**Pull request merged**
