### PR TITLE
Optimize markdown parsing with Kramdown by reusing the options and parser objects

### PR DESCRIPTION
**Pull request by ashmaroli**
- This is a 🙋 feature or enhancement.
- Tested by existing coverage.

## Summary

`Kramdown::Document` is designed to set up the necessary options and a parser (based on the provided options) to initiate conversion of a Markdown content string.

But Jekyll uses the same set of options (and therefore the parser as well) to convert *all of its Markdown documents*. Therefore, having kramdown run the set up tasks for each document is wasteful.

This PR proposes to subclass `Kramdown::Document` and move the set up tasks from the `:initialize` method to a `singleton_menthod`. This approach has the set up tasks run for just the *first Markdown document contents* converted, cache the resulting objects and subsequently provide these objects to consequent conversions.

### CODE REVIEW

**Comment by ashmaroli** [comment]
### Memory Profile Summary

```diff
--- master https://travis-ci.org/jekyll/jekyll/jobs/652560205
+++ PR     https://travis-ci.org/jekyll/jekyll/jobs/652608908

- Total allocated: 396.41 MB (3625375 objects)
+ Total allocated: 387.31 MB (3599878 objects)
- Total retained:  19.80 MB (107263 objects)
+ Total retained:  19.80 MB (107275 objects)
```

**Comment by mattr-** [comment]
I went and looked at the Kramdown code. It's too simple to require further changes. Would be nice to see something like this pushed upstream if they'll agree to it.

**Comment by mattr-** [comment]
@jekyllbot: merge +minor

**Comment by ashmaroli** [comment]
Awesome!! Thank you very much @mattr- :tada:

**Pull request merged**
