### PR TITLE
Add footer comment in default.html

### PR DESCRIPTION
**Pull request by SuriyaaKudoIsc**
@parkr @mojombo

### CODE REVIEW

**Comment by parkr** [comment]
@SuriyaaKudoIsc Please do not ping `@mojombo` – he is no longer actively working on this project. Please use the description to write a reason for your change. We have a process for triaging issues, so don't worry about us not responding.

Why do you think we should add this comment?

**Comment by SuriyaaKudoIsc** [comment]
It's better to use the generated site time tag in a comment because some developers want to now how fast the site was build by Jekyll.

I use it also on my website https://bit.ly/Suriyaa, too!

**Comment by envygeeks** [comment]
@SuriyaaKudoIsc then they should look at the logs, the generated sites source is not the place to look for that information, it's out of the way and unintuitive.

**Comment by SuriyaaKudoIsc** [comment]
Ok.

**Pull request closed without merging**
