### PR TITLE
Cache URLFilter results of string inputs per site

### PR DESCRIPTION
**Pull request by ashmaroli**
## Summary

Currently on `master`, the results for `relative_url` and `absolute_url` are cached per `Liquid:Context` instances. But this is *insufficient* for string inputs which are context-independent.

This PR proposes to cache such results per `Jekyll::Site` instance.

### CODE REVIEW

**Comment by ashmaroli** [comment]
## Comparisons

### Verbose build with `--profile` summary

```diff
--- master https://travis-ci.org/jekyll/jekyll/jobs/644965616
+++ PR     https://travis-ci.org/jekyll/jekyll/jobs/644986354

$ bundle exec jekyll build -s docs --verbose --profile

- done in 6.164 seconds.
+ done in 5.638 seconds.
```

### Memory Profile summary

```diff
--- master https://travis-ci.org/jekyll/jekyll/jobs/644965617
+++ PR     https://travis-ci.org/jekyll/jekyll/jobs/644986355

- Total allocated: 424.44 MB (4021894 objects)
+ Total allocated: 412.15 MB (3885617 objects)
- Total retained:  19.78 MB (107009 objects)
+ Total retained:  19.70 MB (105991 objects)
```

**Comment by ashmaroli** [comment]
## Comparisons

### Verbose build with `--profile` summary

```diff
--- master https://travis-ci.org/jekyll/jekyll/jobs/649458789
+++ PR     https://travis-ci.org/jekyll/jekyll/jobs/649466901

$ bundle exec jekyll build -s docs --verbose --profile

- done in 6.351 seconds.
+ done in 5.358 seconds.
```

### Memory Profile summary

```diff
--- master https://travis-ci.org/jekyll/jekyll/jobs/649458790
+++ PR     https://travis-ci.org/jekyll/jekyll/jobs/649466902

- Total allocated: 396.91 MB (3624650 objects)
+ Total allocated: 384.73 MB (3490922 objects)
- Total retained:  19.80 MB (107264 objects)
+ Total retained:  19.74 MB (106858 objects)
```

**Comment by ashmaroli** [comment]
### Memory Profile summary

```diff
--- master https://travis-ci.org/github/jekyll/jekyll/jobs/669670236
+++ PR     https://travis-ci.org/github/jekyll/jekyll/jobs/669699899

- Total allocated: 370.27 MB (3400304 objects)
+ Total allocated: 348.19 MB (3168258 objects)
- Total retained:  19.09 MB (108407 objects)
+ Total retained:  18.97 MB (107431 objects)
```
/cc @DirtyF :smiley:

**Comment by DirtyF** [comment]
@jekyllbot: merge +fix

**Pull request merged**
