### PR TITLE
Add a note about script/fmt

### PR DESCRIPTION
**Pull request by chrisfinazzo**

### CODE REVIEW

**Comment by parkr** [comment]
LGTM. Thanks!

**Comment by envygeeks** [comment]
Rubocop should be under the Github Styleguide because we most importantly use the Github Styleguide to setup Rubocop in a similar format.  We do not use many of the rules they define by default.

**Comment by parkr** [comment]
@envygeeks Are you saying you don't like the wording of Chris's addition?

**Comment by parkr** [comment]
@jekyllbot: merge +site

**Pull request merged**
