### PR TITLE
Stash frequently used Drop setter keys for reuse

### PR DESCRIPTION
**Pull request by ashmaroli**
- This is an :zap: optimization change. 

## Summary

`Jekyll::Render` is initialized for every page or document rendered in a site and invariably calls `Jekyll::Drops::Drop#[]=` with a series of keys via its `#run` method:

https://github.com/jekyll/jekyll/blob/7e0f907c6452da3e1364be9c0c873c03067e4db0/lib/jekyll/renderer.rb#L52-L58

---

https://github.com/jekyll/jekyll/blob/7e0f907c6452da3e1364be9c0c873c03067e4db0/lib/jekyll/renderer.rb#L214-L217
https://github.com/jekyll/jekyll/blob/7e0f907c6452da3e1364be9c0c873c03067e4db0/lib/jekyll/renderer.rb#L229-L232
https://github.com/jekyll/jekyll/blob/7e0f907c6452da3e1364be9c0c873c03067e4db0/lib/jekyll/renderer.rb#L234-L237
https://github.com/jekyll/jekyll/blob/7e0f907c6452da3e1364be9c0c873c03067e4db0/lib/jekyll/renderer.rb#L190-L192

---

*The constant is currently private so that it can be replaced with a class-scoped cache in a future version if needed.*

### CODE REVIEW

**Comment by ashmaroli** [comment]
### Third Party Repo Profile Summary

```diff
--- master
+++ PR

- Total allocated: 296.75 MB (2461825 objects)
+ Total allocated: 295.11 MB (2420841 objects)
  Total retained:  43.43 MB (112686 objects)
```

**Review by DirtyF — COMMENTED** [review]
No gain on the build time?

**Comment by ashmaroli** [comment]
> No gain on the build time?

No. Because we're replacing String interpolation with a Hash lookup.
At interpreter level, they're comparably performant.

The notable gain here is reduced allocations in a large site with numerous pages and documents especially because `Jekyll::Renderer#run` will inevitably run for all of them..

**Comment by DirtyF** [comment]
What is a large site? I thought the one was big enough to reflect gain.

**Comment by ashmaroli** [comment]
> What is a large site?

*A site with numerous pages and documents (and excerpts)*

> I thought the one was big enough to reflect gain.

Yes. The third-party site is large enough.
But the proposed change in the PR does not result in greater performance. 
Just reduced allocations and therefore reduced strain on Ruby's Garbage Collector.

**Comment by RamboCacing666** [comment]
> * This is an ⚡ optimization change.
> 
> ## Summary
> `Jekyll::Render` is initialized for every page or document rendered in a site and invariably calls `Jekyll::Drops::Drop#[]=` with a series of keys via its `#run` method:
> 
> https://github.com/jekyll/jekyll/blob/7e0f907c6452da3e1364be9c0c873c03067e4db0/lib/jekyll/renderer.rb#L52-L58
> 
> https://github.com/jekyll/jekyll/blob/7e0f907c6452da3e1364be9c0c873c03067e4db0/lib/jekyll/renderer.rb#L214-L217
> 
> 
> https://github.com/jekyll/jekyll/blob/7e0f907c6452da3e1364be9c0c873c03067e4db0/lib/jekyll/renderer.rb#L229-L232
> 
> 
> https://github.com/jekyll/jekyll/blob/7e0f907c6452da3e1364be9c0c873c03067e4db0/lib/jekyll/renderer.rb#L234-L237
> 
> 
> https://github.com/jekyll/jekyll/blob/7e0f907c6452da3e1364be9c0c873c03067e4db0/lib/jekyll/renderer.rb#L190-L192
> 
> _The constant is currently private so that it can be replaced with a class-scoped cache in a future version if needed._

[Rambo_666]

**Comment by RamboCacing666** [comment]
<

**Comment by ashmaroli** [comment]
@jekyllbot: merge +fix

**Pull request merged**
