### PR TITLE
Slightly, improve PNG compression.

### PR DESCRIPTION
**Pull request by XhmikosR**
Before: 101 KB (103.742 bytes)
After:  100 KB (102.817 bytes)

### CODE REVIEW

**Comment by envygeeks** [comment]
Seeing as there are several vulnerabilities surrounding PNG, provide your compression method so we can verify it before accepting this.  I'm hesitant to accept fonts and images without verification.

**Comment by XhmikosR** [comment]
No, I'm trying to inject malware specific to jekyllrb.com.

Come on, not this crap again.

**Comment by envygeeks** [comment]
It is what it is,  whether your like it or not.  I'm not good at my job because I'm lax.

**Comment by XhmikosR** [comment]
I don't want to flame this anymore, but try to distinguish the people.

```
zopflipng.exe -m --lossy_transparent -y --iterations=1000
```

**Comment by parkr** [comment]
@envygeeks If we could add that to CI, that would be great. Do we already have security vulnerability scanning? If not, then we may not be able to reliably catch things like a potential malware from our known contributors. I certainly wouldn't suspect @XhmikosR or any of our other previous contributors of placing malware in an asset like this. Maybe the system could ensure we'd catch it and do so without having to ask tough and sometimes interrogative questions like this ourselves.

@XhmikosR Haha less than 1,000 bytes! But I'll take it. Thanks!

@jekyllbot: merge +site

**Comment by envygeeks** [comment]
@parkr I can have Hulk scan it behind the scenes like we do our own assets if you want.

**Comment by parkr** [comment]
@envygeeks That would work.

**Pull request merged**
