### PR TITLE
Fix grammar in documentation section

### PR DESCRIPTION
**Pull request by HonkingGoose**
This is a 🔦 documentation change.

## Summary

Change the word 'is' to 'are', because when the subject is plural, we use 'are'.

### CODE REVIEW

**Comment by ashmaroli** [comment]
Thank you for catching and correcting the issue, @HonkingGoose.
For future reference, I recommend providing a short and meaningful commit message for the sake of our Git History.

**Comment by DirtyF** [comment]
@jekyll: merge

**Comment by HonkingGoose** [comment]
@ashmaroli I agree that a good commit message is important! I was not sure what the right commit message should be for one-word changes such as this...

Something like:
> "Fix grammar in documentation"

Or:
> "Fix grammar, change word "is" to "are"

Or:
> "Change word from "is" to "are"

What would you prefer in future?

**Comment by ashmaroli** [comment]
I believe `"Fix grammar in documentation"` summarizes the type of change and the area of code being changed, perfectly &mdash; The change is not in one of the `lib/` files, or `test/` files..

**Pull request merged**
