### PR TITLE
I think you made a typo there

### PR DESCRIPTION
**Pull request by gangsthub**
as seen on:
http://blog.davepoon.net/2015/01/19/setting-up-sass-with-jekyll/
http://markdotto.com/2014/09/25/sass-and-jekyll/#create-a-sass-stylesheet

### CODE REVIEW

**Comment by parkr** [comment]
LGTM.

**Comment by TWiStErRob** [comment]
I think it's actually those articles that are wrong. I removed this colon: https://github.com/TWiStErRob/twisterrob.github.io/blob/master/_config_dev.yml#L22 and the generated CSS style is not expanded any more (from `_config_dev.yml`), but the compressed (the one defined in `_config.yml`), so without colon the setting is being ignored.

**Comment by parkr** [comment]
@TWiStErRob [We strip out the leading `:`](https://github.com/jekyll/jekyll-sass-converter/blob/83101840b53c57d660d41eae27a059755dcdc07e/lib/jekyll/converters/scss.rb#L29), so Chris is correct for the latest code. What version are you using?

**Comment by TWiStErRob** [comment]
Ah the latest. I use GH-Pages gem, maybe 2.6.0... I wish I could use edge on GH.

**Comment by envygeeks** [comment]
@TWiStErRob you can, just build it and push the HTML (`_site`) instead of letting Github build it.

**Comment by pathawks** [comment]
I can confirm that the colon is *not* necessary on Pages Gem v39 (Jekyll 2.4.0)

**Pull request merged**
