### PR TITLE
Ignore final newline in folded YAML string

### PR DESCRIPTION
**Pull request by ashmaroli**
**before:** `{{ site.description }}` =>
```
"Write an awesome description for your new site here. You can edit this line in _config.yml. It
will appear in your document head meta (for Google search results) and in your feed.xml site
description./n"
```

   **after:** `{{ site.description }}` =>
```
"Write an awesome description for your new site here. You can edit this line in _config.yml. It
will appear in your document head meta (for Google search results) and in your feed.xml site
description."
```

### CODE REVIEW

**Comment by ashmaroli** [comment]
> Should we also test that the new site's site.config["description"] doesn't have a trailing newline?

I think its implied..

**Comment by parkr** [comment]
> I think its implied..

That's the point... I don't want it to be implicit, I think if we're making this change we should *explicitly* test it.

**Comment by DirtyF** [comment]
@ashmaroli do you intend to test for a traling newline here?

**Comment by ashmaroli** [comment]
> do you intend to test for a trailing newline here?

Sorry, I forgot all about this. Thanks for reminding.. Will push a commit shortly.

**Comment by ashmaroli** [comment]
Can this be included in `v3.6`?

**Comment by DirtyF** [comment]
@jekyllbot: merge +minor

**Pull request merged**
