### PR TITLE
document 'ordinal' built-in permalink style

### PR DESCRIPTION
**Pull request by willnorris**
ordinal was actually added back in April 2013 in ea753130

### CODE REVIEW

**Comment by parkr** [comment]
:shipit: 

(use byparker.com/go/merge-pr to merge, if you do)

**Comment by willnorris** [comment]
(okay, setting up merge-pr now)

**Comment by parkr** [comment]
(then run bundle exec rake site:publish to push it all up)

**Comment by parkr** [comment]
thanks!

**Comment by willnorris** [comment]
sweet!

I also realized that merge-pr expects you to be on the master branch locally when you run it.  I was still in the feature branch, which resulted in the error: `fatal: The current branch ordinal_docs has no upstream branch.`.  I just had to push that one commit manually... no big deal.

**Comment by parkr** [comment]
hmmm yeah, it should probably fail if you're not on `master` or whatever github-default you've set. `go get` assumes `master`, so I could roll with that convention until it changes (if it changes).

**Pull request merged**
