### PR TITLE
Cache matched defaults sets for given parameters

### PR DESCRIPTION
**Pull request by ashmaroli**
..to avoid unnecessary Array allocations due to `Array#select` for the same given parameters.

### CODE REVIEW

**Comment by pathawks** [comment]
Any benchmarks?

**Comment by pathawks** [comment]
Tried doing some benchmarking, but got the error `undefined method `superclass' for nil:NilClass`

**Comment by pathawks** [comment]
```text
  v3.8.2    287.54
  master    304.47
   #6888    284.61
```

Looks like a nice improvement :+1:

**Comment by ashmaroli** [comment]
Why is our `master` taking so much extra time..?
@pathawks can you run the benchmark once more, please?

**Comment by DirtyF** [comment]
@jekyllbot: merge +minor

**Comment by ashmaroli** [comment]
Awesome!!

**Pull request merged**
