### PR TITLE
Update 01-setup.md

### PR DESCRIPTION
**Pull request by otherpaco**
This is a 🔦 documentation change.

## Summary

If you do not remove or rename index.markdown jekyll starts to render the basic theme/site the moment you use front matter in your index.html file (step 2 ff)

### CODE REVIEW

**Comment by ashmaroli** [comment]
I don't see the point here.
Why not just disable the theme instead?

**Comment by otherpaco** [comment]
@ashmaroli I just started with jekyll and ran in the problem that step 2 of the tutorial is already broken.
Of course disable the theme would be the better way. I will add a sentence in Step 1.
Thanks for the tip

**Comment by ashmaroli** [comment]
> step 2 of the tutorial is already broken.

Please elaborate. What error message did you get..?

**Comment by otherpaco** [comment]
@ashmaroli disbaling the theme is not doing the trick. Seems like you have to remove the index.markdown or rename it to render the index.html.
Just try it yourself, follow step 1 and 2 of the tutorial.
If things are unclear I am happy to open an issue

**Comment by otherpaco** [comment]
@ashmaroli there is no error message just use jekyll 4.0 and follow step 1 and 2 of the tutorial. As long as index.markdown exists Jekyll renders the default site instead of the hello world! downcase.

**Comment by otherpaco** [comment]
@ashmaroli nevermind, my bad I wasnt following step 1 exactly and installed jekyll with the basic theme. I am sorry thank you for your support

**Pull request closed without merging**
