### PR TITLE
Sunset Maruku

### PR DESCRIPTION
**Pull request by alfredxing**
Removes Maruku from the `Gemfile`, removes all references, and removes all Maruku-specific tests.

Also displays the following when `markdown: maruku` is still specified:
> Error: You're using the 'maruku' Markdown processor, which has been removed as of 3.0.0. We recommend you switch to Kramdown. To do this, replace `markdown: maruku` with `markdown: kramdown` in your `_config.yml` file.

Let me know if I missed anything!

Addresses #3098.

### CODE REVIEW

**Comment by alfredxing** [comment]
Hmph. Seems to be an issue with Minitest 5.6.0, which was released today. They messed around with Expectation or something.

**Comment by parkr** [comment]
@alfredxing Thanks so much Alfred!!!!!! Hope exams are going well. Feel free to rebase on latest master – it now has the locked minitest version. :smile:

**Comment by alfredxing** [comment]
Rebased and tests passing!

**Comment by parkr** [comment]
Terrific!!! Thank you :heartbeat:

**Pull request merged**
