### PR TITLE
Update normalize.css to v7.0.0

### PR DESCRIPTION
**Pull request by chrisfinazzo**

### CODE REVIEW

**Comment by pathawks** [comment]
https://github.com/necolas/normalize.css/blob/master/CHANGELOG.md

/cc: @jekyll/documentation

**Comment by DirtyF** [comment]
I'm not sure we need all that is in Normalize (typically forms).

Is it worth taking a shot at [Bootstrap's reboot](https://github.com/twbs/bootstrap/blob/v4-dev/dist/css/bootstrap-reboot.css) and see how it behaves?

**Comment by chrisfinazzo** [comment]
@DirtyF That's a fair point. Can you post a screenshot to show this?

I tried to verify this, but I think I may need to punt my current install and run `script/bootstrap` again. My personal site is only at 3.1 and I've got old versions of Ruby in there and a bunch of other stuff.

Time to start fresh I think.

New job on Monday, new Jekyll install...I'm sensing a pattern here 😄

**Comment by DirtyF** [comment]
@chrisfinazzo Normalize still do the job, even with a few useless kilobytes. 
You're free to revisit this in another PR if you're up to it  🖌 

@jekyllbot: merge +site

**Comment by envygeeks** [comment]
TBQF I think Jekyll should move to reset.css from Bootstrap, it's better.

**Pull request merged**
