### PR TITLE
rogue ~> rouge

### PR DESCRIPTION
**Pull request by parkr**
Thanks to @tombell [who reported this](https://twitter.com/thetombell/status/694410112576913409) to the Twitter ether and @daviddarnes for alerting me to it.

/cc @envygeeks

### CODE REVIEW

**Comment by envygeeks** [comment]
That fix is already merged into the other fixes for that class so I don't see the point of this?

**Comment by parkr** [comment]
> That fix is already merged into the other fixes for that class so I don't see the point of this?

Where?

**Comment by daviddarnes** [comment]
:+1: thanks y'all.

**Comment by tombell** [comment]
:+1: I was actually trying to work out if it was genuinely misspelt or not before saying something. :smile: :

**Comment by envygeeks** [comment]
@tombell it wasn't intentional, when I see rouge I think rogue instead of "this is a valid word for red." so subconsciously corrected it without even realizing since as a gamer rogue is muscled in.

**Comment by daviddarnes** [comment]
@tombell always good to do a sanity check. I saw the tweet after I was having issues with switching a site from pygments to rouge.

**Comment by tombell** [comment]
@envygeeks half of me switching over to rouge was correcting rogue typos (pun intended).

**Comment by parkr** [comment]
Fixed by 65a1fc4120bf5b39e0474ac6ac5c3726bd821b60 in #4428. Thanks, @envygeeks!

**Pull request closed without merging**
