### PR TITLE
Updated the scripts shebang for portability

### LINKED ISSUE #3857: Inconsistent shebangs used in the scripts
There are inconsistent shebangs used in the [scripts](https://github.com/jekyll/jekyll/tree/master/script)

They should all use a shebang that is more portable like:

`#!/usr/bin/env bash`

I can submit a pull request if this is something the core team is interested in implementing.

### PR DESCRIPTION
**Pull request by AJ-Acevedo**
Updated all of the sh and bash shebangs for consistency and portability.
Resolves #3857

### CODE REVIEW

**Comment by envygeeks** [comment]
Please re-add the set -e that was originally on the bash command (in script/test).  Thanks!

**Comment by AJ-Acevedo** [comment]
Will do. Should I squash it in or is a second commit fine?

**Comment by envygeeks** [comment]
Squashing would be great!

**Comment by AJ-Acevedo** [comment]
As per [this issue](https://github.com/sstephenson/rbenv/issues/25) `#!/usr/bin/env bash -e`  can cause problems on some systems.

This will work with the portable shebang
```
#!/usr/bin/env bash
set -e
```

**Pull request merged**
