### PR TITLE
add '/' in pagination sample snippets

### PR DESCRIPTION
**Pull request by WaTer9527**
issue:#4882

### CODE REVIEW

**Comment by pathawks** [comment]
From the docs:

```
paginate_path: "/blog/page:num/"
```

It looks like `paginate_path` is expected to have the slash in front already.

**Comment by WaTer9527** [comment]
thanks

**Comment by pathawks** [comment]
It might not be a bad idea to raise a warning if the slash is missing.

It should be easy and obvious how to do the right thing, and there seems to be room for improvement here.

**Comment by pathawks** [comment]
I was going to work on adding this warning, but it looks as though **jekyll-paginate** is no longer being actively developed.

**Comment by envygeeks** [comment]
See: https://talk.jekyllrb.com/t/announcement-retiring-jekyll-paginate/1004

**Pull request closed without merging**
