### PR TITLE
Remove extra spaces

### PR DESCRIPTION
**Pull request by chrisfinazzo**

### CODE REVIEW

**Comment by kleinfreund** [comment]
:+1:

**Comment by chrisfinazzo** [comment]
Good to see that this passed w/o a problem. However, I did notice errors while running `rake`. None of the tests explicitly failed, but I wonder if this is a known issue...

cc // @parkr @mattr @alfredxing

**Comment by alfredxing** [comment]
@chrisfinazzo Can you paste in the errors that you got?

**Comment by parkr** [comment]
@chrisfinazzo And what `rake` command you were using?

**Comment by parkr** [comment]
These changes didn't cause any errors locally when running `bundle exec rake site:preview`.

**Comment by chrisfinazzo** [comment]
Using Rake 10.4.2.

<pre>[460/532] TestTags#test_: include tag with parameters with symlink'd inc        
  1) Error:
TestTags#test_: include tag with parameters with symlink'd include should not allow symlink includes. :
Errno::ENOENT: No such file or directory @ rb_sysopen - tmp/pages-test
    /Users/Chris/Documents/Jekyll/test/test_tags.rb:351:in `initialize'
    /Users/Chris/Documents/Jekyll/test/test_tags.rb:351:in `open'
    /Users/Chris/Documents/Jekyll/test/test_tags.rb:351:in `block (3 levels) in <class:TestTags>'
    /Users/Chris/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/shoulda-context-1.2.1/lib/shoulda/context/context.rb:413:in `instance_exec'
    /Users/Chris/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/shoulda-context-1.2.1/lib/shoulda/context/context.rb:413:in `block in create_test_from_should_hash'
    /Users/Chris/.rbenv/versions/2.1.0/lib/ruby/2.1.0/minitest/unit.rb:1265:in `run'
    /Users/Chris/.rbenv/versions/2.1.0/lib/ruby/2.1.0/test/unit/testcase.rb:17:in `run'
    /Users/Chris/.rbenv/versions/2.1.0/lib/ruby/2.1.0/minitest/unit.rb:940:in `block in _run_suite'
    /Users/Chris/.rbenv/versions/2.1.0/lib/ruby/2.1.0/minitest/unit.rb:933:in `map'
    /Users/Chris/.rbenv/versions/2.1.0/lib/ruby/2.1.0/minitest/unit.rb:933:in `_run_suite'
    /Users/Chris/.rbenv/versions/2.1.0/lib/ruby/2.1.0/test/unit.rb:663:in `block in _run_suites'
    /Users/Chris/.rbenv/versions/2.1.0/lib/ruby/2.1.0/test/unit.rb:661:in `each'
    /Users/Chris/.rbenv/versions/2.1.0/lib/ruby/2.1.0/test/unit.rb:661:in `_run_suites'
    /Users/Chris/.rbenv/versions/2.1.0/lib/ruby/2.1.0/minitest/unit.rb:884:in `_run_anything'
    /Users/Chris/.rbenv/versions/2.1.0/lib/ruby/2.1.0/minitest/unit.rb:1092:in `run_tests'
    /Users/Chris/.rbenv/versions/2.1.0/lib/ruby/2.1.0/minitest/unit.rb:1079:in `block in _run'
    /Users/Chris/.rbenv/versions/2.1.0/lib/ruby/2.1.0/minitest/unit.rb:1078:in `each'
    /Users/Chris/.rbenv/versions/2.1.0/lib/ruby/2.1.0/minitest/unit.rb:1078:in `_run'
    /Users/Chris/.rbenv/versions/2.1.0/lib/ruby/2.1.0/minitest/unit.rb:1066:in `run'
    /Users/Chris/.rbenv/versions/2.1.0/lib/ruby/2.1.0/test/unit.rb:27:in `run'
    /Users/Chris/.rbenv/versions/2.1.0/lib/ruby/2.1.0/test/unit.rb:780:in `run'
    /Users/Chris/.rbenv/versions/2.1.0/lib/ruby/2.1.0/test/unit.rb:372:in `block (2 levels) in autorun'
    /Users/Chris/.rbenv/versions/2.1.0/lib/ruby/2.1.0/test/unit.rb:33:in `run_once'
    /Users/Chris/.rbenv/versions/2.1.0/lib/ruby/2.1.0/test/unit.rb:371:in `block in autorun'

[480/532] TestTags#test_: relative include tag with variable and liquid         
  2) Error:
TestTags#test_: relative include tag with variable and liquid filters with symlink'd include should not allow symlink includes. :
Errno::ENOENT: No such file or directory @ rb_sysopen - tmp/pages-test
    /Users/Chris/Documents/Jekyll/test/test_tags.rb:642:in `initialize'
    /Users/Chris/Documents/Jekyll/test/test_tags.rb:642:in `open'
    /Users/Chris/Documents/Jekyll/test/test_tags.rb:642:in `block (3 levels) in <class:TestTags>'
    /Users/Chris/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/shoulda-context-1.2.1/lib/shoulda/context/context.rb:413:in `instance_exec'
    /Users/Chris/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/shoulda-context-1.2.1/lib/shoulda/context/context.rb:413:in `block in create_test_from_should_hash'
    /Users/Chris/.rbenv/versions/2.1.0/lib/ruby/2.1.0/minitest/unit.rb:1265:in `run'
    /Users/Chris/.rbenv/versions/2.1.0/lib/ruby/2.1.0/test/unit/testcase.rb:17:in `run'
    /Users/Chris/.rbenv/versions/2.1.0/lib/ruby/2.1.0/minitest/unit.rb:940:in `block in _run_suite'
    /Users/Chris/.rbenv/versions/2.1.0/lib/ruby/2.1.0/minitest/unit.rb:933:in `map'
    /Users/Chris/.rbenv/versions/2.1.0/lib/ruby/2.1.0/minitest/unit.rb:933:in `_run_suite'
    /Users/Chris/.rbenv/versions/2.1.0/lib/ruby/2.1.0/test/unit.rb:663:in `block in _run_suites'
    /Users/Chris/.rbenv/versions/2.1.0/lib/ruby/2.1.0/test/unit.rb:661:in `each'
    /Users/Chris/.rbenv/versions/2.1.0/lib/ruby/2.1.0/test/unit.rb:661:in `_run_suites'
    /Users/Chris/.rbenv/versions/2.1.0/lib/ruby/2.1.0/minitest/unit.rb:884:in `_run_anything'
    /Users/Chris/.rbenv/versions/2.1.0/lib/ruby/2.1.0/minitest/unit.rb:1092:in `run_tests'
    /Users/Chris/.rbenv/versions/2.1.0/lib/ruby/2.1.0/minitest/unit.rb:1079:in `block in _run'
    /Users/Chris/.rbenv/versions/2.1.0/lib/ruby/2.1.0/minitest/unit.rb:1078:in `each'
    /Users/Chris/.rbenv/versions/2.1.0/lib/ruby/2.1.0/minitest/unit.rb:1078:in `_run'
    /Users/Chris/.rbenv/versions/2.1.0/lib/ruby/2.1.0/minitest/unit.rb:1066:in `run'
    /Users/Chris/.rbenv/versions/2.1.0/lib/ruby/2.1.0/test/unit.rb:27:in `run'
    /Users/Chris/.rbenv/versions/2.1.0/lib/ruby/2.1.0/test/unit.rb:780:in `run'
    /Users/Chris/.rbenv/versions/2.1.0/lib/ruby/2.1.0/test/unit.rb:372:in `block (2 levels) in autorun'
    /Users/Chris/.rbenv/versions/2.1.0/lib/ruby/2.1.0/test/unit.rb:33:in `run_once'
    /Users/Chris/.rbenv/versions/2.1.0/lib/ruby/2.1.0/test/unit.rb:371:in `block in autorun'
</pre>

**Comment by parkr** [comment]
Ah, we don't `mkdir -p tmp` here...

**Pull request merged**
