### PR TITLE
Add a Community section, resolves #5057

### PR DESCRIPTION
**Pull request by chrisfinazzo**
Cleanup of the original PR.

👋🏻 Thanks, @mneumegen!

cc/ @jekyll/documentation

### CODE REVIEW

**Comment by parkr** [comment]
Thanks for picking this up, @chrisfinazzo! I have a policy of asking folks to include attribution if they take from another PR. If you don't mind, I'd like to see @mneumegen's commit preserved and a subsequent commit for your changes. Thanks! We can re-open once that is complete. 😄

**Comment by chrisfinazzo** [comment]
OK, will update. Can this change land here (`cherry-pick` [8e7072c][]) or does it have to be separate?

[8e7072c]: https://github.com/mneumegen/jekyll/commit/8e7072c8129fd0bd21cca0c04f3ca8bc6e81735c

**Comment by parkr** [comment]
@chrisfinazzo 8e7072c should be a separate commit but isn't ready to land on master. Ideally your PR would be based off of Mike's branch.

**Comment by chrisfinazzo** [comment]
👌🏻

**Pull request closed without merging**
