### PR TITLE
Rouge does not close div after highlighting ends

### PR DESCRIPTION
**Pull request by tomasfejfar**
As per request in #4432. I tried my best to write something meaningful in Ruby - it's not my language of choice :)

### CODE REVIEW

**Comment by tomasfejfar** [comment]
And travis runs now! Great!

**Comment by parkr** [comment]
Ok, taking a look at this today, I see that the test is invalid. You're actually highlighting Liquid there.

I modified the test to submit the code you have as the post content and it looks fine to me and passes:

```diff
diff --git a/test/test_tags.rb b/test/test_tags.rb
index 0af3016..b8cffa8 100644
--- a/test/test_tags.rb
+++ b/test/test_tags.rb
@@ -319,7 +319,11 @@ EOS

     context "post content has highlight tag with linenumbers" do
       setup do
-        fill_post <<-EOS
+        create_post <<-EOS
+---
+title: This is a test
+---
+
 This is not yet highlighted
 {% highlight php linenos %}
 test
@@ -330,7 +334,7 @@ EOS
       end

       should "should stop highlighting at boundary" do
-        assert_match "<p>This is not yet highlighted</p> <div class=\"highlight\"><pre><code class=\"language-php\" data-lang=\"php\"> <table style=\"border-spacing: 0\"> <tbody> <tr> <td class=\"gutter gl\" style=\"text-align: right\"> <pre class=\"lineno\">1</pre> </td> <td class=\"code\"><pre>test<span class=\"w\"></span></pre> </td> </tr> </tbody> </table></code></pre></div> <p>This should not be highlighted, right?</p>", @result
+        assert_match "<p>This is not yet highlighted</p>\n\n<figure class=\"highlight\"><pre><code class=\"language-php\" data-lang=\"php\"><table style=\"border-spacing: 0\"><tbody><tr><td class=\"gutter gl\" style=\"text-align: right\"><pre class=\"lineno\">1</pre></td><td class=\"code\"><pre>test<span class=\"w\">\n</span></pre></td></tr></tbody></table></code></pre></figure>\n\n<p>This should not be highlighted, right?</p>", @result
       end
     end
```

**Comment by tomasfejfar** [comment]
Could you backtrack why does it behave the same way in #4432 ?

**Comment by parkr** [comment]
@tomasfejfar It could be an issue with your version of Jekyll or Rouge. I was using `HEAD` Jekyll and the latest release of Rouge (1.10.1) and had no problem.

**Pull request closed without merging**
