### PR TITLE
Implement custom delegators for drop methods

### PR DESCRIPTION
**Pull request by ashmaroli**
## Summary

While analyzing memory profile reports, I noticed that **every call** to a *delegated method* (generated by using Ruby's `Forwardable` module) results in allocation of an empty array.

So, I propose to use an *in-house* set of delegator factories that addresses the above observation.

### CODE REVIEW

**Comment by ashmaroli** [comment]
### Memory Profile Summary

```diff
--- master https://travis-ci.org/github/jekyll/jekyll/jobs/687015473
+++ PR     https://travis-ci.org/github/jekyll/jekyll/jobs/687992324

- Total allocated: 299.74 MB (3113114 objects)
- Total retained:  19.37 MB (108879 objects)
+ Total allocated: 297.45 MB (3055734 objects)
+ Total retained:  19.37 MB (108887 objects)
```

**Comment by ashmaroli** [comment]
@parkr @mattr-  I would love it if you could take a look at the proposed changes here and provide feedback.
Thanks.

**Comment by ashmaroli** [comment]
### Workflow Summary

```diff
--- master https://github.com/jekyll/jekyll/runs/1130077147
+++ PR     https://github.com/jekyll/jekyll/runs/1133281825

- done in 25.671 seconds.
- done in 27.211 seconds.
- done in 25.857 seconds.
+ done in 24.043 seconds.
+ done in 25.37 seconds.
+ done in 24.911 seconds.

- Total allocated: 282.43 MB (2467827 objects)
+ Total allocated: 239.88 MB (1404029 objects)
  Total retained:  37.81 MB (112069 objects)
```

**Review by parkr — APPROVED** [review]
This is neat! Nice optimization.

**Comment by DirtyF** [comment]
@jekyll: merge +dev

**Pull request merged**
