### PR TITLE
need subcommand build

### PR DESCRIPTION
**Pull request by shingo-nakanishi**
simply run the `jekyll` shows

```
A subcommand is required. 
jekyll 3.2.1 -- Jekyll is a blog-aware, static site generator in Ruby
``` 

need subcommand build

### CODE REVIEW

**Comment by parkr** [comment]
Yes! Thank you. LGTM.

**Comment by shingo-nakanishi** [comment]
Thank you. When update https://jekyllrb.com/docs/deployment-methods/ ?

**Comment by parkr** [comment]
@jekyllbot: merge +site

**Comment by parkr** [comment]
@shingo-nakanishi Now! I have to merge and then deploy from my workstation.

**Pull request merged**
