### PR TITLE
Fix the formatting

### PR DESCRIPTION
**Pull request by chrisfinazzo**

### CODE REVIEW

**Comment by envygeeks** [comment]
I don't think this fixes anything, but I do think that it makes the formatting feel off.

**Comment by envygeeks** [comment]
I guess it would be fine if they weren't forced onto their own line, but if you want to make it inline but when it being on it's own line, it should be a block like it was, unless it was an accident it was made "`" instead of "```"

**Comment by parkr** [comment]
I like the way the 4-space indents give these lines a significance and separation that is easier on the eye and the brain. Thanks for the contribution, but I think I'm going to leave it as is. :+1:

**Comment by parkr** [comment]
The style could use an update tho:

screen shot 2015-08-27 at 1 25 54 pm

**Comment by chrisfinazzo** [comment]
@parkr, that's what I was getting at, for whatever reason these were not indented properly. I'll look at master again to see what's actually going on (my local branch has obviously diverged from this).

**Comment by chrisfinazzo** [comment]
Huh, indented by 4 spaces and...nothing. No text styles whatsoever. 😒

**Comment by envygeeks** [comment]
That's because 4 spaces and triple grave are treated different than {% highlight %} but you can't use {% highlight %} on that document because it's actually meant for Github (it's linked through by every ticket creation to nag you to follow the rules)

**Comment by parkr** [comment]
@chrisfinazzo Our Markdown converter should add a `<pre>` – maybe we can add the style to that on this page?

**Comment by envygeeks** [comment]
Manually wrap it: https://github.com/jekyll/jekyll/blob/master/lib/jekyll/tags/highlight.rb#L116

**Comment by envygeeks** [comment]
With only the `<figure>` the rest of it is already created.

**Pull request closed without merging**
