### PR TITLE
Update Minitest, Allow multiple versions of ActiveSupport.

### PR DESCRIPTION
**Pull request by envygeeks**
TODO:

- [ ] Use describe.
- [x] Make sure cucumber still works.
- [x] Just use Minitest and rely always on latest.
- [ ] Remove ActiveSupport legacy dependency from tests.
- [ ] Fix an edge that Minitest discovered with collections and disappearing files.

### CODE REVIEW

**Comment by envygeeks** [comment]
Also, I don't know exactly what ActiveSupport is used for, so until I know I've a complete matrix.

**Comment by parkr** [comment]
Yeah I'd really love to have that complete matrix removed before we move forward – waiting 40 minutes for a build to give the green or red is not acceptable to me down the road. But for testing :+1:

**Comment by envygeeks** [comment]
I don't even know why we have ActiveSupport in there, any idea why?

**Comment by parkr** [comment]
If you remove it, what breaks? :P

**Comment by penibelst** [comment]
Does this mean you switch to Minitest like I proposed in https://github.com/jekyll/jekyll/pull/2549? Or will you use Rspec beside Minitest?

**Comment by envygeeks** [comment]
@parkr can probably explain the plans a bit better since he's the one who gave me the idea for (RSpec) but I've been working on Minitest for Jekyll 2 (as to mostly keep legacy, legacy while giving updates) and RSpec for Jekyll 3 (without Minitest.)

**Comment by parkr** [comment]
`master` is targeting Jekyll 3.

**Comment by parkr** [comment]
I'm cool with Minitest, I just prefer RSpec usually.

**Comment by parkr** [comment]
@envygeeks Want to tackle just one piece in a PR? Maybe upgrading minitest? I'd love profiling of the specs :)

**Comment by envygeeks** [comment]
@parkr sure! I'll strip down this pull later this week and just update minitest.

**Comment by envygeeks** [comment]
I'm closing this since I'm rebasing ontop of the stuff that was already merged/implemented.

**Comment by envygeeks** [comment]
As well as the stuff I've started adding to the tests that I'll be pushing up this weekend.

**Pull request closed without merging**
