### PR TITLE
Add json extension to list of directory indices

### LINKED ISSUE #6348: Support index.json in DirectoryIndex
Hey there, I'm using Jekyll collections to generate JSON APIs. In order to have more flexible, prettier URLs, it would be nice if Jekyll supported `index.json` in the Webrick DirectoryIndex. This would allow you to have API URLs like `/api/agency/gsa/` instead of `/api/agency/gsa.json`. Currently, `jekyll serve` just shows the directory listing because it doesn't know to look for `index.json` in directories. I've got my production config setup this way, so I'm just looking for the development server to also have this behavior. I'm happy to submit a pull request if you're OK with this addition.

- [ ] I believe this to be a bug, not a question about using Jekyll.
- [ ] I updated to the latest Jekyll (or) if on GitHub Pages to the latest `github-pages`
- [ ] I ran `jekyll doctor` to check my configuration
- [x] I read the CONTRIBUTION file at https://jekyllrb.com/docs/contributing/
- [x] This is a feature request.

### PR DESCRIPTION
**Pull request by adborden**
Fixes #6348

### CODE REVIEW

**Comment by pathawks** [comment]
Now Rubocop says `webrick_opts` has too many lines. 🙃

**Comment by ashmaroli** [comment]
one way out is to move the entire array to a class constant or a new private method if that's better..

**Comment by pathawks** [comment]
> move the entire array to a class constant

✅:+1:

**Comment by DirtyF** [comment]
@adborden Thanks for this excellent first contrib! ❤️ 

@jekyllbot: merge +minor

**Comment by parkr** [comment]
Woohoo! Well done ✨

**Comment by parkr** [comment]
@adborden This has shipped on GitHub Pages and will roll out to 100% of sites over the next few hours.

**Comment by adborden** [comment]
On Thu, 2017-11-16 at 08:39 -0800, Parker Moore <notifications@github.com> wrote:
> @adborden This has shipped on GitHub Pages and will roll out to 100% of sites over the next few hours.

Awesome, thank you!

--
Aaron D Borden
Human and hacker

**Pull request merged**
