### PR TITLE
Memoize the return value of Document#url

### PR DESCRIPTION
**Pull request by parkr**
Running `bundle exec rake site:generate` locally, this brings generation time from 16 seconds down to 8 seconds.

```text
done in 16.421 seconds.
```

```text
done in 8.685 seconds.
```

### CODE REVIEW

**Comment by parkr** [comment]
Lol @ ruby. Also lol @ us not catching this! If you haven't checked out stackprof, it is _so_ cool.

```console
$ export BENCHMARK=1
$ bundle install
$ script/stackprof # measures cpu
$ script/stackprof object # measures memory
```

**Comment by parkr** [comment]
@jekyllbot:  merge +fix

**Comment by pup** [comment]
@jekyllbot: merge +fix

**Comment by pup** [comment]
@parkr could it be that jekyllbot doesn't accept comments that have multiple spaces in them (like yours did)?

**Comment by parkr** [comment]
Perhaps! I'm not sure. Thanks for submitting the correction for me :)

**Comment by ianthehenry** [comment]
This breaks, e.g., generators that programatically calculate permalinks -- you must now explicitly un-set the `url` property after setting the permalink to forget the memoized value.

I feel that as it used to be a dependent property, changing any of the values it depends on should invalidate the cache. But I don't know how to do that when it depends on values stored in hashes...

**Comment by parkr** [comment]
Hey @ianthehenry! Can you give a simple example? We could set the `@url` value to `nil` if we can catch the changes. This change is important to keep, as it is a significant performance gain.

**Comment by ianthehenry** [comment]
Here was a plugin that I had ~~written~~ copied almost verbatim from StackOverflow:

```ruby
# Because we put our posts in their own directories:
#
# _posts/2017-05-11-foo/index.md
#
# Instead of their own files:
#
# _posts/2017-05-11-foo.md
#
# The default slug is "foo/index". But this is annoying, so we strip it.

module Jekyll
  class PermalinkRewriter < Generator
    safe true
    priority :low

    def generate(site)
      site.posts.docs.each do |post|
        unless post.data.member?('permalink')
          post.data['permalink'] = post.data['slug'].sub(/\/index$/, '') + '/'
        end
      end
    end
  end
end
```

After upgrading to 3.5.2, I had to make this tweak:

```ruby
module Jekyll
  class Document
    def invalidate_url
      @url = nil
    end
  end

  class PermalinkRewriter < Generator
    safe true
    priority :low

    def generate(site)
      site.posts.docs.each do |post|
        unless post.data.member?('permalink')
          post.data['permalink'] = post.data['slug'].sub(/[\/-]index$/, '') + '/'
          # As of 3.5.2, post.url is memoized, and not recalculated when one of
          # the properties it's based on changes.
          #
          # https://github.com/jekyll/jekyll/pull/6266
          post.invalidate_url
        end
      end
    end
  end
end
```

Which, you know, was after a bit of head-scratching and then looking for probable commit messages.

I suppose I could also just override the `url` getter on a post. That feels less hacky than this, I suppose. But yeah; it was a thing that used to work that stopped working.

**Pull request merged**
