### PR TITLE
Lock coffee-script-source

### PR DESCRIPTION
**Pull request by jekyllbot**
PR automatically created for @pathawks.

```text
Lock coffee-script-source

v1.12 was causing all of our tests to fail
https://github.com/jekyll/jekyll/pull/5661#issuecomment-267381479
```

### CODE REVIEW

**Comment by pathawks** [comment]
I don't know if this belongs here or upstream; I just don't want our tests to crumble.
https://github.com/jekyll/jekyll/pull/5661#issuecomment-267381479

/cc @jekyll/ecosystem

**Comment by pathawks** [comment]
@jekyllbot Assigning me to review my own changes is not helpful, although I understand why you got confused. 🤖

**Comment by ashmaroli** [comment]
Team captains should have `Lieutenants` / `Vice-Captains` / `Deputies` :smile:

**Comment by parkr** [comment]
Let's do this in `jekyll-coffeescript`!

**Comment by pathawks** [comment]
jekyll/jekyll-coffeescript#16

**Pull request closed without merging**
