### PR TITLE
Update Rubocop gem to 0.75.0

### LINKED ISSUE #7765: Update dependency constraint to allow for rubocop v0.74.0
Hey there! :wave:

I noticed that the constraint you have for rubocop doesn't allow for the latest version to be used.

The constraint I found was `~> 0.72.0`, and the latest version available is `0.74.0`.

Can you look into updating that constraint so our users can use the latest and greatest version? Thanks! :revolving_hearts:

### PR DESCRIPTION
**Pull request by karouf**
This is closing an open issue but not really a 🐛 bug fix.

## Summary

I've updated the Rubocop gem to the latest version released and I fixed the new offenses reported when running the tests.

## Context

Closes #7765

### CODE REVIEW

**Comment by ashmaroli** [comment]
Duplicate of (or prior art at) #7846

**Comment by ashmaroli** [comment]
From Travis log:
```
Rubocop 0.75.0
Inspecting 130 files
..../home/travis/build/jekyll/jekyll/lib/jekyll/command.rb: Warning: no department given for RescueException. Run `rubocop -a --only Migration/DepartmentName` to fix.
/home/travis/build/jekyll/jekyll/lib/jekyll/command.rb: Warning: no department given for RescueException. Run `rubocop -a --only Migration/DepartmentName` to fix.
...................................../home/travis/build/jekyll/jekyll/lib/jekyll/frontmatter_defaults.rb: Warning: no department given for PredicateName. Run `rubocop -a --only Migration/DepartmentName` to fix.
/home/travis/build/jekyll/jekyll/lib/jekyll/frontmatter_defaults.rb: Warning: no department given for PredicateName. Run `rubocop -a --only Migration/DepartmentName` to fix.
........................./home/travis/build/jekyll/jekyll/lib/jekyll/renderer.rb: Warning: no department given for AbcSize. Run `rubocop -a --only Migration/DepartmentName` to fix.
/home/travis/build/jekyll/jekyll/lib/jekyll/renderer.rb: Warning: no department given for AbcSize. Run `rubocop -a --only Migration/DepartmentName` to fix.
/home/travis/build/jekyll/jekyll/lib/jekyll/renderer.rb: Warning: no department given for RescueException. Run `rubocop -a --only Migration/DepartmentName` to fix.
/home/travis/build/jekyll/jekyll/lib/jekyll/renderer.rb: Warning: no department given for RescueException. Run `rubocop -a --only Migration/DepartmentName` to fix.
../home/travis/build/jekyll/jekyll/lib/jekyll/static_file.rb: Warning: no department given for ParameterLists. Run `rubocop -a --only Migration/DepartmentName` to fix.
/home/travis/build/jekyll/jekyll/lib/jekyll/static_file.rb: Warning: no department given for ParameterLists. Run `rubocop -a --only Migration/DepartmentName` to fix.
........./home/travis/build/jekyll/jekyll/lib/jekyll/utils.rb: Warning: no department given for PredicateName. Run `rubocop -a --only Migration/DepartmentName` to fix.
/home/travis/build/jekyll/jekyll/lib/jekyll/utils.rb: Warning: no department given for PredicateName. Run `rubocop -a --only Migration/DepartmentName` to fix.
.....................................................
```

**Comment by karouf** [comment]
I filtered issues to exclude those having PR attached so I missed this one... Sorry for the noise then I'm closing that.
Funny I never had the warnings running `script/cibuild` like in the Travis build.

Unrelated: the failed test in the [Ubuntu test suite](https://github.com/jekyll/jekyll/pull/7851/checks?check_run_id=251711753) seems to be flaky. I encountered it several times during `script/cibuild` runs but never consistently. Should I open an issue for that?

**Comment by ashmaroli** [comment]
> Should I open an issue for that?

@karouf Its a known issue. I've attempted to resolve it multiple times and failed.
Don't bother filing an issue for that. Since the failures are inconsistent, the ticket will only lead to confusion for someone attempting to resolve it &mdash; there's no guarantee if they'll encounter the failure locally for the same test(s) mentioned in the ticket.

**Comment by karouf** [comment]
Ok thanks for saving me some time trying to hunt that down! :)

**Pull request closed without merging**
