### PR TITLE
Include theme directories in default gemspec

### PR DESCRIPTION
**Pull request by benbalter**
See https://github.com/jekyll/minima/pull/6.

We need to *include* the theme directories, not *exclude* them.

### CODE REVIEW

**Comment by benbalter** [comment]
As written, this PR will *only* include files in the theme directories. Do we want to include the LICENSE? I think the other files are safe to not include.

**Comment by parkr** [comment]
Durrrrr. Thanks @benbalter!

> Do we want to include the LICENSE? I think the other files are safe to not include.

Yeah! If we're generating a license and readme, we should include them.

Thank you!

**Comment by parkr** [comment]
LGTM.

**Comment by benbalter** [comment]
@parkr Can I LGTM my own PR?

**Comment by benbalter** [comment]
Also to note, we should update minima once this merges.

**Comment by parkr** [comment]
> @parkr Can I LGTM my own PR?

Yep!

> Also to note, we should update minima once this merges.

To use this method? Sure!

LGTM.

**Comment by benbalter** [comment]
LGTM.

**Comment by parkr** [comment]
@jekyllbot: merge +bug

**Comment by wommy** [comment]
https://github.com/jekyll/minima/commit/7629d352a05f809fe1cda3e10c62bbd4a495e173

**Comment by wommy** [comment]
@benbalter @parkr thoughts on my above?

**Comment by benbalter** [comment]
@wommy you're spot on your with commit comment. Mind opening a dedicated issue in this repo to figure out which approach is best to harmonize the three?

**Pull request merged**
