### PR TITLE
Create Dockerfile

### PR DESCRIPTION
**Pull request by chb0github**
builds as: `docker build -t jekyll .`
Runs as `docker run -d --name jekyll -p 4000:4000 -v $PWD:/usr/app/jekyll jekyll`

issue: #5844

### CODE REVIEW

**Comment by Crunch09** [comment]
I am not familiar with docker but is maybe [jekyll/docker](https://github.com/jekyll/docker) the correct place to put this into ?

**Comment by chb0github** [comment]
Oh, I didn't see that. Let me have a look

**Comment by chb0github** [comment]
That repo hasn't had a check-in in 6 months. I submitted a PR but really, it's 1 file. Not sure why anyone would have an entirely different repo for this job. 

Since you're not familiar with it @Crunch09 - basically, once you have this file and build the image, anyone can run jekyll without having to install ruby or any gems as long as they have [docker](https://www.docker.com/).

**Comment by parkr** [comment]
The jekyll/docker repo was updated 3 days ago and I'd like to keep user-facing Dockerfiles there. Thanks!

**Pull request closed without merging**
