### PR TITLE
Update version in `config.yml` via YAML load / dump

### PR DESCRIPTION
**Pull request by Crunch09**
As discussed in #6676 , I've already ran the command once, so we can see what changes in the `config.yml` file when running this command (as it normalizes the YAML output)

### CODE REVIEW

**Comment by DirtyF** [comment]
@Crunch09 nice extra feature 😃

**Comment by ashmaroli** [comment]
@Crunch09 anyway to get the indentation back to two spaces?

**Comment by Crunch09** [comment]
@ashmaroli Good point, there should be an option i think! I'll check

**Comment by DirtyF** [comment]
It also remove any comments left in the file 😕

**Comment by ashmaroli** [comment]
The docs built fine locally so i guess the indentation is not that much of an issue for the list items (**T.I.L.**)

**Comment by Crunch09** [comment]
Yeah, if we want to have comments in there we need to stick with the regex i'm afraid :(

@ashmaroli Indentation is already set to 2 by default. I assume you meant the `plugins` and `exclude` arrays? I don't have enough YAML knowledge but i think there is no need for spaces so the YAML implementation doesn't add them.

**Comment by ashmaroli** [comment]
Yes, I was referring to them.. but since everything works fine, guess its okay then.. just that the config file looks a bit crowded to me now..

**Comment by DirtyF** [comment]
This file is rarely edited so I guess it's OK.

@jekyllbot: merge +site

**Pull request merged**
