### PR TITLE
Update Ruby versions in travis.yml

### PR DESCRIPTION
**Pull request by ashmaroli**
Add Ruby v2.3.1 to travis.yml. Leaving everything else as is.

### CODE REVIEW

**Comment by envygeeks** [comment]
2.3.1 is a successor to 2.3.0 not an addition to it.  Can you please adjust your pull to reflect that?

**Comment by ashmaroli** [comment]
wasn't sure whether to add or replace.

also upgrade?
 - 2.2.4 -> 2.2.5
 - 2.1.8 -> 2.1.9

jruby latest is 9.1.2.0 .. cant find that in the travis docs...

**Comment by envygeeks** [comment]
Hold tight, I'm cleaning up the .travis.yml file, at that point you can ship a cleaner pull that does all that.

**Comment by envygeeks** [comment]
@ashmaroli okay, you are good to update, I cleaned up .travis.yml so that you could just update the RVM field without having to worry about updating many values just to update our Rubies.

**Comment by envygeeks** [comment]
To add another note, yes, you can update all of them if you wish! We use the succesor pattern, so if there is a new minor release it just replaces the old minor version rather than holding a dozen versions of Ruby, we do this because there is no need to waste Travis-CI capacity.

**Comment by ashmaroli** [comment]
okay.. will test jruby 9.1.2.0 also..

**Comment by ashmaroli** [comment]
travis is still at gem version 2.5.1 instead of 2.6.6

**Comment by parkr** [comment]
LGTM, pending Travis passing.

**Comment by ashmaroli** [comment]
Travis build passed..

**Comment by envygeeks** [comment]
LGTM.

**Comment by envygeeks** [comment]
@jekyllbot: merge +dev

**Pull request merged**
